### ISSUE TITLE
Add filter for inpost metabox context

### ISSUE THREAD

**Issue by danielpost** [sybrew/the-seo-framework#100]
Correct me if I'm wrong, but I couldn't find a filter to modify the inpost metabox context (in inpost.class.php, line 164). For a project I'm working on I'd prefer to show it on the side.

**Comment by sybrew** [comment]
Sure thing! Commit's coming in...

```
/**
 * Applies filters the_seo_framework_metabox_id : string
 *
 * Alters the inpost metabox priority and class ID.
 *
 * @since 2.9.0
 *
 * @param string $context, default 'normal'. Accepts 'normal', 'side' and 'advanced'.
 */
$context = (string) \apply_filters( 'the_seo_framework_metabox_context', 'normal' );
```

Will be shipped with 2.9 😄

**Comment by Aetles** [comment]
Will this be added to the [API docs](https://theseoframework.com/docs/api/filters/) in the future?

**Comment by sybrew** [comment]
@Aetles I'm still working on automated documentation; so that all filters will be properly and instantaneously documented. The API docs is now short of about 50 filters.

In the meantime, if you require any specific modifications, you can always ask for support 😄

**Comment by Aetles** [comment]
It's ok, I figured it out. :) (I'm just the kind of type that really tries to solves things by finding information myself before resorting to support questions… 😊 )

**Comment by sybrew** [comment]
@Aetles That's the best type 😄 But, don't hesitate to ask before you tend to spend hours figuring out an issue.
