### ISSUE TITLE
editor user and resize social image

### ISSUE THREAD

**Issue by domegang** [sybrew/the-seo-framework#101]
hi,
on my blog an editor reported me an error during the resize of the social image. My debug log files is blank and i don't understand the problem. This problem occurs with non-admin users.  it can be linked to the user roles/permissions ? How i can solve. Thank you

**Comment by sybrew** [comment]
I'll go test it out ASAP. Will report back.

**Comment by sybrew** [comment]
Confirmed! 

The user requires "customizer" permissions, and it's very difficult to track and see on how to adjust this. 
I think cropping wasn't meant to be used in plugins 😅. Might require a rewrite...

**Comment by sybrew** [comment]
Okay, so here's the deal:

1. WordPress [blocks users who don't have customizer access](https://github.com/WordPress/WordPress/blob/62061bab5658386d0bbfbfeb3f89be883fd75ec4/wp-admin/includes/ajax-actions.php#L3167). I believe this is wrong.
2. WordPress attaches permissions to each attachment, based on who uploaded it. Therefore, [they only create nonces for specific users](https://github.com/WordPress/WordPress/blob/62061bab5658386d0bbfbfeb3f89be883fd75ec4/wp-includes/media.php#L3136-L3140).
3. This nonce must be used for security reasons, [we use it](https://github.com/sybrew/the-seo-framework/blob/1a1c96549f56e5f9f6a4d6dd223793906171c8de/lib/js/tsf.js#L1871) and [it is checked against](https://github.com/WordPress/WordPress/blob/62061bab5658386d0bbfbfeb3f89be883fd75ec4/wp-admin/includes/ajax-actions.php#L3166).

Now, the reason at "1." can be circumvented. The 2nd and 3rd rule are plainly annoying and requires a lot of thinking before we counter them.

So, there are several solutions, what do you think?
1. Use our own nonce. The old image isn't overwritten, so why would we require permissions?
2. Only list images the user is allowed to edit (it's possible.. but I don't know if this is easy).
3. Set up our own error code, which is annoyingly displayed only at the far end.
4. Ignore this whole deal and just circumvent issue 1.

**Comment by sybrew** [comment]
I went for 1., by the way 😄. 

The permissions are now `upload_files`, which excludes "Contributors" but include everyone above.
https://codex.wordpress.org/Roles_and_Capabilities

Cheers!
