### ISSUE TITLE
XSL stylesheet can't be loaded on domain mismatch

### ISSUE THREAD

**Issue by sybrew** [sybrew/the-seo-framework#102]
Simply put, here's the scenario:

1. The home URL is set to https://example.com/
2. Go to http://www.example.com/sitemap.xml
3. The sitemap is output correctly.
4. The sitemap stylesheet links to https://example.com/sitemap.xsl
5. Domain mismatch.

This error is then output:
`Unsafe attempt to load URL https://example.com/sitemap.xsl from frame with URL http://www.example.com/sitemap.xml. Domains, protocols and ports must match.`

HTTP/HTTPS, www/non-www, or a domain alias will cause this error.

What happens on a mismatch?
* The user sees a blank page.
* The Search Engine sees the sitemap.

Possible solutions:
1. Ignore this fact. Search Engines don't mind.
2. Redirect user to Home URL's sitemap on domain mismatch (`$_SERVER/$_REQUEST`).
3. Disable stylesheet link on mismatch.

**Comment by LeBaux** [comment]
Just to sump up my experience, website set to use https://www in wordpress:
https://www.slunickozlin.cz

I am forcing URL rewrites via **.htaccess**:

```
# BEGIN Force http to https
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteCond %{HTTPS} !=on
RewriteRule ^(.*) https://%{HTTP_HOST}/$1 [R=301,L] 
</IfModule>
# END Force http to https
```

https://www.slunickozlin.cz/sitemap.xml works correctly, as expected
http://www.slunickozlin.cz/sitemap.xml redirects correctly to ssl version

http://slunickozlin.cz/sitemap.xml produces stylesheet error
https://slunickozlin.cz/sitemap.xml produces stylesheet error

One little detail is that in Firefox I am not ending up on blank screen, r[ather with this](http://i.imgur.com/T6ZLsf2.png).
As always, I am not sure if this helps in any way. 😛

**Comment by sybrew** [comment]
@LeBaux Yes, a `.htaccess` rule is the best way to go. However, I can't expect everyone to follow your lead in that.

Also, the .htaccess rule you use doesn't evade multi-domain sites issues which are also described in this issue listing.

In the end, this can be seen as a bug caused ultimately by an incomplete website configuration. 

So, this isn't about prevention, it's about solving 😄. The only question left is: "how?".

**Comment by sybrew** [comment]
The redirect could lead to unwanted side effects and excessive load, especially when running translation plugins.
I'm guessing that the best solution would be number 3.
