### ISSUE TITLE
Integrate Singular options into Terms & Taxonomies

### ISSUE THREAD

**Issue by itmustbe** [sybrew/the-seo-framework#110]
The SEO Framework integrates wonderfully with WooCommerce Products.

But for WooCommerce Product Categories, only basic Title and Description fields (and Robots Meta Settings) show up to customize.

I'd love to have the full set of SEO Framework options (General/Visibility/Social) for WooCommerce Product Categories. I really like using Product Categories as links to share on social media.

Alternatively, I'd love it if the Product Category Thumbnail (set for WooCommerce) could be used for the og:image tag (instead of that tag being blank).

Thank you for a wonderful plugin, it is greatly appreciated :)

**Comment by sybrew** [comment]
Hi @itmustbe,

That's a big request!

1. First, let's add the options from Singular items as-is to the Terms settings.
2. From there, we can implement WooCommerce specifics for fallback generation.

**Comment by itmustbe** [comment]
Yes I do apologize for not framing my issue in the form of a pull request!  I wish I had skills to do so (if all it took was advanced CSS knowledge I'd be good).  I looked on your website for a place to donate to your project but I don't see one?  I'd be happy to pitch in $$ since I can't contribute code :)

**Comment by sybrew** [comment]
Opening an issue was the right thing to do! I meant "big" as in that it requires a lot of work to get done.
The donation button is placed on almost all pages (in the sidebar), aside from the homepage 😄. Cheers :)

**Comment by itmustbe** [comment]
Found it and donated!  I think it'd be nice if the Donate button was easily found on your Home page and also on your main Readme on Github... I expected it in one of those two places :)

**Comment by sybrew** [comment]
Thank you so much! And I agree, the readme.md file does leave a lot to be desired. I've taken your suggestion and added a link in the footer of the website too 😄 Cheers!
