### ISSUE TITLE
Exclude pages/posts/slugs from interacting

### ISSUE THREAD

**Issue by sybrew** [sybrew/the-seo-framework#112]
From [MassimoD's request](https://wordpress.org/support/topic/canonicals-2):

Include a way to exclude pages, posts, post types or even URL slugs from interacting with TSF.

To check against this, it adds unnecessary load time for almost all sites, so it will be an extension.

**Comment by eurobank** [comment]
Is this still on your to-list ?

**Comment by sybrew** [comment]
Hi, @eurobank,

As long as an issue is open, it's to-do. 
That's how it generally works at GitHub. 😄

**Comment by whatevaman** [comment]
give it a go, we could use it :)

**Comment by sybrew** [comment]
It's coming to the core plugin, instead of an extension. It affects too many layers for an extension to reach.

We're opting for post type exclusions, as they're most prominent to be disastrously implemented.
