### ISSUE TITLE
Webmaster verification help box

### ISSUE THREAD

**Issue by LeBaux** [sybrew/the-seo-framework#113]
I assume webmaster verification through SEO plugin (TSF or others) is not proffered method, however the help webmaster metabox could be extended to be more noob-friendly.

Considering the fact that Google Search Console is the most wanted verification, we can save a click by adding `&tid=alternate` to [URL template](https://github.com/sybrew/the-seo-framework/blob/master/inc/views/metaboxes/webmaster-metabox.php#L14) since we need to use HTML tag method.

Afterwards it might be helpful to extend the help message to: _Click here to get Google Webmaster Verification Code. Select HTML tag and copy the code from "content"._ Maybe this is way too cosmetic and you can postpone it indefinitively and the verification with other search engines could be revisited later on if it actually rises tangible problems.

**Comment by sybrew** [comment]
If I understand this correctly:
1. The URL should have an extra query argument to direct you to the correct template.
2. The entered content may be the complete meta-tag and then should be stripped on or after input.
3. More information is required for users that have never heard of Webmaster Tools.

I believe the placeholder was sufficient, but at least 1 and 2 might be feasible (either through JavaScript and/or POST).

**Comment by sybrew** [comment]
Number 1. has been introduced in 03c6eedd714f9f4d6e84d6d224e37174b53ad6bd for v3.1.0

**Comment by sybrew** [comment]
This issue has already been completed and refined over time.
