### ISSUE TITLE
Admin example sitemap.xml link doesn't add ports

### ISSUE THREAD

**Issue by strarsis** [sybrew/the-seo-framework#114]
In admin page, the sitemap.xml link ("The sitemap is here...") doesn't add the port to the URL, 
e.g. :8080, which is often used in development and the URL won't work then.

**Comment by sybrew** [comment]
Will check other links too. Thanks! 😄

**Comment by strarsis** [comment]
Addendum: The ports are also missing in sitemap.xml generated links.

**Comment by sybrew** [comment]
Hi @strarsis 

Could you test the patch, I believe all links should be correct 😄. Please also consider testing next/prev links on paginated pages. 

Direct download:
https://github.com/sybrew/the-seo-framework/archive/e4130a40bfbba1892bf3cf4e0fdf9e3eaa7d87c8.zip

Note that the plugin's normally stored at /wp-plugins/autodescription/.

Cheers!

**Comment by strarsis** [comment]
@sybrew: Just replaced the stable plugin with this patched one and now it works!

----

Btw. I just noticed that the plugin name on WordPress plugins directory is 
"autodescription" which was a bit confusing.
