### ISSUE TITLE
NoIndex for Product Attributes

### ISSUE THREAD

**Issue by Yorkki** [sybrew/the-seo-framework#118]
Hello!

I really hope this is the right place to ask this, but would it be possible at all to make product attributes NoIndex from SEO Settings? (maybe even NoFollow too)

I have zillion product attributes and G just found them and now they indexing (and I don't want that), and way too many to go through manually. Not sure if it was the new WooCommerce update (the big one) that did this, but I hadn't noticed this before.

Anyways, appreciate your hard work, the best SEO plugin by far in my opinion. Hope this suggestion / question wasn't too dumb :-)

Cheers,

- Yorkki

**Comment by sybrew** [comment]
Hi @Yorkki,

Only if the attributes are publicly accessible (i.e. showing on the front-end), then you'll be able to select whether or not they can be indexed through the SEO meta options.

Provided, they don't have a global option to disable indexing or following, like other WordPress default archives do.
Such options are planned... alas I can't find the related issue right now; so I'm leaving this issue open until I do (might I even need to create it) 😄

**Comment by Yorkki** [comment]
Hi sybrew, thanks for the reply!

Yes, I have attributes publicly accessible. I'm showing lots of attributes like Publisher, EAN Code etc etc. Those are now links (like taxonomy / categories) and G is indexing them. Wish I could disable indexing through TSF :-)

Cheers!

**Comment by sybrew** [comment]
Hi @Yorkki 

You can configure that already, if I'm not mistaken. See the images below:
![image](https://cloud.githubusercontent.com/assets/7662236/25554525/d7b75a7c-2ccf-11e7-8abf-b38b99f8d662.png)

![image](https://cloud.githubusercontent.com/assets/7662236/25554533/ecffaf10-2ccf-11e7-8cb9-0cfdac25c32f.png)

![image](https://cloud.githubusercontent.com/assets/7662236/25554539/08ec4652-2cd0-11e7-8ce6-b20a1b461d93.png)

![image](https://cloud.githubusercontent.com/assets/7662236/25554542/1cbf1dbc-2cd0-11e7-8f06-30f8f1e26dcd.png)

**Comment by Yorkki** [comment]
Yes, indeed you can do that, but I have tens of thousands of em ..so it's a no go :-)

**Comment by sybrew** [comment]
Hi @Yorkki 

Well, you can always use a filter in the meantime 😄. This one should work for you: 
```
add_filter( 'the_seo_framework_robots_meta_array', 'my_robots_adjustments', 10, 1 );
function my_robots_adjustments( $robots = array() ) {

	if ( ! function_exists( 'taxonomy_is_product_attribute' ) )
		return $robots;

	$qo = get_queried_object();
	$tax = ! empty( $qo->taxonomy ) ? $qo->taxonomy : false;

	if ( ! $tax )
		return $robots;

	if ( taxonomy_is_product_attribute( $tax ) ) {
		// Keys match the value. Legacy code.
		$robots['noindex'] = 'noindex';
	}

	return $robots;
}
```

**Comment by Yorkki** [comment]
Hi sebrew, sorry was away a bit,..

this is great thanks, will test it today! :-)

**Comment by Yorkki** [comment]
Actually, couldn't wait, had to test it right away :-) ... and it seems to work as intended,... awesome! Thanks again!

**Comment by sybrew** [comment]
Found the "adding options for special pages" discussion:
https://github.com/sybrew/the-seo-framework/issues/20#issuecomment-252874509

Cheers! 😄

**Comment by newyorkwebdesign** [comment]
Hi @sybrew,
I have the same issue with duplicate descriptions for both woocommerce product attributes and product-tag/s. After adding your filter/function to my child theme's functions.php file, there is no "robots" tag in the source at all, i.e. [https://www.karaymetals.com/outside-diameter/0-438]. I'm using Yoast SEO. Maybe that is the issue? Thanks
