### ISSUE TITLE
Redirect from attachment page back to attached page

### ISSUE THREAD

**Issue by strarsis** [sybrew/the-seo-framework#119]
I am not able to find this option (is this already implemented) which redirects a visitor of attachment page back to the page the media file has been attached to, see [Yoast equivalent](https://kb.yoast.com/kb/redirect-image-attachment-urls/).

**Comment by LeBaux** [comment]
Hello @strarsis, this topic was [discussed in detail here](https://github.com/sybrew/the-seo-framework/issues/82). Hope it helps!

**Comment by sybrew** [comment]
Thanks @LeBaux!

What most want to achieve with this, Articles is the correct solution.
Nevertheless, it's still planned 😄

Please continue the discussion on #82. 

Have an awesome weekend.
