### ISSUE TITLE
Option to remove title additions at in-post meta box

### ISSUE THREAD

**Issue by sybrew** [sybrew/the-seo-framework#120]
Instead of leaving the blog name and separator out of everything &mdash; including non-editable pages, like Search &mdash; it would be much better to remove the additions if the manual title is used.

This should be optional, and can be done in several ways:
1. Add global title option for this.
2. Add per-page title option for this.

The latter is takes much more time to integrate flawlessly (see #71). 
So, the former will be done first.

**Comment by phrench** [comment]
Great news and many thanks for listening to the community in regards to this issue!

Any ETA for this?

**Comment by sybrew** [comment]
@phrench its milestone is 3.1.0 😄 If everything's going well, I hope to have it released in 3 months.

**Comment by sybrew** [comment]
From https://github.com/sybrew/the-seo-framework/issues/178#issue-249472001

Adding separated per-page options for Social and Non-Social is also great.

X-post #64 (we won't be merging the issues... so, bear with me on this one)

**Comment by phrench** [comment]
I see you mentioned it will be included in version 3.1. Looking forward to it, I've been waiting for this for more than a year :-)

Any ETA for the 3.1 release?

**Comment by sybrew** [comment]
Hi @phrench 

The schedule didn't go as planned because Local SEO required about six new frameworks which took 5 months to build.
For now, I can't give an estimate for 3.1 as I still need to sort the features out, and I'm working on the intricated Focus extension. But, once I get started the ETA should be more clear. 

The main focus for 3.1 will be Gutenberg and titles; so this will be included, certainly.

**Comment by sybrew** [comment]
Here's what I have in mind:

![image](https://user-images.githubusercontent.com/7662236/43163222-c886881c-8f8d-11e8-8517-76bb4d67a495.png)

I hope I don't have to explain it.

I'm still looking into on how it should we should bring the blog name back. **Feedback is welcome!**

---------------------

A checkbox will be the easiest solution. However:
1. It's ugly.
2. I don't want users to be able to remove the blog name from autogenerated titles.
3. Only showing it when a custom title is available is ugly again.

I've looked at how other plugins do it, and none of them are to my liking, nor what allows good SEO.

**Comment by phrench** [comment]
Looks good! Maybe a simple text link saying "Add website title to meta title"?

Or why not include a pre-checked checkbox saying "Include website title" and only remove the blog name when it gets unchecked? Regarding the paternalism of the users, you could simply add a "Warning" or "Not recommended" message with a link to a more detailed explanation if you wish so.

**Comment by sybrew** [comment]
Thanks for your feedback, it's much appreciated 😄 

With that, I tried adding checkboxes again, and while trying to make it "beautiful" (maintain the style), and to prepare it for added complexity, it'll look something like in the images below.

Notice how it gets cluttered real fast, for something that should be simple.

(Small screen)
![image](https://user-images.githubusercontent.com/7662236/43171122-ffc2c578-8fa8-11e8-91dd-8011038542e0.png)

(Larger screen)
![image](https://user-images.githubusercontent.com/7662236/43171146-24c7e04c-8fa9-11e8-92d4-018fd4eee27e.png)

--------------

You're correct on adding warnings. The setting should only be used for when you wish to brand your title differently, not for the sake of debranding your titles to make them "stand out" or be "beautiful".
The link to this warning is already present via the `[?]` item.

**Comment by sybrew** [comment]
Regarding the warnings, we could incorporate it via an advanced "drawer".
After opening the drawer, the user can toggle various elements.

This drawer will only be shown when the user enables the advanced options, set via the general settings.
This setting can be applied to many things in the future, too.

Drawers can be seen in the Monitor and Local extensions, and they look like this in Monitor:

![image](https://user-images.githubusercontent.com/7662236/43172756-2e583b9a-8fb1-11e8-8bf7-855861c857fc.png)

The drawers don't require JS. This will be redundant when the JS-powered Gutenberg arrives... for which I still need to write an interface.

**Comment by phrench** [comment]
Thanks for implementing this change, it's also much appreciated :-)

I would recommend to remove the div containing "Site name", it's not necessary IMHO. Without, it would look not cluttered at all.

Regarding the warning, I wouldn't over-complicate things. I know you're an advocate of including the site title in the meta title, but I'm not. Including the site title is ok for default blog posts and novice users. But every important, high-traffic page of mine has the site title removed in order to optimize the meta title for higher CTR and more keyword variations. What I'm saying: You're plugin is a tool and if the default setting is safe for novice users it should be good enough.
