### ISSUE TITLE
Typo in string

### ISSUE THREAD

**Issue by barnez** [sybrew/the-seo-framework#123]
There is a typo in [this string](https://translate.wordpress.org/projects/wp-plugins/autodescription/stable-readme/en-gb/default?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=4456350&filters%5Btranslation_id%5D=49025373).

It currently reads:  
Do fill in the and Social Meta "General", "Facebook" and "Twitter" settings.

It should either read:
Do fill in the Social Meta "General", "Facebook" and "Twitter" settings.

Or:
Do fill in the ________ and the Social Meta "General", "Facebook" and "Twitter" settings.

**Comment by sybrew** [comment]
Thank you so much @barnez, I'll fix it right away 😄 

It's shown [here](https://wordpress.org/plugins/autodescription/#installation) and it's meant to be a step-by-step checklist, so it's separated from the rest to make it seem less cumbersome yet more achieving work... it takes less than 1 minute if you come prepared 😉.
