### ISSUE TITLE
[Question] Excluding categories from sitemap

### ISSUE THREAD

**Issue by OwenMelbz** [sybrew/the-seo-framework#127]
Hi, sorry if theres a better place to ask questions like this, but I couldn't see anywhere?

But is there a way to exclude specific post categories from showing in the sitemap?

Our scenario is we're importing tweets from twitter which the client doesn't want to show in the sitemap as they dont have detail pages.

Many thanks

**Comment by sybrew** [comment]
Hi @OwenMelbz 

You're looking for this filter: `the_seo_framework_sitemap_posts_query_args`

[The code](https://github.com/sybrew/the-seo-framework/blob/cc53540c746dee460492858815a4daea124476cc/inc/classes/sitemaps.class.php#L770-L793).

You'd have to add `category__not_in`:
https://codex.wordpress.org/Class_Reference/WP_Query#Category_Parameters

```
add_filter( 'the_seo_framework_sitemap_posts_query_args', function( $args, $defaults ) {
	return array(
		'category__not_in' => array( 2, 6 ),
	);
}
```

Let me know if it works 😄 Cheers!
