### ISSUE TITLE
AI keyword (subject) analysis

### ISSUE THREAD

**Issue by sybrew** [sybrew/the-seo-framework#128]
Related: #108 

Currently, focus keyword analysis is [fundamentally flawed as a concept](https://wordpress.org/support/topic/hi-from-a-newbie/#post-7110667).

>You need a focus subject, not a focus keyword. 
>
> [...]
>
> It’s all about basic paper writing: You have a title, an intro (focusing on the title), the subject (explaining the intro, leading to the conclusion) and then the conclusion (referring back to the intro and title). All should contain the focus keyword without thinking about it.
> 
> The issue is that the named system doesn’t work anymore since synonyms are considered:
> `architects, architect, architectural, architecture, architect office, architectural firm`

We need to improve that. So, let me introduce you to "the system"...

## The system

Let's call the parser "the system". This is still an abstract flow put into words:

#### To counter that flaw, and to slightly give way to a subject, you:
1. Enter a keyword.
2. Enter synonyms for the keywords (teach the system).
3. Repeat 1. and 2. until you've covered your subject.

#### Alternatively, give (a) common sentence(s) to be filled in:
1. ["subject"] is about ["this"], ["that"], and ["such"].
 a) Example: ["Ferarri"] is about ["cars"], ["performance"], and ["style"].
2. Each word filled in allows for synonyms.
  a) Ferrari -> "" (brands often don't have synonyms) 
  b) Cars -> "automobiles", "vehicles", "motors"
  c) Performance -> "speed", "mph"
  d) Style -> "beautiful", "glamour"

#### The system analyzes
1. The system gives you hints whether the subject has been parsed within the content.
2. Repeat 1. on any change. With slightly buffered intervals (buffer gets exponentially larger as the content does).

#### The system tests
1. After a while, the system can (i.e. Monitor?) test whether the page is ranking for the subject.
2. The system will give you results.

#### Alternatively, use Google Search Console API
1. The system fetches data through [Google Search Console - Search Analytics](https://www.google.com/webmasters/tools/search-analytics).
2. The system checks for the subject on whether it has ranked based on position.

#### The system feeds back
1. After enough subjects have been covered, Google's Search Console should give you a good list of matching queries.
2. Those queries can be ranked by CTR, and then fed back to the system to suggest new subjects.
3. Then you can perform "Step 1" with more confidence.

**Comment by sybrew** [comment]
This will be the first extension to have unverified (but restricted) API access.
Premium users will receive unrestricted API access.

**Comment by RicaNeaga** [comment]
Please take a look how these guys make this happen (subject / synonyms analysis) - https://cognitiveseo.com/

Hope it helps :)

**Comment by sybrew** [comment]
Hi @RicaNeaga,

I'm not sure which part you're referring to. Could you elaborate?

From what I've seen, they scan Google's SERP to see how well your keywords are doing. 
This is a resource-intensive task because we'd have to store thousands of Google result pages automatically. This is something Google doesn't want us to do.
You'll be faced with a Turing test even when you do this manually.

As you can tell by their pricing, it's not cheap (20x our price). It's also quite out of the scope of what we offer.

Not all hope is lost, however. We'll see how both we (TSF company) and Google evolves over time.

**Comment by RicaNeaga** [comment]
The link above was given to me by the same well-known SEO expert from my country, he said that for subject / synonyms analysis, the tool I linked above works just great.

So maybe at a latter stage, when you're just about to finish your product and want to test it, see how it works vs. that tool, to see if the results are ~ the same / maybe if your product needs improvement.

I'm not a SEO expert, only a wordpress enthusiast, so I couldn't give you a better advice, the best thing I could do is get some feedback from an experienced SEO specialist :)

**Comment by sybrew** [comment]
I totally missed my own Step 3 part... heh. This is what you were referring to :)

Yes, so with that we could indeed evaluate how it all intertwines and compare results if necessary.

I'll most likely use Google's API, which is probably the most accurate thing out there:
- Docs: https://developers.google.com/apis-explorer/#p/webmasters/v3/ 
- Type: `webmasters.searchanalytics.query`

**Comment by sybrew** [comment]
The extension name will be: **Focus**

The very early developer draft can be found in the links below, which are subject to change:
\> [Focus extension trunk](https://github.com/sybrew/The-SEO-Framework-Extension-Manager/tree/master/extensions/free/focus/trunk)
\> [Scoring draft](https://github.com/sybrew/The-SEO-Framework-Extension-Manager/blob/a9a5cfdd2e81ed270a89adb62c75184fe058dd0e/extensions/free/focus/trunk/views/inpost/score-template.php#L23-L193)

The barely-styled visual (placeholders) we currently have:

![image](https://user-images.githubusercontent.com/7662236/35839983-b41d9470-0af3-11e8-9f14-b5faa933b35f.png)

The subject will automatically be filled in through our API services.
When the subject is selected, you can edit the attached synonyms.

The scoring is done based on keyword and subject (synonyms) analysis.

----------------

We're far from the "what we truly want" product. So expect many improvements over time after the initial release.
***Step 1 and 2*** will be provided (as an abstract thereof) with version 1.0. 

**v1.0 ETA is spring 2018.**

*The beta announcement will follow.*
