### ISSUE TITLE
Handle Imagick/GD dependency

### ISSUE THREAD

**Issue by BoxMediaUK** [sybrew/the-seo-framework#133]
Whenever I activate the plugin some of my posts just show corrupt data. An example below. It happens on a number of my sites, not all posts but the majority..

Any ideas?

`JFIF��;CREATOR: gd-jpeg v1.0 (using IJG JPEG v62), quality = 82 ��C    !'"#%%%),($+!$%$��C   $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$��L�"�� ���}!1AQa"q2���#B��R��$3br� %&'()*456789:CDEFGHIJSTUVWXYZcdefghijstuvwxyz��������������������������������������������������������������������������� ���w!1AQaq"2�B���� #3R�br� $4�%�&'()*56789:CDEFGHIJSTUVWXYZcdefghijstuvwxyz�������������������������������������������������������������������������� ?�~��()i(��������� J(������(����(��ZJ(��(��(����(��(��(��ZJ(����ZJ(����)i(����Z)(��(����Z)(����Z)(����Z)(����Z)(����Z)(����Z)(����Z)(����Z)(����Z)(����Z)(����Z)(����Z)(����Z)(��)h���)i)h���Z(������ J(���J)i)h���ZJZJZ)(�������JZJ(���J)i)h���Z(������ J(���JZ))h)i(������)h���)i)h���Z(������ J(���J)i)h���ZJZJZ)(�������JZJ(���J)i)h���Z(�� (���ZJ)h���)h(��Z(�������ZJZJ)h)i(��ZJZJ)h(��ZJZ()i)h(��� JZ()i)h(��� (���Z(���������ZJZJZ()h���Z((����Z((��� JZ((��� JZ()h���Z(������((��� JZ((����Z((�����((�����((��� JZ()h���Z(������((�����()h���Z(��((��� JZ()h���Z(������((��� JZ((��� JZ(������(������((��� JZ()h���Z(������((�����()h���Z(��((��� JZ()h���Z(������((��� JZ((��� JZ(������(���� JZ(��JZ(������ )(���(���� )(����Z)(����Z)(����� (�� (�� (�� (�� (�� (�� (�� (�� (�� (�� (�� (�� (�� (�� (�� (�� (�� (�� (�� (�� (�� (�� (�� (�� (�� (�� (�� (�� (�� (�� (�� (�� (�� (�� (�� (�� (�� (�� (�� (�� (�� (�� (�� (�� (�� (�� (�� (�� (�� (�� (�� (�� (�� (�� (�� (�� (�� (�� (�� (�� (�� (�� (�� (�� (�� (�� (�� (�� (�� (�� (�� (�� (�� (�� (�� (�� (�� (�� (�� (�� (�� (�� (�� (�� (�� (�� (�"� ) !>� ��)����}(��L�}(�@�>�nh�q�Sis@Ţ��Z(��(����(��JZ(����)(h����)(h��(����)(h��(��(����nG���EE��7Ӱ�Qo�"�����6)w���n� �:�JBH�@��4P�E%-Q@��QEQEQEQEQEQEQEQEQEQEQIK@RP�EQEQIE-��QIE-RP�IK@��QE%-Q@��QE%-��QIE-RP�IE-RP�IK@�P�E%-Q@��QE%-Q@�P�E%-��QIE-��QIE-RP�IK@��QE%-Q@��QE%-��QIE-RP�IE-RP�IK@�P�E%-Q@%-QEQEQE&h ��&��P+����&���l~�Mf��i9���?u&�L�)7���wTa��I��޴���������E�P�.sJ*0�R��\���)s@\Z))hQEQEQEQEQEQERR�@Q@��f�i���@�S]�$c�!<��+��)�N�cL$�HW$/�B��j-�֍��Wa6K�{�<ʇp�<�`&ߚ3L�Q`I��RQ`6:Ӂ�2�qJ�?4���7PZ���Z��@)��4;���Ta�WԵk ��u�m-�����Q��۰�\�-V��-u+X���"���e%��)Z�E!`

**Comment by sybrew** [comment]
Hi @BoxMediaUK,

It seems like any of the WordPress default image processing libraries is missing in your PHP installation,
 be it either [GD](http://php.net/manual/en/book.image.php) or [Imagick](http://php.net/manual/en/book.imagick.php).
Alternatively, it might be that GZIP is running twice and there might be an incompatibility with a caching plugin.

Nevertheless, would adding this filter to your theme's functions.php file fix it? 
Note that this trick won't work on WooCommerce.
```
add_filter( 'the_seo_framework_og_image_args', function( $defaults = array(), $args = array() ) {
	$defaults['disallowed'] = array( 'featured' ); 

	return $defaults;
}, 10, 2 );
```

**Comment by BoxMediaUK** [comment]
Does SEO Framework rely on these libraries? I am bit perplexed why its just this plugin that causes the issue..

I will give the script a try..

**Comment by sybrew** [comment]
Technically, WordPress does. TSF relies on [WordPress' exception handling at that point](https://github.com/sybrew/the-seo-framework/blob/ff5e97ba5a319bb43ef613d9e9b33be92f9a4a7c/inc/classes/generate-image.class.php#L473-L482
).

I see JPEG and 82 in the encoded output you've posted. However, WordPress Core also uses those values 😕.

If you manage your own server environment, then the following list should help you greatly 😄 

Your web server (Apache/Nginx) requires support for:
- Headers
- Expires
- Proxy
- SSL
- UID
- Version
- Deflate (gzip)

To completely support WordPress, your PHP installation requires support for at least:
- cli
- curl
- ftp
- gd (if GD is unavailable, use imagick)
- mbstring (must have for performance)
- mcrypt (WooCommerce)
- mysql
- opcache (nobrainer for performance, you will regret not having this)
- pdo (feed caching)
- soap (WooCommerce, PayPal)
- sockets (faster file writing)
- xml
- zip
- FPM (or DSO + RUID2... suPHP will disable opcache)

**Comment by BoxMediaUK** [comment]
Wordpress runs absolutely fine with several of my sites and never encountered this error before until installing this plugin. I am migrating from Yoast so really interested in using yours but can't if it does this to my sites..

**Comment by BoxMediaUK** [comment]
I'm not sure how the sockets module would speed up file writing, I presumed that only related to TCP sockets but I'm interested to know the logic here for my own code.

Here is the list of modules running

[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dom
exif
filter
ftp
gd
gettext
gmp
hash
iconv
imagick
imap
json
libxml
mbstring
mcrypt
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
SPL
sqlite3
standard
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zlib

[Zend Modules]
Zend OPcache

**Comment by sybrew** [comment]
Sockets is used [here](https://github.com/WordPress/WordPress/blob/dd6da701b286579819cd6aa518aa2d7018efd759/wp-admin/includes/class-ftp.php#L899-L912), where it would otherwise fall back to class `ftp_pure`. It saves a roundtrip when reading and writing files whilst using FTP, it's not a big issue as it's admin related only.

But I digress, could you help me debug this 😄?

Did [my filter](https://github.com/sybrew/the-seo-framework/issues/133#issuecomment-303244274) do anything?
Also, are you using caching plugins and if so, which one and does disabling of the caching plugin help?

**Comment by BoxMediaUK** [comment]
I enabled imagick and it seemed to have done the trick. I'm not sure why but I will keep an eye on it over the coming days as the traffic increases..

We use Litespeed cache on a Litespeed server..

**Comment by sybrew** [comment]
Awesome! Thanks for notifying 😄 

It seems that the absence of the "required" libraries isn't handled too well by WP Core then. I'll see if I can mitigate the issue in the next update.

**Comment by sybrew** [comment]
Hi @BoxMediaUK 

Could you elaborate on how you've enabled Imagick? Through php.ini?

I've just tested out this bug, and WordPress simply returns a WP_Error instance, which was already correctly handled... So I don't know where to look now 😅 

```
object(WP_Error)#566 (2) {
  ["errors"]=>
  array(1) {
    ["image_no_editor"]=>
    array(1) {
      [0]=>
      string(28) "No editor could be selected."
    }
  }
  ["error_data"]=>
  array(0) {
  }
}
```

**Comment by sybrew** [comment]
Closing this issue. When the bug comes back or persists, feel free to add comments and I'll reopen it.

It also seems to be more of a WordPress Core issue than a TSF issue.
