### ISSUE TITLE
Breadcrumb Primary Category

### ISSUE THREAD

**Issue by samunderwood** [sybrew/the-seo-framework#135]
Are there any plans to be able to select your primary category for posts that fit within multiple categories? Currently, the breadcrumb JSON-LD output is not always accurate as it doesn't show the right category.

You can see Yoast made a solution for this in these release notes - https://yoast.com/yoast-seo-3-1/

**Comment by sybrew** [comment]
Hi @samunderwood 

There is! See https://github.com/sybrew/the-seo-framework/issues/32 and feel free to contribute your thoughts there.

Cheers!
