### ISSUE TITLE
the_seo_framework_add_blogname_to_title filter should apply to inpost metaboxes

### ISSUE THREAD

**Issue by kevinlisota** [sybrew/the-seo-framework#136]
I am using the filter `the_seo_framework_add_blogname_to_title` to disable adding the blogname to pages (We do use the blogname on posts, however.) We do this because many of our page titles already include the sitename, and the duplication looks weird in search results.

My function checks `is_page()` and returns false when that conditional is true. This works as expected in the `<title>` output.

However, if you go to the page edit screen, the Custom Page Title in the SEO metabox still fills in the blogname as a placeholder, which is not correct when this has been disabled and does not accurately reflect what the plugin is going to output in HTML.

Is there a way to filter this? I'm not finding any obvious solutions.

My request is that when `the_seo_framework_add_blogname_to_title` has conditionally been disabled, that change should propagate to the SEO meta box on edit pages so that it reflects what the plugin will ultimately output.

**Comment by sybrew** [comment]
Hi @kevinlisota 

Because of the complexity in differences between how the query is handled on the front-end in respect to the back-end, I've created the [query class](https://github.com/sybrew/the-seo-framework/blob/master/inc/classes/query.class.php).

In there, you'll find method `is_page()`, which will mitigate to `is_page_admin()` in the administrative screens. I hope that works for you 😄.

In the future, the "add blogname to title" option will be added to the in-post meta box; for that, see https://github.com/sybrew/the-seo-framework/issues/120.

**Comment by sybrew** [comment]
Hi @kevinlisota 

Have you been able to resolve this yet, or did you run into anything specific?

Cheers!

**Comment by kevinlisota** [comment]
I have tried the following, based on your query class, but it doesn't work correctly. It works fine on the front end, but in admin, it removes the title from `post` and some other CPTs that aren't specified below.

I haven't debugged yet, but it is either your `is_page` function or `is_singular` function that is being too aggressive.

The reason we need this is that certain CPT have our blogname embedded in the title already, we don't want it repeated, which looks weird and isn't necessary for SEO. Regular posts do not.

```
	 public function remove_sitename_title( $add ) {
		 if ( is_post_type_archive( ['devblog', 'event', 'picks', 'special_coverage'] ) ) {
			 $add = false;
		 } elseif ( function_exists( 'the_seo_framework' ) ) {
			 $the_seo_framework = the_seo_framework();
			 if ( is_object( $the_seo_framework ) ) {
				 if ( $the_seo_framework->is_page() || $the_seo_framework->is_singular( ['event', 'listing'] ) ) {
					 $add = false;
				}
			 }
		 }
		 return $add;
	 }
add_filter('the_seo_framework_add_blogname_to_title', 'remove_sitename_title');
```

**Comment by sybrew** [comment]
Yes, that has already been commented on, right here: https://github.com/sybrew/the-seo-framework/issues/71#issuecomment-288400855.
It's a JavaScript issue you're facing, not PHP. Those have a low priority as they don't affect what crawlers encounter.

For the removal of the blog name, see https://github.com/sybrew/the-seo-framework/issues/120
With that, I'll implement a JavaScript fix too, and the filter will be combined with the option.
