### ISSUE TITLE
Confusing verbiage in settings

### ISSUE THREAD

**Issue by chuckreynolds** [sybrew/the-seo-framework#14]
SEO > Social Media Settings > Post Dates > Home Page 

The part I think may be wrong, or I'm misunderstanding how that works is the "by `disabling` the"... Should it not be "by `enabling` the following options"?

![screen shot 2016-07-07 at 17 52 50](https://cloud.githubusercontent.com/assets/46185/16674329/d7c74ccc-446b-11e6-8359-4cefd815af02.png)

Also where do you take that time from? the time that page was last updated/published or based on recent posts published dates? Just wondering as I'm starting to look into migrating some clients to this plugin.

Cheers

**Comment by sybrew** [comment]
Hi Chuck,

The text is correct, I'll try to explain:
The description is reflecting on it being negative (unchecked). When you enable/check the options, the modified/published time will be output, which can be a bad indication to crawlers as it's almost never updated. The home page is very static, and sometimes it's best to let Search Engines determine its age through dynamic content.

The time is taken from the WordPress Post object attached to the Home Page. Within that object the publishing time and last modified time are obtainable.

In the future I'll add an `is_home()` indicator, which can then determine the latest visible post publishing time within that loop. That will probably be an extension on its own which explains it all, as it's a dynamic (and thus confusing) option.

I hope this clears things up!

**Comment by sybrew** [comment]
Hi Chuck,

If you have any more details to add, or believe the sentence should differ. Please feel free to re-open this issue.

Cheers!

**Comment by chuckreynolds** [comment]
...tbh this is so old i forgot about it. lol. I do want to use this plugin on a few properties but I haven't had the time to implement and migrate. Once I do I'll probably be a thorn in your side when I do find things and have suggestions ;)  Cheers.

**Comment by sybrew** [comment]
Hi Chuck. If you do find anything or have suggestions, feel free to let me know :).
