### ISSUE TITLE
SEO Framework individual post settings on custom post types

### ISSUE THREAD

**Issue by jserrao** [sybrew/the-seo-framework#145]
Is there a hook that allows individual post settings on custom post types? It's that nice box that appears at the bottom of the default `post` of WordPress that I would like to get on the custom post types that I have.

**Comment by sybrew** [comment]
Hi @jserrao 

Yes, there is!

However, I do suggest setting the custom post type arguments to have at least these set:
```
register_post_type( array(
	'public'   => true, // Implies exclude_from_search: false, publicly_queryable: true, show_in_nav_menus: true, and show_ui:true. The built-in types attachment, page, and post are similar to this.
	'rewrite'  => array( 'slug' => 'movie' ),
	'supports' => array( 'title', 'editor' ),
) );
```

Then TSF will work with it automatically, and the output is as expected (front-facing, public, with rewrite rules, query-able and has basic options).

For more information: https://codex.wordpress.org/Function_Reference/register_post_type

**Comment by jserrao** [comment]
My custom post types look fine - how does this plugin display it's metabox settings if the custom post type has a lot of ACF fields on it? I know ACF adds a display override section into their custom field sets - maybe there is a conflict here?

**Comment by sybrew** [comment]
There shouldn't be an issue with ACF:
![image](https://user-images.githubusercontent.com/7662236/26890620-7d3e0b7a-4bb2-11e7-85d7-72a88dd57285.png)

Please check the Screen Options dropdown menu at the top right of your screen. `%s SEO Settings` should be marked there.

**Comment by jserrao** [comment]
Sorry I never responded to this @sybrew but I had to adjust my content types to make this work. 

It seems the `'public' => true;` param of `register_post_type()` is what fixed this.

**Comment by sybrew** [comment]
@schmidthaus 
I have no experience with their plugin, but if you add custom support for `autodescription-meta` to the CPT, it should work.

**Comment by spka** [comment]
Had the same issue today, since i use the excerpt instead of the editor as a description. Adding the _the_seo_framework_custom_post_type_support_ filter and commeting out the editor made it work.

Docs: [https://theseoframework.com/docs/api/filters/](url) - "Since 2.4.1"

**Comment by sybrew** [comment]
Hi @spka,

The filter is no longer needed from TSF 3.0.4, as the editor and title requirements have been removed.
