### ISSUE TITLE
Sitemap to pull items from MS subdirectories

### ISSUE THREAD

**Issue by sybrew** [sybrew/the-seo-framework#147]
When using MultiSite subdirectories, the sitemap should pull items from other blogs.

When doing so, it should check if the subdirectories are mapped to other domains before doing so.
This is an extremely resource intensive job, and we might have to wait for [PHP 5.5 Generator](http://php.net/manual/en/language.generators.overview.php) support.

Yes, WordPress' PHP 5.2 LTS is holding everyone back... 😢 

For our PHP upgrading schedule, visit https://github.com/sybrew/the-seo-framework/issues/98.

**Comment by sybrew** [comment]
### A quick note:
TSF supports MultiSite subdirectory sitemaps. 

But, rather than having everything in the main sitemap, you should submit the subdirectory sitemaps manually through [Google Search Console](https://www.google.com/webmasters/tools/sitemap-list) and [Bing Webmaster Tools](https://www.bing.com/webmaster/configure/sitemaps/home) (Configure My Site -> Sitemaps).

Note that Bing randomly picks up non-existing sitemaps, for a weird reason... which might have been a bug caused by pinging a plausibly wrong URL prior to 2.9.2; although, this is yet to be confirmed.

**Comment by kevinlisota** [comment]
We run multisite with subdirectories, and I would be very careful with introducing this, or not do it at all, and submit multiple sitemaps.. Wordpress multisites largely behave as independent WordPress installs.

I suppose you can call into sub-sites posts tables and build sitemaps. However, what about a sub-site that has filters set. Like a filter to exclude or include certain CPTs. Or excluding certain post IDs from the sitemap.

Those are very common use cases (we do both.) Your sitemap has these available via filters. If you were to enable the main site to pull entries from subsites, where do these filters go? add_filter isn't going to span multiple sites.

I think the correct thing is to submit a sitemap per multisite install.

**Comment by sybrew** [comment]
When using subdirectories, you imply that you use it for structural reasons.
 
For example, the main site doesn't have WooCommerce, but the subsite (e.g. "/shop/") has WooCommerce.
We can't expect everyone following this standard, but when using subdirectories for any other reason is like using a mouse as a keyboard: It can work, but it isn't efficient or even meant to be.

For ease of use, this topic's feature would then be great.
Of course, this feature should be opt-in; so, an option should be displayed.

There are multiple ways to handle this, like through network settings (see #126).
Filters should also work. Especially since you have access to `$GLOBALS['blog_id']`, which we can pass as a parameter within a filter.

The actual runtime code should sustain a single database connection, through which it then loops the enumerated sites.

**Comment by sybrew** [comment]
Moving this to an extension for two reasons:
1. TSFEM can use generators.
2. This is an advanced feature that should stand on its own.

**TODO:** Implement a filter that overrides the sitemap content/links in The SEO Framework.

We should implement an options screen which allows the user to select included sites.
The "checkbox" site list should only consist of sites that the user controls (or has already been selected by other users), and thereof only ones that have the same domain name.

**Comment by colomet** [comment]
is there any expected date (aprox) for that extension? weeks, months?

thanks

**Comment by sybrew** [comment]
Hi @colomet,

This feature isn't on the roadmap yet, and it might be years before implemented.
I expect less than 0.1% of the users to benefit from this. Multisite setups generally require more technical knowledge and server access, and almost no site inherently needs it.

I'm now working on improving the API for better plugin stability when used, which should make planned extensions like this work seamlessly.

I've openly invited other developers to create extensions, which is why you see the author name next to each extension in the dashboard. They're free to make this one or any other for that matter.

**Comment by colomet** [comment]
> Submitting multiple sitemaps to search engines via their webmaster tools works just as well as creating an index thereof (or merging it completely) for a multisite.

So, google will find the sitemaps sone or later and it will work in the same way?

thanks

**Comment by sybrew** [comment]
https://github.com/sybrew/the-seo-framework/issues/147#issuecomment-306024087 still holds.

I see no need for implementing this. Third-party solutions are possible via the new sitemap generator brought in TSF v4.0.
