### ISSUE TITLE
og:description is using first paragraph of text

### ISSUE THREAD

**Issue by hoverboardreviews** [sybrew/the-seo-framework#15]
I have an issue where the og:description is ignoring the manually written description and excerpts and is instead using the first paragraph of text.  The twitter:description pulls the correct info though.  Any suggestions on how to fix this?

**Comment by sybrew** [comment]
Hi hoverboardreviews,

Thanks for opening this issue! I need a little more information, which could indicate where the issue lies:

1. Are you facing this issues on only one page, or multiple? 
2. Are you using persistent object cache (a caching plugin)? The whole output of The SEO Framework is placed within the object cache, which could hold old data.
3. It could be possible the page/post ID can't be recognized through the WordPress loop, therefore I'd also like to know if we're dealing with Custom Post Types.
4. Do you have a link to the site where you're facing this issue?

Thanks!

**Comment by hoverboardreviews** [comment]
It was on multiple pages, but it seems to have been theme related somehow.
It wasn't a custom post type, but I had tweaked the page to add
categories.  If you're still interested in checking it out, let me know.
Otherwise, I've got an alternate theme that will make this irrelevant.

On Fri, Jul 8, 2016 at 4:16 PM, Sybre Waaijer <notifications@github.com>
wrote:

> Hi hoverboardreviews,
>
> Thanks for opening this issue! I need a little more information, which
> could indicate where the issue lies:
>
>    1. Are you facing this issues on only one page, or multiple?
>    2. Are you using persistent object cache (a caching plugin)? The whole
>    output of The SEO Framework is placed within the object cache, which could
>    hold old data.
>    3. It could be possible the page/post ID can't be recognized through
>    the WordPress loop, therefore I'd also like to know if we're dealing with
>    Custom Post Types.
>    4. Do you have a link to the site where you're facing this issue?
>
> Thanks!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/sybrew/the-seo-framework/issues/15#issuecomment-231474819>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/APoXQGLcXXE-NHpDZ8RGWXSwgKDp2z5Yks5qTr42gaJpZM4JHtOL>
> .
>



-- 
Visit my site:  ScooterEra.com <http://www.scooterera.com/> The Hoverboard
HQ

Follow Me on Your Favorite Social Network


[image: --]

ScooterEra.com - Hoverboard HQ.
[image: https://]about.me/hoverboards
<https://about.me/hoverboards?promo=email_sig&utm_source=email_sig&utm_medium=email_sig&utm_campaign=external_links>


   - http://twitter.com/scooter_era
   - https://www.facebook.com/the.scooter.era
   - https://plus.google.com/+Scooterera
   - http://www.pinterest.com/scooterera

**Comment by sybrew** [comment]
Hi hoverboardreviews,

I'm glad to hear you've worked it out!

Could you name or link to the theme that has caused this issue? Then I can take a look at what might have triggered this error.

Thanks and have a great day!

**Comment by sybrew** [comment]
I'm closing this issue as it seems to be no longer relevant. 
If you face this issue again, feel free to open this issue once more.
