### ISSUE TITLE
Errors with flush rewrite rules when changing settings

### ISSUE THREAD

**Issue by kevinlisota** [sybrew/the-seo-framework#152]
We are getting unusual errors with rewrite rules, where some of the registered rewrite rules are no longer present after changing settings in SEO Framework. It takes a few steps to replicate.

We are seeing this with some plugins, but not others. Specifically, I would install AMP-WP from Automattic, or Liveblog from Automattic to see it happening. We're also seeing it on code we use to disable trackbacks and their associated rewrites.

1) Install AMP plugin
2) Go to Settings > Permalinks and click Save Changes to flush rewrite rules
3) Go to the database and grab the rewrite_rules option from the option table. Deserialize it so you can read it easier.
4) Make a settings change in SEO Framework that enqueues your flush_rewrite_rules function. I was just doing this with some ping settings in the sitemap, though I think there are many other settings changes that would work.
5) Now try to access a page at the /AMP/endpoint. Or better yet, grab a copy of the rewrite_rules row from the options table and deserialize that.
6) Compare the two versions of rewrites. You've lost the AMP endpoints.

We do have a persistent object cache present, though I haven't tested this without a persistent object cache to see if that affects this issue.

I think the issue might be where you are trying to flush the rewrite rules much too late on the shutdown action. `The_SEO_Framework\Load->maybe_flush_rewrite()` runs as the very last script on all of our pages.

If you look at the `flush_rewrite_rules` function, it uses `flush_rules`. You'll notice that `flush_rules` already has a built-in delay to not run before `wp_loaded` hook has completed. This is to ensure that it allows for other plugins to register their rewrites.

Note that wordpress loads the rewrite_rules option from the database right before the `parse_request` hook is fired. I'm guessing you need to fire flush_rewrite_rules on `init` or your own plugin's init hook.

On a related note, there seems to be an unused function here. `enqueue_rewrite_flush_other` is defined and is checked in the `maybe_flush_rewrite` function, but never used anywhere else that would actually set it to true. Not sure why it's needed.

**Comment by sybrew** [comment]
Hi @kevinlisota 

I'm unable to confirm this bug. It might just be the theme or another plugin.

`enqueue_rewrite_flush_other()` should've been deprecated with 2.6.3, but I left it in with the future in mind. It was used by a (now removed) method `wpmudev_domainmap_flush_fix()`: https://theseoframework.com/?p=1269

---

### Flushing background info:

Flush rewrite rules *must* be implemented on shutdown.

Just one single mistake, made by one single plugin, and all goes haywire. In fact, it could be any combination of rewriting plugins; just one has to make a mistake. While most work great on their own.

Unfortunately, this easily induces a conformational bias, and I can't blame you. It's WordPress' fault.
They're working on a fix, however: https://core.trac.wordpress.org/ticket/36292

For the past 6 years, this issue has been in discussion, too:
https://core.trac.wordpress.org/ticket/18450
In that ticket, they want to move all flushes to PHP shutdown, just like TSF is doing now.
