### ISSUE TITLE
Add Quick Edit SEO options

### ISSUE THREAD

**Issue by sybrew** [sybrew/the-seo-framework#155]
From [ExpatThai's suggestion](https://premium.wpmudev.org/blog/review-seo-framework-wordpress/#comment-168038):

Add the ability to adjust the SEO options through Quick Edit / Bulk Edit.

Sounds simple enough, but we might want to automate the output of options beforehand.
i.e. through a generator, rather than manual HTML.

**Comment by LeBaux** [comment]
From the quality perspective, I think it is best to edit SEO settings in full blown editor, with the content. But I am pretty sure SEO "power users" would appreciate this a ton. Even I would be tempted to use this, especially after adding TSF to older blog with tons of articles... but I think I would end up doing sloppy work. It is two way street this thing. 👹I think this also might be premium extension territory.

**Comment by sybrew** [comment]
2211aecb3fe6048930dd6079dc1570f86823f58e started adding support for this. However, #345 and #110 were blocking.

**Comment by LeBaux** [comment]
When done, please let me know, so I can pass the info to [LinkiCZ](https://twitter.com/LinkiCZ/status/1142063788201598976). Some link builders are interested in bulk edit functionality. Thank you!
