### ISSUE TITLE
Remove custom page title

### ISSUE THREAD

**Issue by Storbaek** [sybrew/the-seo-framework#158]
I'm a happy user of the SEO framework but stumbled upon one issue.

I would like to use thrive themes headline optimize, which does A/B split test on headlines on the page title. As the custom page title overwrites the normal page title, I have no way to use the plugin.

Is there a way to disable the custom page title introduced by the SEO framework by post type, but keep the custom page description?

**Comment by sybrew** [comment]
Hi @Storbaek 

It's plausible, but not easy. I'll commit a patch that will make it easy in the next version and will explain how it works.

**Comment by sybrew** [comment]
Alright, now it's easy :)

Example:
```
add_action( 'the_seo_framework_init', function() {

	if ( 'my-post-type' === get_post_type() ) {
		add_filter( 'the_seo_framework_overwrite_titles', '__return_false' );
	}
} );
```

**Comment by Storbaek** [comment]
Cool Sybre. I'm not a developer, so could you guide me where to insert the code?

Thanks!

**Comment by sybrew** [comment]
Hi @Storbaek 

I've created a small overview here:
https://theseoframework.com/docs/using-filters/#where

Note that you need to exchange 'my-post-type' with your post type slug. Be sure to create a backup before your text editor or FTP client might destroy the file attain(t)ed.

**Comment by Storbaek** [comment]
Ok, that went smooth to add in the functions.php with your guide! 

How do I know and test that it actually picks from the title and NOT custom title? All the A/B testing would be wasted if the code doesn't work somehow.

Second, your guide mentions adding in a child theme and I don't seem to have one, so I have the code in the parent theme. Any workarounds here?

**Comment by sybrew** [comment]
You can test it by setting a special title separator in the SEO Settings. If that separator doesn't get output, then the filter works.
Alternatively, set a custom SEO title. If that one doesn't get output, then it also works.

Note that the filter doesn't affect Open Graph and Twitter titles. So your testing should be discreet.

For the second part, the workaround is exactly as what you've done 😄

**Comment by Storbaek** [comment]
Brilliant. Keeo up the good work!
