### ISSUE TITLE
Adding custom Schema.org

### ISSUE THREAD

**Issue by wassim** [sybrew/the-seo-framework#165]
Is it safe to **manually** add custom Schema.org (following the official doc) while having TSF enabled? Would the plugin alter with this in any way?

**Comment by LeBaux** [comment]
It is my understanding, there is TSF extension being developed right now precisely for adding relevant schema.org microdata, see https://github.com/sybrew/the-seo-framework/issues/142. It will be a premium extension however, but you can still snag [early bird license](https://premium.theseoframework.com/shop/). To answer your original question, **if you properly add manually the data there should be no conflict**, just verify your code afterwards, for example with[ Structured data testing tool](https://search.google.com/structured-data/testing-tool/u/0/).
