### ISSUE TITLE
Search results pages output a few open graph tags

### ISSUE THREAD

**Issue by kevinlisota** [sybrew/the-seo-framework#168]
Search results pages are outputting an incomplete set of the following opengraph tags

og:locale
og:type
og:url
og:site_name

Some of the og tags are correctly removed, and the twitter tags are correctly removed as well. These remnants should also be removed.

**Comment by sybrew** [comment]
I've left them in for crawling verification.

https://developers.facebook.com/docs/plugins/like-button
https://developers.facebook.com/docs/plugins/share-button

I'll test how Facebook, Twitter, and Pinterest perceive them with and without the tags.

**Comment by sybrew** [comment]
Even the `og:image` and `og:description` tags may be added. 

When the site owner places a like-and/or share button on all their pages via a widget, all aforementioned tags are taken into account.

I don't see a conflict, and the current data outputted shouldn't affect performance.

If anyone wishes to discuss this further, feel free to follow up.
