### ISSUE TITLE
WPGlobus support

### ISSUE THREAD

**Issue by ghost** [sybrew/the-seo-framework#171]
Hello,

I'm not sure if this plugin has to add support for WPGlobus or if WPGlobus has to add support for this plugin. However, by default the page title and description this plugin makes are including the language codes from WPGlobus. If there's any way to fix that I think it would be great.

Thanks!

**Comment by sybrew** [comment]
I haven't heard about WPGlobus before, but this is the deal with all translation plugins:
They always require extra, maintained compatibility. This is because WordPress doesn't provide an API for these plugins.

I will look into this, but there's no ETA yet.

**Comment by sybrew** [comment]
WPGlobus should use the WordPress API to filter the title early if they haven't already; so, we can obtain the adjusted version. 

That'd filter would be `single_post_title`.
https://developer.wordpress.org/reference/functions/single_post_title/
