### ISSUE TITLE
The Events Calendar title compat

### ISSUE THREAD

**Issue by sybrew** [sybrew/the-seo-framework#176]
From [n1ck0's support topic](https://wordpress.org/support/topic/untiled-browser-title-on-default-month-view-of-events-calendar/):

The Events Calendar shows "Untitled" on some pages. 
This seemingly means that The SEO Framework can't access the CPT/CPT-archive title through WordPress' API.

**Comment by nick0** [comment]
Thanks @sybrew. Currently this only happens to us on the browser title of the default month view page. Default list, day, photo and map work fine.

**Comment by nick0** [comment]
Thanks so much @sybrew. 2.9.4 fixed the issue. Cheers mate

**Comment by Wisecompany** [comment]
I am still having this issue on the latest version of the SEO Framework and The Events Calendar.

**Comment by sybrew** [comment]
That plugin's [hijacking the WordPress query](https://github.com/moderntribe/the-events-calendar/blob/4.6.23/src/Tribe/Query.php#L247-L253) (without setting the page name), instead of [correctly registering the archives](https://developer.wordpress.org/reference/functions/register_taxonomy/). 

I tested a few SEO plugins with their monthly archives, and they all show different issues with the titles.

I can't open an issue on their Github, so I'm afraid you'll have to resort to their support forums.

**Comment by Wisecompany** [comment]
Okay, thank you @sybrew for looking into it.

**Comment by sybrew** [comment]
It seems the plugin's setting "noindex" for its event archives. This is good, because you can safely disable the post type without having to worry about the mixed titles for the `/events/` endpoint:
![image](https://user-images.githubusercontent.com/7662236/46212813-36836b00-c337-11e8-9a89-b9261f8794ed.png)

Note that the option will disable TSF for the single events, too.

**Comment by Wisecompany** [comment]
This fixed the issue! Thank you!
