### ISSUE TITLE
Remove title additions from social share title tags

### ISSUE THREAD

**Issue by atdr** [sybrew/the-seo-framework#178]
An option to remove the additions (e.g. blog name) from the post title tag used for social sharing would be helpful.

Facebook as an example includes the domain below the description so including blog name in the title doesn't add much value.

**Comment by sybrew** [comment]
Duplicate: https://github.com/sybrew/the-seo-framework/issues/64
Related: https://github.com/sybrew/the-seo-framework/issues/120

Hi @atdr 

Thanks for your feedback, it's something I also had in mind for a long time 👍 
Please continue this thread on #64. Cheers!
