### ISSUE TITLE
Meta Keywords Support

### ISSUE THREAD

**Issue by neodjandre2** [sybrew/the-seo-framework#181]
I am aware that Google doesn't add much value to meta keywords but other search engines do, according to this article:

http://www.digitalmarketingmaturitymodel.com/in-2017-should-i-be-using-meta-keywords/

Perhaps you could add a function like this, to simply support tags as meta keywords?

https://webvamp.co.uk/blog/seo/using-wordpress-tags-as-keywords/

Many thanks,
Andrew

**Comment by sybrew** [comment]
Hi Andrew,

I can't hold blog posts by anonymous authors without statistical data in high regard.
I find announcements and blog posts from the actual source much more believable:
- Bing/Yahoo: https://blogs.bing.com/webmaster/2014/10/03/blame-the-meta-keyword-tag
- Google: https://www.youtube.com/watch?v=jK7IPbnmvVU

In conclusion, keywords are useless, and 95% of search traffic won't take them into account.
[Some have stated](https://www.semrush.com/blog/the-myths-behind-meta-keywords/) that use of keywords even penalizes your site.

The code example posted first builds the site's body and then writes the head. It is possible, but then you require output buffering whilst you're writing in reverse. 
Besides that, I'm not going to touch the content anytime soon with my plugins. I believe that's where themes and the CMS (i.e. WordPress) are for.
