### ISSUE TITLE
Change Tag Title Archives 

### ISSUE THREAD

**Issue by neodjandre2** [sybrew/the-seo-framework#189]
Hi,

Is it possible to change the titles and meta descriptions for Tag Archives ?

many thanks,
Andrew

**Comment by sybrew** [comment]
Hi @neodjandre2 

This is possible, simply go to the tag edit screen and you'll find "Tag SEO Settings":

![image](https://user-images.githubusercontent.com/7662236/30144874-3493e3c6-938e-11e7-94f0-182413a565b2.png)

**Comment by neodjandre2** [comment]
Hi, I have about 1,000 tags so would be difficult to do this for each one of them.

Is it possible to do this via a function ?

e.g.
The title should be: "Tag Name" Latest News and stories
description: These are the latest news and stories for "Tag Name"

many thanks!

**Comment by sybrew** [comment]
Hi @neodjandre2 

If you wish to apply the above to all tags, let me know and I'll write something up for you.
Otherwise, I'm afraid you still require manual adjustments.

Note that tags (especially when you've saturated your site with hundreds of them) generally don't rank well, so in the end, it might not be worthwhile.

**Comment by neodjandre2** [comment]
Yes the plan is to come down to about 200 tags but they are still going to rank well I believe, if I can automate adding the title and meta description, so your help would be much appreciated. :)

**Comment by sybrew** [comment]
Hi @neodjandre2 

I believe it should work great for you:
```php
add_filter( 'the_seo_framework_get_term_meta', function( $data = array(), $term_id ) {

	//! This method is marked private. So use might change unannounced, although unlikely.
	$term = the_seo_framework()->fetch_the_term( $term_id );

	// Stop if it's not a "post_tag".
	if ( 'post_tag' !== $term->taxonomy )
		return $data;

	$data = array(
		'doctitle' => $term->name . ' Latest News and stories',
		'description' => 'These are the latest news and stories for ' . $term->name,
	);

	return $data;
}, 10, 2 );
```

By default, the filter doesn't work on term meta that has already been adjusted with TSF enabled.

So, what it does:
1. It grabs all terms that are "new" in the eyes of TSF.
2. It sets pre-filled manual Tag Title and Description, which you can easily alter later.
3. Once you've saved the tag (ever) with TSF enabled, the filter won't work anymore for the tag and your manual input is used.
4. What's put in the filter isn't automatically saved, so you can change your mind later.

**Comment by neodjandre2** [comment]
Yes this works great ! I think it would be useful to incorporate to the plugin itself :)

**Comment by sybrew** [comment]
Allowing for defaults per archive and other types are planned. But first, we want to have a framework that supports it:
https://github.com/sybrew/the-seo-framework/issues/140

**Comment by majestica** [comment]
> Hi @neodjandre2
> 
> I believe it should work great for you:
> 
> ```
> add_filter( 'the_seo_framework_get_term_meta', function( $data = array(), $term_id ) {
> 
> 	//! This method is marked private. So use might change unannounced, although unlikely.
> 	$term = the_seo_framework()->fetch_the_term( $term_id );
> 
> 	// Stop if it's not a "post_tag".
> 	if ( 'post_tag' !== $term->taxonomy )
> 		return $data;
> 
> 	$data = array(
> 		'doctitle' => $term->name . ' Latest News and stories',
> 		'description' => 'These are the latest news and stories for ' . $term->name,
> 	);
> 
> 	return $data;
> }, 10, 2 );
> ```
> 
> By default, the filter doesn't work on term meta that has already been adjusted with TSF enabled.
> 
> So, what it does:
> 
> 1. It grabs all terms that are "new" in the eyes of TSF.
> 2. It sets pre-filled manual Tag Title and Description, which you can easily alter later.
> 3. Once you've saved the tag (ever) with TSF enabled, the filter won't work anymore for the tag and your manual input is used.
> 4. What's put in the filter isn't automatically saved, so you can change your mind later.

Hi, is the filter not working anymore? I tried it and nothing has changed, please tell me how can I fix it? I have more than 400 tags, it is very difficult to fill in everything with your hands, I would like to fill the meta title and description for all tags as you described above using the template with tag variable name, and then, if any need manual editing, correct it through the admin panel. thank

**Comment by sybrew** [comment]
Hi @majestica 

Yes, that filter was deprecated in TSF v3.1.0, and removed in TSF 4.0.0.

You should now use `the_seo_framework_term_meta_defaults`; which works the same, and almost does the same, but fits even better with your scenario.

Note that `fetch_the_term()` has also been deprecated. If you need it, you can use WordPress's native `get_term_by( 'id', $term_id )`.

**Comment by majestica** [comment]
> Hi @majestica
> 
> Yes, that filter was deprecated in TSF v3.1.0, and removed in TSF 4.0.0.
> 
> You should now use `the_seo_framework_term_meta_defaults`; which works the same, and almost does the same, but fits even better with your scenario.
> 
> Note that `fetch_the_term()` has also been deprecated. If you need it, you can use WordPress's native `get_term_by( 'id', $term_id )`.

ill try use somethink like this

**Comment by sybrew** [comment]
Hi @majestica,

Change `id` with `term_taxonomy_id` in `get_term_by()`, and it should work. 
I didn't know `id` required the third `taxonomy` parameter to be filled. My bad!

P.S. In the future, see if you can log debugging errors, the filter should've filled the logs.
e.g. add this as a mu-plugin:
```php
<?php
// Get preferred reporting level here: https://maximivanov.github.io/php-error-reporting-calculator/
error_reporting( E_ALL );

// Log at /wp-content/error.log--Might contain sensitive information, so restrict it via .htaccess!!!
ini_set( 'error_log', WP_CONTENT_DIR . '/error.log' );
```

**Comment by majestica** [comment]
> Hi @majestica,
> 
> Change `id` with `term_taxonomy_id` in `get_term_by()`, and it should work. You might also want to test if a term is returned at all before testing its object values.
> 
> I didn't know `id` required the third `taxonomy` parameter to be filled. My bad!
> 
> `fetch_the_term()` uses some (faulty) fallback mechanisms, which shouldn't be relied upon. That's why I deprecated it.
> 
> P.S. In the future, see if you can log debugging errors, the filter should've filled the logs.
> e.g. add this as a mu-plugin:
> 
> ```
> <?php
> // Get preferred reporting level here: https://maximivanov.github.io/php-error-reporting-calculator/
> error_reporting( E_ALL );
> 
> // Log at /wp-content/error.log--Might contain sensitive information, so restrict it via .htaccess!!!
> ini_set( 'error_log', WP_CONTENT_DIR . '/error.log' );
> ```

Great, thanks
that work
