### ISSUE TITLE
Filter for JSON Search schema

### ISSUE THREAD

**Issue by MichaelPereiraUK** [sybrew/the-seo-framework#19]
Hi,

I'm working with an edge case where I'm not using the `?s=` search parameter for my site but there's little control for changing the potential action schema.

Is there an objection to adding a filter for the `$target` variable or maybe the `$json` variable for full control?

**Comment by sybrew** [comment]
Hi Michael,

There's absolutely no objection, I just need to know how you've changed that query and I might be able to automatically implement such functionality :+1:.

The reason for this is because The SEO Framework looks at the "s" query parameter on more places.

Keep me posted and have a great day!

**Comment by MichaelPereiraUK** [comment]
My actual use case is where Magento is installed as a subfolder /shop/ and i'm wanting to make it's native search the potential search action.

Yoast has a filter for this called `wpseo_json_ld_search_url`

In other scenarios you might be wanting to make the search parameter a pretty URL like `/search/foobar` which a few methods of implementation can be found [here](http://www.haloseeker.com/making-pretty-wordpress-search-urls-is-better-for-seo/).

**Comment by sybrew** [comment]
Hi Michael,

It has been added, see https://github.com/sybrew/the-seo-framework/commit/f0c35189d059adaa0a69ba2171aac137a22d26a8
It will ship with the 2.7.0 release.

The filter `the_seo_framework_ld_json_search_url` defaults to `http://example.com/?s=`. 
This means you'll have to supply the `?s=` yourself.

Please note it's cached within a transient. You can flush the home page cache by re-saving the SEO Settings. This is the only place where the search script is output.

**Comment by MichaelPereiraUK** [comment]
@sybrew - Great, Thanks.
