### ISSUE TITLE
article:publisher Facebook Meta not supported

### ISSUE THREAD

**Issue by mitchmenghi** [sybrew/the-seo-framework#192]
Hi i have come across this issue that is not present with AIO SEO Pack.

https://screenshots.webchemistry.com.au/2017_09_13_16_19_47.jpg

Sharing debugger finds an incompatible article:publisher meta. Please advise

**Comment by sybrew** [comment]
In short: `article:publisher` shouldn't be outputted when `og:type` is `website`.

Will look into this. Thanks!

**Comment by sybrew** [comment]
`article:publisher` should only be output when `og:type` is `article`.

Fix will be shipped with 3.0.0
