### ISSUE TITLE
Organization SEO through Schema.org 

### ISSUE THREAD

**Issue by sybrew** [sybrew/the-seo-framework#193]
Current Organization/Corporate SEO incorporated in The SEO Framework is incomplete and relies on the theme.
It also stems from [2.6.0](https://theseoframework.com/?p=1196); a huge update relied on an old foundation, yet set roots for the current.

Therefore, the current implemented format is unreliable and difficult to maintain.

So, a new extension that will set up basic information regarding the coupled Organization of your website, is planned.

This extension will feature all settings required for fully-fledged Organization SEO, and will no longer depend on the theme.

**This extension will replace the current implementation, and the current implementation *might* be removed in a future TSF update.**
I am aware that **removal** is an unpopular move. But, I'm sure few of you understand what the current options actually do. **Feedback is required!**

### The extension

This extension will replace currently set Schema.org settings, in a much better format.
These settings will be used for the [Articles extension](theseoframework.com/extensions/articles/), among other items planned in the future.

**This extension covers the following data:**
1. [Corporate Contacts](https://developers.google.com/search/docs/data-types/corporate-contacts), i.e. Phone Number, Language, Areas served.
2. [Logo](https://developers.google.com/search/docs/data-types/logo), in various formats, to accomplice Articles.
3. [Social Profile Links](https://developers.google.com/search/docs/data-types/social-profile-links).

**What needs to be done:**
1. Current Schema.org information set up in The SEO Framework must have a filter attached, for it to be completely disabled.
2. We need to annotate extension dependencies. The Articles extension will depend on this extension when using AMP. And for it to have AMP output, it depends on the [AMP extension](https://theseoframework.com/extensions/amp/).

**What might be done:**
1. Remove current Schema.org features from The SEO Framework.

**Comment by SchneiderSam** [comment]
Please check this: 459

Idea for an new extension?

**Comment by sybrew** [comment]
[Corporate Contact](https://developers.google.com/search/docs/data-types/corporate-contact) is now deprecated, probably in favor of Google My Business and data from Wikipedia.
