### ISSUE TITLE
Settings capability doesn't allow saving

### ISSUE THREAD

**Issue by sybrew** [sybrew/the-seo-framework#196]
From [patchekohoss reply](https://wordpress.org/support/topic/the-seo-framework-and-woocommerce-shop-manager-user-role/#post-9513373):

Using filter `the_seo_framework_settings_capability` doesn't allow the user to save.

**Comment by snrbrnjna** [comment]
🙈

**Comment by paulovsky** [comment]
I also have this problem. Any help would be appreciated.
