### ISSUE TITLE
sharing does not show image

### ISSUE THREAD

**Issue by neton-bricio** [sybrew/the-seo-framework#2]
Hello

I installed the plugin on one of my sites and I'm enjoying the performance.

But I have a problem. When I share a post on social networks (Facebook, G +, Twitter) the highlighted image does not appear in the post sharing.

If you could help me solve this problem I would be very grateful.

sorry for my bad English.
![2016-04-26-14 41 32_477x372](https://cloud.githubusercontent.com/assets/8245457/14829989/c639c4e2-0bc4-11e6-925e-8e718f16adba.jpg)
![2016-04-26-14 46 00_583x357](https://cloud.githubusercontent.com/assets/8245457/14829994/cb43ddb0-0bc4-11e6-8d35-f43b139d9c15.jpg)
![2016-04-26-15 05 40_372x378](https://cloud.githubusercontent.com/assets/8245457/14830001/d04013ce-0bc4-11e6-9ea1-c1686e606583.jpg)

**Comment by sybrew** [comment]
Hi Neton,

Are you using a plugin that cleans up your original image file? The SEO Framework relies on the original file being present.

For example, you've uploaded:
`http://tribunadocerrado.com.br/wp-content/uploads/2016/04/impeachment-senado.jpg`
And it has been converted to:
`http://tribunadocerrado.com.br/wp-content/uploads/2016/04/impeachment-senado-300x160.jpg`

And now the original upload is gone. This is why the original image is resulting in a 404 page. So no image is shown.

I hope this clears things up!

**Comment by neton-bricio** [comment]
Hello mother.
Thank you for investigating this flaw. He helped me solve the problem. Now everything is working perfect.
Solution: I disabled the rotlinks instructions in .htaccess | others may have this problem. Remember that some accommodation offers lock hotlink by Cpanel.
Whenever this issue arises, disable hotlink in cpanel and .htaccess can be the solution.
