### ISSUE TITLE
Post Type Archive options meta box

### ISSUE THREAD

**Issue by sybrew** [sybrew/the-seo-framework#20]
From: [Eelco's plugin review](https://wordpress.org/support/topic/a-good-and-clean-plugin)

New feature for options that allow custom **titles and descriptions** for non-editable query types, like 404 and search.

**Comment by sybrew** [comment]
Status update...

**Title output:**
The following filters are already present, these will be used for further manipulation through the planned extension:

```
/** 
 * 404 title filter.
 * @since 2.5.2
 */
add_filter( 'the_seo_framework_404_title', 'my_404_title' );
function my_404_title( $default = '404' ); {
	//* Will be escaped on output.
	return 'four oh four';
}

/**
 * Search title filter.
 * @since 2.6.0
 * @note The default title can be translated.
 */
add_filter( 'the_seo_framework_search_title', 'my_search_title' );
function my_search_title( $default_i18n ='Search results for:' ) {
	//* Will be escaped on output.
	return 'Custom Search:';
}
```

**Description output:**
On Search and 404, no description will be output currently to save resources.
In almost all cases, these pages will not rank well on SERP.
See: [front end output code](https://github.com/sybrew/the-seo-framework/blob/6aa09d84a65d0378734a518edd97acb1182ba678/inc/classes/init.class.php#L233-L274).

Facebook generates its own description from the content (like Google does) on pages without any description present.

Plausible resolutions: 

1. Move the 404/Search check within the `the_description()` method (or further); however, this requires the filter to be used prior to the output or be moved (which might even improve performance when a filter is used).
1. Let the extension output its own meta tag. This might lead to bugs or incompatibilities if changes do happen (inconsistency).

**Other output:**
Images, and many other items that can be output, are currently not. 
This is to save resources (404 and search pages are usually not cached).

Plausible resolution on 404: Transient cache for the whole 404 output.
Plausible resolution on Search: none yet &mdash; it's dynamic (in a certain sense).

I do not believe that there's any interest in any other output apart from the title and description. 
Please provide feedback on use cases if otherwise.

**Comment by sybrew** [comment]
From [Eusebiu's suggestions](https://wordpress.org/support/topic/possible-improvements-2/):
It would also be great if CPT registered Archives and other archive types without UI would contain its own metabox.

This metabox could be added to the SEO Settings page (or a new tab) with a default (or stripped) SEO metabox.
The metabox should have a CPT switcher at the top right/left, to prevent overpopulating the settings page. This switcher will allow you to select which CPT you wish to populate the SEO fields for.
How this would work without JavaScript is still in consideration.

**Comment by sybrew** [comment]
Here's are filters which you can use before this is implemented.

<details>
<summary>Filter placeholder example: (click me)</summary>

```php
/**
 * Filters the raw titles generated by The SEO Framework for non-queryable pages.
 * 
 * Doesn't require escaping.
 * 
 * @param string     $title The filter title.
 * @param array|null $args  The query arguments. Accepts 'id' and 'taxonomy'.
 *                          Is null to autodetermine query.
 * @return string The raw generated title output.
 */
add_filter( 'the_seo_framework_title_from_generation', function( $title, $query ) {

	// We don't want to filter predefined queries. This will conflict in breadcrumbs otherwise.
	if ( null === $query ) return $title;

	$tsf = \the_seo_framework();

	if ( $tsf->is_404() ) {
		// Overwrite 404 title here. Default is shown.
		$title = $tsf->get_static_404_title();
	} elseif ( $tsf->is_search() ) {
		// Overwrite search title here. Default is shown.
		$title = $tsf->get_generated_search_query_title();
	} elseif ( $tsf->is_real_front_page() ) {
		// Overwrite front page title here. Default is shown.
		$title = $tsf->get_static_front_page_title();
	} elseif ( $tsf->is_archive() ) {
		// Overwrite archive page titles here. Default is shown.
		$title = $tsf->get_generated_archive_title();
	} elseif ( $tsf->is_singular() ) {
		// Overwrite singular page titles here. Default is shown.
		$title = $tsf->get_generated_single_post_title();
	}

	return $title;
}, 10, 2 );
```

</details>

<details>
<summary>Real world example: (click me)</summary>

```php
/**
 * Filters the raw titles generated by The SEO Framework for non-queryable pages.
 * 
 * Doesn't require escaping.
 * 
 * @param string     $title The filter title.
 * @param array|null $args  The query arguments. Accepts 'id' and 'taxonomy'.
 *                          Is null to autodetermine query.
 * @return string The raw generated title output.
 */
add_filter( 'the_seo_framework_title_from_generation', function( $title, $query ) {

	// We don't want to filter predefined queries. This will conflict in breadcrumbs otherwise.
	if ( null === $query ) return $title;

	$tsf = \the_seo_framework();

	if ( $tsf->is_404() ) {
		// Overwrite 404 title here.
		$title = '404 Not Found';
	} elseif ( $tsf->is_search() ) {
		// Overwrite search title here. Visitor-fed variable, best to pre-escape.
		$title = sprintf( 'Search: &#8220;%s&#8221;', \get_search_query() );
	} elseif ( $tsf->is_real_front_page() ) {
		// Use default title.
	} elseif ( $tsf->is_archive() ) {
		if ( is_post_type_archive( 'product' ) ) {
			$title = 'Product overview';
		} else {
			// Use default title.
		}
	} elseif ( $tsf->is_singular() ) {
		// Use default title.
	}

	return $title;
}, 10, 2 );
```

</details>

**Comment by sybrew** [comment]
I punted this to 3.4.0. I must send out 3.3.0 sooner.

**Comment by remcokalf** [comment]
I also am waiting for titles+descriptions+robots for Custom Post Types and Custom Post types archive pages. But I am also missing the same for Custom Taxonomies. Like in Yoast. My sites often rely heavily on CPTs and Custom Taxonomies.

**Comment by ooksanen** [comment]
Any news on this? The above filters, or the ones in [API docs](https://theseoframework.com/docs/api/filters/) don't seem to work in 4.0.5

**Comment by ooksanen** [comment]
Not sure if it's possible, but IMHO it would be best if the CPT shouldn't need to be set to public for the filters to work. It's not unusual to have CPT for which you don't want the single posts to be indexed or accessible, but want to have an archive page for.

For example in a current project, we have a CPT with so little post content, it doesnt't warrant for a subpage, such as `domain.com/cpt-archive/single-cpt`. Instead we have an archive `domain.com/cpt-archive` page that lists the posts and the small amount of content is shown in a lightbox / modal window. 

For this case I cannot make the CPT public and/or allow indexing so the filters won't work and my only option to set my custom title and description is to make a custom page template for listing the posts, which would be unnecessary if it would be possible to set the archive title and description even for non-public CPT whether via a filter or TSFW settings.

**Comment by camealeon** [comment]
> 
> 
> I also am waiting for titles+descriptions+robots for Custom Post Types and Custom Post types archive pages. But I am also missing the same for Custom Taxonomies. Like in Yoast. My sites often rely heavily on CPTs and Custom Taxonomies.
> 
> Currently the absense of default CPT, CPT archive and Tax term title/meta/settings is the only thing holding me back to move from Yoast to TSF for larger sites.

Hey @sybrew is there any update maybe for that? I recently abandoned rank math for seo framework, and that one is missed for me. It could be great to have Custom Post, Custom Taxonomies Seo titles creation. I have some items for sell on custom post type and would like to add and postfix to title. That would be great!

**Comment by sybrew** [comment]
Hi @JeffreyskiPL, 

This feature is slated for 4.1, which will be our next major update 😄 It will take a couple of months to complete, so don't hold your breath.

[Verbose title options](https://github.com/sybrew/the-seo-framework/issues/140) are planned as a separate entity. My plan for that is also to allow you to set title templates.

**Comment by sybrew** [comment]
Pushed to 4.2.0, because we need an update out quickly to support the new Core sitemap functionality (WP 5.5), due August 2020.

**Comment by sybrew** [comment]
Robots meta types will still land in 4.1.0. We might be able to squeeze this whole issue into the update if everything goes well.

**Comment by sybrew** [comment]
From [my comment above](https://github.com/sybrew/the-seo-framework/issues/20#issuecomment-252874509)
> How this would work without JavaScript is still in consideration.

I'm considering dropping non-JS support altogether, much as WordPress Core has with the Gutenberg (Block Editor) project. Dropping non-JS allows me to offload processing to the browser instead of redundantly pre-processing on the server. I have already dropped most of the title and description pre-processing.

The image below shows how the Post SEO Settings meta box looks with JS disabled (in 4.2.0-dev-39). Open Graph and Twitter titles still have redundantly prefilled titles, but the JS overrides that, anyway.
![image](https://user-images.githubusercontent.com/7662236/138575210-f4867622-648d-44bb-8f44-243e405870b2.png)

Ultimately, dropping support shrinks the codebase and increases maintainability.

I'll try to make this feature non-JS capable, but I'll forgo that effort at the earliest inconvenience.

**Comment by sybrew** [comment]
Provisioned layout (visibility tab) with multiple post type archives on the site:

![image](https://user-images.githubusercontent.com/7662236/139515300-b9d48143-a660-42ff-b34b-025da4c4987f.png)

Provisioned layout (social tab) with only one post type archive on the site:

![image](https://user-images.githubusercontent.com/7662236/139515375-057d2499-32aa-433d-ab10-914092262787.png)

**Comment by quadcom** [comment]
Please oh please can we get this put in pronto!

**Comment by sybrew** [comment]
In a30f46a058bdd8fe1b8f97169aba077898271c5f, I added the final piece of this puzzle: "What would happen when the post type is disabled?" Well, this:

![image](https://user-images.githubusercontent.com/7662236/140191519-4c4f1a68-08de-42da-b7d2-0dc0e934bd40.png)

I thought about disabling the select-option and adding a hint, but common HTML select-styling wouldn't allow me to convey why it was disabled. So, I opted for removing the editor and putting in place a warning message.

This feature took 14 days, 140 hours, 15 commits, and 100 file changes to complete. You can view the timeline here: https://github.com/sybrew/the-seo-framework/compare/64b64e28e534304ee7e1bea65b25e8ec46241f85...0ae8fc3679da3df7cd48c42411505b532b419172.

I think that'll make for a nice feature-packed 4.2.0 update. So, I'll punt most (all?) other items [from the milestone](https://github.com/sybrew/the-seo-framework/milestone/38). A complete code review will still occur, for I found a few bugs in need of resolving. As always, I'll test the update on my networks to find errors spawn and review changes in Google Search Console et al.

Fun fact: If you hit <kbd>space</kbd> in a Post Type Archive's title with Archive Title Prefixes enabled (under Title Settings), you'll find two floating titles. This feature was developed a couple of years back but never utilized (and I honestly forgot I coded it). The behavior is intentional, for your space will be removed on-save anyway. I consider it a bug that Terms (Category/Tags) do not behave the same.

![image](https://user-images.githubusercontent.com/7662236/140194016-afe46877-86b9-4249-b93e-70e8d4d3c9f8.png)

**Comment by bonakor** [comment]
Hi, 
Would it be possible to get it for the Custom Taxonomies too,please?

**Comment by sybrew** [comment]
Hi @bonakor, 

This feature works with any registered Post Type Archive. 
TSF already supports all public terms. If you do not have an interface for those, they may be registered as non-public. 

Please open a support topic and share the code you used to register the custom taxonomy so we can investigate the issue: https://tsf.fyi/support/tsf/new-topic.
