### ISSUE TITLE
Host directive in robots.txt for Yandex

### ISSUE THREAD

**Issue by Clevelus** [sybrew/the-seo-framework#200]
If the site uses SSL, for Yandex it is mandatory to use the HOST directive in robots.txt. No other search engines use this directive, but it does not interfere with them. A good directive should be closed only for Yandex ("User-agent: Yandex"), but this is not necessary.

Also for weak sites it may be useful to use the "Crawl-delay" directive. When indexing a weak site with a Yandex, it can put it (500 error).

More info: https://yandex.com/support/webmaster/controlling-robot/robots-txt.xml

Temporary solution (in functions.php):
```php
function add_yandex_content(){
 $out = "\r\n";
//$out = $out . "Host: https://mysite.ru\r\n";
//$out = $out . "Host: " . get_site_url(null, '', 'https'); // -- use SSL checkbox!
$out = $out . "Host: " . get_site_url();
$out = $out . "\r\n";
return $out;
}

add_filter( 'the_seo_framework_robots_txt_pro', 'add_yandex_content' );
```

**Comment by Clevelus** [comment]
My full code:
```php
function add_yandex_content(){
  	$out = "";
  	//$out = $out . "Disallow: /wp-admin\r\n";
  	$out = $out . "Disallow: /wp-includes\r\n";
  	$out = $out . "Disallow: /wp-content/plugins\r\n";
  	$out = $out . "Disallow: /wp-content/themes\r\n";
  	$out = $out . "Disallow: /wp-login.php\r\n";
  	$out = $out . "Disallow: /wp-register.php\r\n";
  	$out = $out . "Disallow: /comments\r\n";
  	$out = $out . "Disallow: */trackback\r\n";
  	$out = $out . "Disallow: */embed\r\n";
  	$out = $out . "Disallow: */feed\r\n";
  	$out = $out . "Disallow: /cgi-bin\r\n";
  	$out = $out . "Disallow: *?s=\r\n";
  	$out = $out . "\r\n";
	$out = $out . "Host: " . get_site_url();
  	$out = $out . "\r\n";
	return $out;
}
add_filter( 'the_seo_framework_robots_txt_pro', 'add_yandex_content' );
```

**Comment by sybrew** [comment]
## Host directive
Duplicate of https://github.com/sybrew/the-seo-framework/issues/50
It's been a year, but I expect what I posted there still holds true.

If you have proof of adversities with the omission of the Host directive, please let us know.

## Crawl delay
The Crawl-delay directive is manageable through the webmaster tools. Search Engines should also consider slowing down crawling when they notice it takes a long time.
Regardless, if your site can't handle multiple visitors at the same time, you should consider switching hosts.

That said, a crawl delay might be handy for users still finding difficulties, but I see it as redundant.
On the other hand, the crawl delay directive can save bandwidth.

I'm waiting for your (and others') feedback 😄

**Comment by sybrew** [comment]
Yandex no longer promotes usage of this. Use canonical URLs instead.

You can adjust your host easily via the General Settings at `/wp-admin/options-general.php`:
**Site Address (URL)**
