### ISSUE TITLE
Title Generation rewrite: back to basics

### ISSUE THREAD

**Issue by sybrew** [sybrew/the-seo-framework#202]
Related: #166

## Too complex

Currently, the Title generation is (like #201) a very complex system.
It first determines whether `wp_title()` is used, and through that logic, it determines if it's doing it wrong (or not).

Then, it determines the query; and it constantly compares the query to the set parameters.
For this reason, it works on both the front-end as back-end.

**This is currently stable**, but even I, as the developer of it all, have a difficult time comprehending what it does.

### Sketched Flowchart : Current logic
![image](https://user-images.githubusercontent.com/7662236/31087891-1082268a-a79f-11e7-873b-1f314bba4245.png)

## A better flow

First, we should split the filter usage. So, it no longer has to determine which title output form is used.
Secondly, when using `wp_title()`, it should use the WP 4.4 filter `wp_title_parts`. Which prevents us from having to "fix" the title.

Third, and most importantly, we need to separate functionality between **generation from front-end query**, **generation from admin-query**, and **getting by parameters**.

What this means is that the method is no longer god-like, but is split over different methods:
* `wp_title_parts` filter method.
* `pre_get_document_title` filter method.
* `get_frontpage_title()` method.
* `get_singular_title()` method.
* `get_term_title()` method.
* `get_title_separator()` method.
* `get_blogname()` method.

### Flowchart : Example generation from front-end query:
![image](https://user-images.githubusercontent.com/7662236/31087306-d61b8858-a79c-11e7-92a4-d89c3861a212.png)

### Flowchart : Example generation from admin query or input:
![image](https://user-images.githubusercontent.com/7662236/31087727-66933fec-a79e-11e7-82f9-e6c85b5aaa18.png)

### Do not forget!

The WordPress query is much more complex. We need to incorporate 404 titles, search titles, and allow users to overwrite the title when they wish to do so.

## The verdict

This issue is quite simple to resolve. 
But, a lot of functionality (like The SEO Bar, LD-JSON, etc.) are dependant on the current system.

What this mustn't do is obstruct any of the current functionality.
What this must do is ease the code readability, maintainability, and flow. Where we can expect changes to propagate correctly, without causing bugs.

This gist is this: We want to assign expected behavior to simple methods that are only called when need be; instead of "guessing" the query, based on a huge array of parameters.

**Comment by sybrew** [comment]
Keep #88 in mind when refactoring.

**Comment by sybrew** [comment]
For #140, it should be possible to completely overwrite the title.

So, we need three filters, in order:
1. `the_seo_framework_pre_add_title`
2. `the_seo_framework_add_title`
3. `the_seo_framework_pro_add_title`

I know `add_title` is an unconventional name, but it's directed at the title "adding" action.

The filters need to be updated, including title parts, so they can be dissected. 
It might be more useful to give an **array** to the user, so they can alter it before it gets "imploded".

With that in mind, this might be best:
1. `the_seo_framework_pre_add_title`
2. `the_seo_framework_pre_add_title_array`
3. `the_seo_framework_add_title`
4. `the_seo_framework_pro_add_title`

**Comment by sybrew** [comment]
The methods, just like in the URL generation, should return carbon-copies of the front-and-back-end output and vice versa. 
This means that all filters and so forth must take effect.

**Comment by GuardianMajor** [comment]
@sybrew 👍 awesome, thanks.

**Comment by sybrew** [comment]
To quickly recap what has been done. 

- [ ]  <del>These lists are locked, and reflect the final release.</del>
- [x] These lists are still subject to changes.

## Added methods

Callable as `the_seo_framework()->{$method_name}();`

e.g. `the_seo_framework()->get_title();`

* `get_title()`
* `get_custom_field_title()`
* `get_generated_title()`
* `get_raw_custom_field_title()`
* `get_raw_generated_title()`
* `generate_title_from_query()`
* `generate_title_from_args()`
* `get_generated_archive_title()`
* `get_generated_single_post_title()`
* `get_generated_single_term_title()`
* `get_generated_post_type_archive_title()`
* `get_generated_search_query_title()`
* `get_static_404_title()`
* `merge_title_branding()`
* `merge_title_pagination()`
* `merge_title_protection()`
* `use_title_branding()`
* `use_generated_archive_prefix()`
* `use_home_page_title_tagline()`
* `use_singular_title_branding()`
* `get_home_page_tagline()`

## Changed methods

For these methods, the first parameter is now expecting an array or null, instead of an ID only.

```
null  -> Determine query automatically, based on current page request.
array -> The accepted indexes are: 'id', 'taxonomy'. Don't determine query. Returns empty string or "Untitled" on failure. 
```

Although they do accept IDs, it's considered deprecated (without warning) behavior.

* `get_twitter_title()`
* `get_open_graph_title()`
* `get_generated_twitter_title()`
* `get_generated_open_graph_title()`

## Deprecated methods:

These methods still work but will invoke a warning.

* `title()`, goodbye, old friend. Use `get_title()` instead.
* `generate_home_title()`, use `get_title()` instead.
* `get_the_real_archive_title()`, use `get_generated_archive_title()` instead.
* `single_term_title()`, use `get_generated_single_term_title()` instead.
* `process_title_additions()`, use `merge_title_branding()` instead.
* `add_title_pagination()`, use `merge_title_pagination()` instead.
* `use_archive_prefix()`, use `use_generated_archive_prefix()` instead.
* `untitled()`, use `get_static_untitled_title()` instead.

## Removed methods:

Using these methods won't crash your site. But, they will return `void (NULL)` and invoke a "doing it wrong" message.

* `build_title()`
* `build_title_doingitwrong()`
* `parse_title_args()`
* `reparse_title_args()`
* `process_title_additions()`
* `build_title_notagline()`
* `get_notagline_title()`
* `generate_title()`
* `title_for_home()`
* `title_for_terms()`
* `title_from_custom_field()`
* `get_custom_field_title()`
* `post_title_from_ID()`
* `get_the_search_title()`
* `get_the_404_title()`
* `add_title_additions()`
* `add_title_protection()`
* `do_title_pre_filter()`
* `do_title_pro_filter()`
* `home_page_add_title_tagline()`

## Added filters

Read the code documentation on their usage.

* `(string) the_seo_framework_title_from_custom_field`
* `(string) the_seo_framework_title_from_generation`

...and many, many more WordPress' internal filters for titles, that are otherwise called via [wp_get_document_title()](https://developer.wordpress.org/reference/functions/wp_get_document_title/). But, with a twist: They also work on the admin screens and via custom queries.

In short, TSF plugin now relies on WordPress to do the filtering for titles. 
So, we don't need to implement our own compatibility.

## Removed filters

Use the added filters instead.

* `the_seo_framework_title_args`
* `the_seo_framework_search_title`
* `the_seo_framework_pre_add_title`, use `the_seo_framework_title_from_generation` instead.
* `the_seo_framework_pro_add_title`, use `the_seo_framework_title_from_generation` instead.
* `the_seo_framework_custom_field_title`, use `the_seo_framework_title_from_custom_field` instead.
* `the_seo_framework_add_blogname_to_title`
* `the_seo_framework_use_archive_title_prefix`, use the options API instead.
* `the_seo_framework_do_shortcodes_in_title`, use any of the two new title filters mentioned right above and return `do_shortcode( $title )` instead.
* `the_seo_framework_title_pagination`
* `the_seo_framework_title_seplocation_front`, use the options API instead.
* `the_seo_framework_title_seplocation`, use the options API instead.
