### ISSUE TITLE
Proposal: ORM to test

### ISSUE THREAD

**Issue by francescobianco** [sybrew/the-seo-framework#207]
I'm so sorry to disturb you, I would kindly ask you if you could test this library in your project! 
https://github.com/javanile/moldable
With the purpose of knowing my project and understanding if it can be integrated into yours!
To thank you for your availability I am observing your project and giving a star

Install via composer
```
composer require javanile/moldable
```

I ask you if we can help each other

**Comment by sybrew** [comment]
Hi @francescobianco 

TSF manages its dependencies fully within WordPress, and all its subsidiaries are set there.
I can't see how this project can contribute towards yours in any way whatsoever.

Regardless, I wish you the best of luck finding testers! Cheers 😄
