### ISSUE TITLE
Can't access the title and description from API

### ISSUE THREAD

**Issue by bschulz87** [sybrew/the-seo-framework#208]
How to get the generated title and description data?

I tried to add them to the post / page endpoints with the the_seo_framework_title_from_cache() functions using the 'rest_prepare_post' filter, but i just get the autogenerated data, no custom data. Also accessing the options like title_seperator would be nice.

Would really love to be able to use the SEO Framework for my JAMstack project.

**Comment by sybrew** [comment]
Hello, @bschulz87,

You can access the options through `the_seo_framework()->get_option( $key = '', $use_cache = true )`. 

About REST integration, I have yet to look into that. Could you give me an example? 
I was under the impression TSF could hook into the title output functions. That said, it will be nice to ship such enhancements (if necessary) with 3.0.0.

Note that the title generation is pending a rework, so I'm a bit hesitant giving code examples:
https://github.com/sybrew/the-seo-framework/issues/202
I'd rather integrate enhancements that will last within TSF.

Cheers!

**Comment by bschulz87** [comment]
Hello, @sybrew!

The get_option function worked like charm, thanks!

Still can't get the generated title and description.

My functions.php

`    /**
     * Add SEO Tag Filter
    */
    if ( function_exists( 'the_seo_framework' ) ) {
      $the_seo_framework = the_seo_framework();
      if ( is_object( $the_seo_framework ) ) {
        add_filter(
            'rest_prepare_post',
            'seo_tags'
        );
        add_filter(
            'rest_prepare_page',
            'seo_tags'
        );
      }
    }

    /**
     * Return SEO Tags
     */
    function seo_tags( $response ) {

      $custom_fields = get_post_meta($response->data['id']);
      $response->data['seo'] = array(
        'title' => $custom_fields['_genesis_title'],
        'description' => $custom_fields['_genesis_description'],
        'seo_title' => the_seo_framework_title_from_cache(),
        'seo_description' => the_seo_framework_description_from_cache(),
        'title_separator' => the_seo_framework()->get_option( 'title_seperator', true ),
        'homepage_description' => the_seo_framework()->get_option( 'homepage_description', true ),
        'homepage_title_tagline' => the_seo_framework()->get_option( 'homepage_title_tagline', true ),
        'homepage_title' => the_seo_framework()->get_option( 'homepage_title', true )
      );
      return $response;

    }`

My response (excerpt)
`
		"title": {
			"rendered": "Test"
		},
		"seo": {
			"title": [
				"Custom Page Title SFW"
			],
			"description": [
				"A SFW Custom Page Description"
			],
			"seo_title": "Test | WP Api",
			"seo_description": "Latest posts: Test on WP Api | Lorem ipsum",
			"title_separator": "pipe",
			"homepage_description": "Custom Home Page Description",
			"homepage_title_tagline": "Custom Home Page Title Tagline",
			"homepage_title": "Custom Home Page Title"
		},
`

**Comment by sybrew** [comment]
Hi @bschulz87,

My apologies for the late reply, I've been rushing for TSF 3.0.0 beta (we're almost there!).

Are singular post types also affected? Because as I see from your results, you targeted the blog page.
