### ISSUE TITLE
Installed plugin under the title link names

### ISSUE THREAD

**Issue by paaljoachim** [sybrew/the-seo-framework#214]
Hey

I am just now installed your plugin on a new local dev site and will take it for a spin. I will create issues along the way of whatever I notice that I want to bring up.

In the Installed screen.
The SEO Framework
SEO Settings I Plugin Home I Extensions I Deactivate

I am looking into making it a little shorter...

Settings I Home I Extensions I Deactivate

Changing SEO Settings to just Settings. Many plugins have a settings link below the plugin title that leads to the plugin settings screen. If someone thinks it leads to the WP settings screen then they will see that it does not.
Plugin Home to just Home. If the user thinks it will lead to the home page of their site they will find out that it does not do so.

I do understand the reasoning of having SEO Settings and Plugin Home as it makes it totally obvious that it goes to the plugin settings and the plugin home page. I am just thinking out loud about shortening these.

**Comment by sybrew** [comment]
You're right. At the moment it forces the table cells to widen with all those links.
