### ISSUE TITLE
Adding additional Document Title Separators

### ISSUE THREAD

**Issue by paaljoachim** [sybrew/the-seo-framework#216]
I am now looking at the Document Title Separators.
Can one add special characters from the characters Keyboard viewer? 

For instance a star
✸
HEAVY EIGHT POINTED RECTILINEAR BLACK STAR
Unicode: U+2738, UTF-8: E2 9C B8

An emoji
😀
Grinning face
Unicode: U+1F600, UTF-8: F0 9F 98 80

Or other symbols.

Or have a box below the existing ones to add these characters into? 
Will these then show up in a search?
As it would be one way to stand out in a search among various results.

**Comment by sybrew** [comment]
Most (if not all) UTF-8 symbols are displayed by popular search engines.

I'm unsure if some symbols/characters will be seen as separators by search engines. Therefore, I don't think it will be smart to allow users to set custom ones.

In any case, this will be possible with the implementation of https://github.com/sybrew/the-seo-framework/issues/140. So, I don't see a reason to implement this feature, it's just more code to maintain 😅.

**Comment by init-bobJames** [comment]
👋Hello!

I know this is 4 years later; but I would like to try using : as seperator. Seems big agencies are using this, or Google started using this in branded titles. I would like to follow but cant see option for : Title Separator :

Thank you 👍
