### ISSUE TITLE
Homepage titles from in-post special characters

### ISSUE THREAD

**Issue by sybrew** [sybrew/the-seo-framework#221]
From [barnez' bug report](https://wordpress.org/support/topic/version-3-0-minor-bug-with-pixel-counter-and-the-ampersand-character/):

When using special characters in the homepage in-post titles (and descriptions?), the one rendered in the Home Page Settings meta box will escape any entered attributes, like `&  => &amp;`.

The escaping is done for security reasons. So, I have to find a way to circumvent this without exposing users to XSS.
It seems that the escaping and rendering is done correctly on the edit.php pages. So, we might have some code coverage (i.e. spaghetti) issues.

**Comment by barnez** [comment]
Fast work @sybrew I'll be sure to post any future bugs directly here.
