### ISSUE TITLE
WPML configuration file

### ISSUE THREAD

**Issue by sybrew** [sybrew/the-seo-framework#229]
From [paulovsky's reply](https://wordpress.org/support/topic/wpml-compatibility-121/#post-9755427):

The WPML translation editor isn't fully compatible with TSF, in a sense that the translation strings aren't used in the metadata.

> https://wpml.org/documentation/support/language-configuration-files/
> https://wpml.org/documentation/related-projects/wpml-compatibility-test-tools-plugin/

**Comment by vukvukovich** [comment]
Hi,

I've tested this one.
To be able to translate SEO plugin custom fields, you need to set them as translatable in WPML. 
Afterwards those strings will appear in the Translation editor.

You can set those to translatable in two ways:

1. Directly from post like in the screenshot 
2. By going to WPML > Translation Management >Multilingual Content Setup > Custom Fields Translation (Show system fields)
<img width="2368" alt="screen shot 2018-02-01 at 1 58 41 pm" src="https://user-images.githubusercontent.com/7383476/35679802-a480ecf4-0758-11e8-862b-e521c9c171cb.png">
<img width="2074" alt="screen shot 2018-02-01 at 1 58 18 pm" src="https://user-images.githubusercontent.com/7383476/35679803-a4a28328-0758-11e8-955a-19d1abe4b487.png">

Cheers!

**Comment by sybrew** [comment]
Thank you so much for this @vukvukovich!

Is there any action needed from my side, so to make this work automagically?

**Comment by vukvukovich** [comment]
Yw!

I've created WPML config file for you. Here: #261 

Cheers!

**Comment by sybrew** [comment]
Closed in #261
