### ISSUE TITLE
Increase meta description base length

### ISSUE THREAD

**Issue by anyname** [sybrew/the-seo-framework#231]
Hello. According to Moz as of late November google have 'removed' the snippet / description length, at which point the ellipsis come into play (~166char).

While no official limit one of around 300-320chars is what is now appearing in organic serps.

Plugin needs to accommodate this & increase the limit indicator (green > red etc) and the auto generated snippet length. Not sure if Yahoo etc have followed suit, so an option to max-length the description length may be appropriate.

Useful video on this weeks whiteboard friday: https://moz.com/blog/googles-longer-snippets

**Comment by sybrew** [comment]
Not all pages are affected. Whether the user is aware of this, and how they can be, is something very to consider too. A simple toggle will have to be set on a per-page basis.

I think I'll have to test this with a simple snippet that increases at least the auto-generated lengths.

Regarding the SEO Bar, it'll have to support pixel counters before I do anything special with it. See #204.

**Comment by sybrew** [comment]
This is happening faster than I thought. Pushed up to the next major release.

**Comment by sybrew** [comment]
## Pixel reference:

![image](https://user-images.githubusercontent.com/7662236/34005335-e2c2b300-e0fa-11e7-8916-9bc60951954e.png)

That description (including ellipsis and date): **1787 pixels**.
Truncated word: **or**.

| Pixel count| Post | Page |
| ------------- | ------------- | ------------- |
| Current| 820 | 920  |
| New | 1700 | 1800  |

**Comment by ADSDAY** [comment]
Its interesting as Google is already showing more data on sites that have not changed the meta length. This is based on the content derived in the page, If it answers most answers for what google should show it will take content from the site and create its own meta description.

They also state not to be in a panic to go ahead and change all Meta data, maybe this just needs the limit lifting in TSF but not compulsory. going through a series of coloured notifications, Green, Light Green, Orange, Red etc.

**Comment by ADSDAY** [comment]
![a design day google search](https://user-images.githubusercontent.com/34550179/34005775-ef8d2bf8-e0f3-11e7-9959-c3e6d5a9eac4.png)

Tested by changing Meta in TSF 20 mins ago, and push fresh index.

**Comment by sybrew** [comment]
^ That's **1819** pixels.

**Comment by ADSDAY** [comment]
Also Title increase to by the look of it, as all accepted and showing.

**Comment by sybrew** [comment]
Yes, but that change has already been implemented. You're using 566 out of 600 pixels.

**Comment by ADSDAY** [comment]
Just loading up my SEO analysis software to see what the updates are since Googles change.

**Comment by ADSDAY** [comment]
No flags at all reported by software, Also reports max length as 325 characters.

**Comment by sybrew** [comment]
**TODO:** Test Facebook and Twitter counters. They might be very static, or also depend on pixels.

https://github.com/sybrew/the-seo-framework/issues/64 must receive higher priority due to these changes.

**Comment by sybrew** [comment]
The increase will happen with 3.0.4.

A notice should be added that the increased length will not work well with social sites.

**Comment by sybrew** [comment]
The expected updated pixel guidelines need to be recalculated due to an error:
https://github.com/sybrew/the-seo-framework/issues/231
