### ISSUE TITLE
Issue with Title tag of Author archive

### ISSUE THREAD

**Issue by bradwellsb** [sybrew/the-seo-framework#239]
![seofw-author-issue](https://user-images.githubusercontent.com/3577465/34035626-89ccedc6-e17a-11e7-81d0-1116f031b30a.png)
With the latest version (3.0.3) of the SEO Framework plugin enabled, there seems to be an issue on author archive pages. The <title> tag (as seen in the browser’s tab, etc) shows html code instead of the author and site title. In my case, the title shows up as <img alt='' src='...' ...> (see attachment) instead of just showing author’s display name.  With the plugin disabled, the title tag shows up as expected.  Here's a [sample website](https://choosebible.com/author/brian-watson/) with the issue

**Comment by sybrew** [comment]
This is an issue with GeneratePress. I'll see if I can fix it with a pull request.

In the meantime, I'll tag the author of GeneratePress: @tomusborne

**Comment by bradwellsb** [comment]
Thanks, I understood GeneratePress relied on Wordpress to generate title tags, so I assumed it wasn't an issue on their end.  I'll try to draw attention to it in their support forum

**Comment by sybrew** [comment]
That's true. But WordPress doesn't make it very easy for us 😃, so we sometimes miss one little parameter that causes an "echo/print" instead of a "return".

**Comment by sybrew** [comment]
I've inspected the code, and the "echo/print/return" issue is no longer present.
It's actually that TSF uses template parts for title generation. That's a mistake on my part.

I want to resolve this, but it'll take a lot of time to do correctly. See #202.

To resolve this case for you, I'll write a small snippet that you can add to your theme's `functions.php` file in my next comment.

**Comment by sybrew** [comment]
The code below should do the trick. It's not perfect because it can't check whether it's an Open Graph title or not, but it's temporarily.

I'm pushing the title rewrite and this bugfix to 3.1.0.

```php
add_filter( 'the_seo_framework_the_archive_title', function( $title, $term ) {

	if ( is_author() ) {
		$title = the_seo_framework()->use_archive_prefix( $term )
		       ? sprintf( __( 'Author: %s' ), get_the_author() )
		       : get_the_author();
	}

	return $title;
}, 10, 2 );
```

**Comment by tomusborne** [comment]
@sybrew What about GeneratePress is causing the issue? The theme adds theme support for the title-tag, but doesn't do any additional filtering to it at all.

Thanks!

**Comment by sybrew** [comment]
Either this filter needs to be removed, or an alternative core function needs to be found and used:
https://github.com/sybrew/the-seo-framework/blob/1e5a0ade672a82f2f5d8207ae5f96e4d64b001ae/inc/classes/generate-title.class.php#L904-L911
