### ISSUE TITLE
Flush post object cache on save/edit

### ISSUE THREAD

**Issue by sybrew** [sybrew/the-seo-framework#24]
From: [Shaikh's support question](https://wordpress.org/support/topic/unable-to-update-ogtitle?replies=4).

Add a way to flush the object cache (`wp_cache_delete()`) from a particular post or page on update/save.
This can use the same mechanism as used for transient caches.

Maybe: Rename the Transients class to Cache class.

**Comment by entr** [comment]
Why using `wp_cache_` functions at all? Instead stick with transients only. They're already being saved in object cache when available.

> Also of note is that Transients are inherently sped up by caching plugins, where normal Options are not. A memcached plugin, for example, would make WordPress store transient values in fast memory instead of in the database. For this reason, transients should be used to store any data that is expected to expire, or which can expire at any time. Transients should also never be assumed to be in the database, since they may not be stored there at all. - https://codex.wordpress.org/Transients_API

My suggestion is to just remove them altogether.

**Comment by sybrew** [comment]
You're right; the posts may not ever be edited at all. Which means the transient will be permanent.

However, it is expected that the SEO settings can change, either by user interaction or through an update from my side.
Therefore, these things are auto-expiring through transients. I do not know many plugins nor setups that interact with the transient mechanism to change its behavior.

In conclusion, your comment is spot on. I'll see if I can make this work pragmatically in the upcoming update 😄.

**Comment by sybrew** [comment]
To prevent any unforeseen conflicts; whilst keeping everything as dynamic as possible: the object cache handler is still in place for those whom wish to use it.

More options and a handler have been added (commit arriving soon).
