### ISSUE TITLE
About: Olivian's 20-point feedback list

### ISSUE THREAD

**Issue by sybrew** [sybrew/the-seo-framework#251]
From [Olivian's post](https://olivian.ro/seo-framework-plugin/):

He clearly attributed many suggestions, and I'd like to process them. 
Because the list is long and opening a dozen or so issues is inconvenient, I'll list them here.

I'm going to copy the content and put it into sections. From Olivian's footer:
> You can copy the content, as long as you specify the source.

Great! Here is the source: https://olivian.ro/seo-framework-plugin/

------------

## 1. Put the SEO settings as a Tools/Settings submenu.

>  I would have considered hiding the settings of the plugin in either “Tools” or “Settings” menu. There are just too many plugins nowadays which show the menu in the root of the menus in WordPress, making it a bit difficult to navigate. Just a small hint, you can ignore it, also.

We could, but we won't. The reasons are explained at https://github.com/sybrew/the-seo-framework/issues/218 by both @lebaux and me.

- [ ] Planned.
- [x] Closed.

------------

## 2. Explain what pixel counters do.

> I would explain a bit better what the pixel counters do. Right now the explanation is a bit unclear.

Definitely. At the time of release, I explained it in the changelog under **"The Pixel Counter"** section.
https://theseoframework.com/changelog/3-0-0-eminence/

But, I haven't found a nice location to put it yet.

- [x] Planned.
- [x] Closed.

------------

## 3. Advanced title/description options.

> I would love to have some advanced options of mass editing the Titles / Descriptions, based on:
> a. For the titles, the option of editing the prefixes / suffixes for individual elements, like categories, tags, etc.; So, all the categories to have a certain title;
> b. For both titles and description a checkmark to consider to NOT add the prefix / suffix if the title/description reaches the maximum recommended length for titles/descriptions;
> c. An option to manually edit the maximum allowed pixel width / character number of titles / descriptions;
> d. An option to take not a single prefix/suffix from just an option, but a larger number of options; so, I could define 10-20 prefixes, and the plugin should automatically take one of those for each title / description;
> e. I would prefer for the point above if you wouldn’t use random generators, as this would mean that each time the page is generated, there is a new description, title; instead, use the hash of the current URL to get the title or description (based on the slug of the post / category / page, generate a number and divide that number to the number of elements in the bucket; the module of that operation should be the element taken); I describe this in this article about meta descriptions: Meta description tag for large web sites | Olivian.ro – by Olivian Breda.
> f. How about allowing regular expressions in meta titles / descriptions?

This list is difficult to process as many points are intertwined. **TODO**

- [ ] Planned.
- [ ] Closed.

------------

## 4. Explain why one should use TSF's schema over another.

> I would explain what is the advantage of using your plugins for schema.org, instead of using a dedicated plugin.

This is tricky. 
This is mainly because I do not want to refer to the SEO settings as an entity, but rather as a part of WordPress. You'll notice many sentences in the plugin are constructed from a third-person or extremely objective aspect.

This hinders us quite a bit, and we might need to change our philosophy on this part.

In any case, it's explained here: https://github.com/sybrew/the-seo-framework/issues/67#issuecomment-272603256

- [ ] Planned.
- [x] Closed.

------------

## 5. More Schema.org items.

Specifically, Articles and e-commerce.

> You seem to offer schema.org just for breadcrumbs / sitelinks searchbox; how about each blog post to be either blog post or news article, based on schema.org? And for web sites which have an ecommerce plugin, to add schema.org for those.

We do use articles, and it's getting per-post options in the next update:
https://theseoframework.com/extensions/articles/

Like the Articles extension, we're going to be moving more Schema.org functionality into extensions.
This is because the rich data is very self-sustainable, and the higher PHP requirement by default helps us a lot with sanitation, maintainability, and speed of coding.

Regarding e-commerce, WooCommerce 3.0+ does this, and it's improving its output regularly.
Nevertheless, I've had to create my own snippet for TSF's store. So WooCommerce might require room for improvement. (See line 151: `view-source:https://premium.theseoframework.com/shop/`)

We'll see how this goes, and what we can do to improve it. 
As of right now, WooCommerce is moving faster than we can keep up with so we let them do their thing. This is because Automattic has (in software terms) "just" acquired them, and they're still embodying it into their own work. Hopefully, their pace of changing comes to a halt soon, so we can hop on board.

- [ ] Planned.
- [x] Closed.

------------

## 6. Webmaster verification input needs improvement.

>  “When adding your website to Google, Bing and other Webmaster Tools, you’ll be asked to add a code or file to your website for verification purposes. These options will help you easily integrate those codes.”
> How about teaching the webmaster how to upload HTML files to the root folder, via FTP? At some point, the web masters may decide to disable your plugin, thus making the verification in Google Search Console obsolete.

We could. However, as I'm writing out sentences, I always ask myself this:
"How does this affect Multisite users?"

Because a WordPress Multisite only uses one directory for all sites. This is how I manage all my own clients. In such scenario, adding a file to the base directory could interfere. 

Now, Google, in particular, uses a unique hash filename for each site.
Bing, however, hands you a generically named `BingSiteAuth.xml` file. This is an issue.

- [ ] Planned.
- [x] Closed.

------------

## 7. Google Webmasters is now Google Search Console.

> I would mention that they’re now called Google Search Console.

TODO: Fix this.

- [x] Planned.
- [x] Closed.

------------

## 8. What is Yandex?

> I would explain what Yandex is, and why is it worthy to connect your web site in there.

Above in the webmaster options metabox, it says: 

> Verifying your website has no SEO value whatsoever. But you might gain added benefits such as search ranking insights to help you improve your website's content.

However, Pinterest does yield benefits other than insights, like using their Apps.
We might need to split this behavior and elaborate.

Nevertheless, it's also vastly explained on the homepage of the linked-to (through the [?]) page, although this requires more intuition than knowledge:
https://webmaster.yandex.com

Regardless, we might want to add a "Learn more" button for each entry.

- [ ] Planned.
- [x] Closed.

------------

## 9. Webmaster links should be more direct.

>  For each field in which you ask the user to give a verification code, I would consider adding a link button, and when clicking on it, the user would be prompted to create a GWT / BW / YW account. It’s much simpler like this, than imagining the user to Google for “Yandex”, then find out about the Webmaster Tools, etc.;

I believe this was already the case?
**TODO:** Look into this.

- [x] Planned.
- [x] Closed.

------------

## 10. Sitemap detection wording.

> “Another active sitemap plugin has been detected. This means that the sitemap functionality has been replaced.”
> By this, I understand that you have replaced my sitemap functionality with yours. But you actually seem to have ignored your sitemap functionality, and allow the standard one.
> My suggestions:
> – Clearly state the message, so that it’s clear that you have disabled your own sitemap, favoring that of the plugin;
> – Give a message with instructions on how to disable the other plugin, and let only yours live; I think it’s better to have a single plugin doing more things, than more plugins doing various tasks;

Perfectly worded. However, see point 4 for why we don't want to go overboard on this.

- [x] Planned.
- [x] Closed.

------------

## 11. Autodetect Schema plugins.

> I have a schema.org plugin, but you don’t seem to have detected it correctly.

This is tricky. Especially since we don't cover all Schema.org basis, yet.

Many Schema.org plugins allow users to set per-type values. When they wish to use TSF's Schema.org breadcrumbs instead of those, it's a catch-22 with autodetection instated.

So, we've placed a filter for other plugin authors to adjust this instead of autodetection.

https://github.com/sybrew/the-seo-framework/blob/7ea72a70b86af94aacdf4580bea958174f99e3a2/inc/classes/detect.class.php#L495-L509

- [ ] Planned.
- [x] Closed.

------------

## 12. Introduce setting sub-tabs.

> In the settings page, you have a tabbed interface with 4 tabs, then, beneath it, you have a very long list of options which are not tabbed; it’s an unnatural use of a dashboard; I would expect a tabbed interface to show me all the information divided in 4 tabs, not the way you do it currently;

I think introducing sub-tabs is the gist of this? I like that idea.

First, I want to auto-generate the options page. Because building this in HTML is a hell to maintain.

- [ ] Planned.
- [x] Closed.

------------

## 13. Explain query alteration settings.

>  “Query Alteration Settings”
> I didn’t understand what does this refer to.

Hover over the [?]:
_"This allows you to exclude pages from on-site search results."_ 

Disabling it will remove some in-page SEO visibility options:
![image](https://user-images.githubusercontent.com/7662236/34575191-20665d30-f17a-11e7-9a12-cbe2bb088549.png)

- [ ] Planned.
- [x] Closed.

------------

## 14. Edit fields from placeholders.

> When I edit my blog post, I see you offer the option to edit the meta title. What I would do, if I were you, would be to either allow the user to edit the text in place (so, instead of offering the user an empty box, offer him an option to edit the current title), or to copy & paste from a place above the text box.

This will likely clutter the dashboard.

However, I think it's a neat way of implementation. 
Maybe we could add a small pencil hovering over the field. Note that Edge adds an annoying X button, so we need to see how it all fits.

- [ ] Planned.
- [x] Closed.

------------

## 15. Live preview & more title options

> You offer, in the blog post editing options for titles / description, a red bar showing me information about the text which is inserted; what I would do better?
> – Give me the exact character count of my title;
> – Put a small “live” preview of how you would expect my title / description to appear on Google. Same font, same colors, same length. Example » (except that for this web site it isn’t “live”, as I suggest you to implement).
> – Allow me to create a few general sentences, and either add them as a bucket, for example, I would add in the settings 10 texts for product delivery (“Free delivery for 30+$ orders”, “Delivery via UPS”, “Delivery in 48 working hours” etc.), and name the bucket [delivery], and each time I type [delivery] in the title or description, you would use one of those texts for me;
> – I would love it if you would automatically take the first three sentences you see in the article, and allow me to add them via a button to the description, each sentence with an individual button.

To address each part separately:

- Pixel counter & character counter.
See the layout settings, there you can enable the character counter.

- Add live Google preview.
I dislike this idea because it'll clutter the interface and it's not uniform to the WordPress interface.
With Gutenberg coming, we might revisit this.

- Predefine sentences into verbose codes.
I believe this should be done through another plugin. See https://github.com/sybrew/the-seo-framework/issues/140#issuecomment-352506945
However, a dedicated framework is nice too. So, read the comment below on that page.

- Add buttons to auto-grab-and-insert sentences.
I also dislike this idea for its cluttery-ness. Users should also be very familiar with copy-paste.

- [ ] Planned.
- [x] Closed.

------------

## 16. Let users decide where data is stored.

> How about allowing the user to save the title & description not in your own plugin database, but in a database he chooses, so that if at some point the user decides not to use your plugin, or you don’t update it anymore, the user could uninstall your plugin and still use the database with a different solution?

They can, through the WordPress meta API. That's the API TSF uses.
Also, the options can be grabbed from the API individually. Although [this behavior will change soon](https://github.com/sybrew/the-seo-framework/issues/185), it doesn't change the fact that it's possible.

- [ ] Planned.
- [x] Closed.

------------

## 17. Elaborate on the in-post robots settings.

> You have a very poor explanation of “Apply nofollow to this Post”. Why should a user apply that setting? What are the pros/cons of doing it?

Hover over the [?], and click on it for more information.

The linked-to page only describes what it does _vaguely_ in the first paragraph. We might want to find a better resource.

- [x] Planned.
- [x] Closed.

------------

## 18. Social network-specific in-post options.

> “Custom Social Image URL”. Shouldn’t there be an option to add different images, for various social networks?

Already planned
https://github.com/sybrew/the-seo-framework/issues/64

- [x] Planned.
- [x] Closed.

------------

## 19. Set fallback image and specify which to use.

> In my opinion, the most important og:graph tag is og:image. Facebook usually takes some images from the page, if they don’t see that tag.
> What I suggest you to do:
> – In case the user doesn’t add an image to a certain blog post / page, you should ask in the settings page for a default image, for all the blog posts which don’t have an image.
> – Allow the user to mention in the settings that he wants to use images in either Featured Image setting, or as a custom field, in WordPress.

You can already set a fallback image in the Social Meta settings:
![image](https://user-images.githubusercontent.com/7662236/34576468-44278af6-f17e-11e7-9e8a-cd81307961f4.png)

Aside from that, I believe the current behavior is very intuitive. 
Changing the current flow on a per-page basis is, in my opinion, "too much" and confusing. 
Setting a field to take a specific image is much better, which is already the case.

- [ ] Planned.
- [x] Closed.

------------

## 20. Regarding issue #108

> About your future options – I don’t like automated options of checking for things like:
> – Does the metadata match with the input data?
> – How’s the code quality?
> – How’s the page performance regarding to load time?
> – Is there an AMP version?
> – Is it indexed in Google, Bing, etc. yet?
> – Is it found in the sitemap?
> – Is there a sharing button?
> – Has the post been shared on Facebook or Twitter?
> , because they can give you the wrong idea on what needs to be done.
> I would rather prefer you create something like this », and allow the user to check manually for much more things.
> You can put in words things which can’t be automatically evaluated. “Would you say that this page reflects well the user intent? Would the user share this page? Would it consider it written by authority?” These are questions which are much more important than what you can deduce automatically. If you would create a half-automated system for getting me the information (a long checklist, held on your web site, with links for each element you talk about), allowing the user to evaluate the problem by themselves, this would make me much happier.

To start off, the gist is that those features are opt-in, through an extension. Also, the ones mentioned are going to be checked from our servers. Some of those checks are already available in our [Monitor Extension](https://theseoframework.com/extensions/monitor/).

Those checks are very verbose, and it's more of an error-checklist than something suggestive.
I don't believe the mentioned checks will steer users in a direction they shouldn't be heading. It might be good to let users decide beforehand whether the check is needed for them or not.

Regarding the checklist, i.e. "Does this page reflect your intend, etc.", that's something which is already planned.
This year I hope to have Natural Language Processing implemented, which will answer those questions based on machine learning for you.

- [ ] Planned.
- [ ] Closed.

**Comment by RicaNeaga** [comment]
Hello! Thank you again for considering all the suggestions, another specialist made another one in a comment on Olivian's website - please also take this one also into account, it's related to the meta description :)

https://olivian.ro/seo-framework-plugin/#comment-173244

> Great list, Olivian! This is a thanks message for you and hopefully a useful read for devs (watching the Github repo).
I would suggest another important item to your list if you don’t mind. Meta description has now grown to around 300-320 characters. The solution should not be a character counter, as shown now, in my opinion, because the length might change overnight. AND I have the feeling the actual length will change pretty soon.
This rather long description, comparing it with what we’ve had in the past (155-160 characters), might be subject to abuse, as everything new shown as snippet in SERPs. I would modify the character counter with a simple statement (recommendation) above the input 

> box.

**Comment by sybrew** [comment]
Thanks for the update Cristi!

The comment above (https://github.com/sybrew/the-seo-framework/issues/251#issuecomment-359734652) is related to #231.

The recommendation (as stated) has already been put into effect, objectively, through the pixel counter.
It doesn't tell you to use at least N characters. Whether this is subject to change or not is still to be considered; using just a few words isn't good either.

The correlated SEO bar still requires an update to correspond to the pixel counter. The issue related to this is #204.

**Comment by sybrew** [comment]
Dated. Feel free to follow up via a new issue.
