### ISSUE TITLE
Canonical tag of author archive missing author name

### ISSUE THREAD

**Issue by Knivemare** [sybrew/the-seo-framework#255]
Hey,

the canonical tag of my author archive is redirecting to a 404 page.
```
URL: https://example.com/author/name/
Canonical: https://example.com/author/
```
As this is not a valid URL it's generating a 404 error for every page in the author archive.

I'm using TSF in combination with the theme "Publisher" by BetterStudio v3.2.0

**Comment by sybrew** [comment]
Hi @Knivemare 

Could you send me the affected page's link to my [contact page](https://theseoframework.com/contact/), so I can investigate the cause?

**Comment by Knivemare** [comment]
Hi @sybrew, 

done. Thx!

**Comment by sybrew** [comment]
@better-studio using the Publisher theme, `get_queried_object_id()` returns 0 on author archive pages.
Could you verify if this is caused by either the theme or third-party environmental changes?
