### ISSUE TITLE
Meta Description for Custom Post Type Archive pages

### ISSUE THREAD

**Issue by abombelli** [sybrew/the-seo-framework#26]
Hello

It would be great if we where able to add meta descriptions in the backend for custom post type archive pages. Without description the archive page does not appear in the Sitelinks section in the Google results.

Thanks!
Aldo

**Comment by sybrew** [comment]
Hi Aldo,

That's a great idea, and it's already planned!

See the related topic: https://github.com/sybrew/the-seo-framework/issues/20

Cheers!

**Comment by abombelli** [comment]
Thanks for your feedback!
Any timeframe? It is really the only thing we are waiting for to change the SEO plugin.
Cheers

**Comment by sybrew** [comment]
Hi Aldo,

There's no ETA as of yet; it might take a couple of weeks, it might even be delayed until early 2017.

For now, if you'd like, you can easily manually inject descriptions for certain pages or post types without any notable performance impacts with the filters below.

```
add_filter( 'the_seo_framework_description_output', 'my_special_description', 10, 2 );
add_filter( 'the_seo_framework_ogdescription_output', 'my_special_description', 10, 2 );
add_filter( 'the_seo_framework_twitterdescription_output', 'my_special_description', 10, 2 );
/**
 * Alters the description on special conditions.
 *
 * @param string $description The current description.
 * @param int $id The Post, Page or Term ID.
 * @return string Description. Does not need to be escaped.
 */
function my_special_description( $description = '', $id = 0 ) {
	
	/** 
	 * @link https://developer.wordpress.org/reference/functions/is_post_type_archive/
	 */
	if ( is_post_type_archive( 'my_post_type_name' ) ) {
		$description = 'My super description';
	}
	
	return $description;
}
```

**Comment by abombelli** [comment]
Great! Thanks you.

**Comment by carasmo** [comment]
I have 'autodescription-meta' added to my CPT custom support and I have no idea where I can modify the SEO content for CPT archive for meta content including social. There's no Twitter information, just open graph.

**Comment by sybrew** [comment]
Hi @carasmo 

`autodescription-meta` is no longer needed from TSF 3.0.4, which was released a few days ago.
If the CPT has `public` and `rewrite` set to true (or any form of true-ish), then TSF can and will interact with it. For more information, consult [WordPress' register_post_type() documentation](https://developer.wordpress.org/reference/functions/register_post_type/).

For CPT archives, please see [this comment](https://github.com/sybrew/the-seo-framework/issues/20#issuecomment-252874509), where I discussed implementing support for CPT archives.
The implementation of which is to be announced. Nevertheless, it's next in line to be included.

P.S. This is a very old issue, so I'm closing it for new comments. Feel free to open a new issue 😄
