### ISSUE TITLE
CPT's taxonomy not listed in sitemap.xml

### ISSUE THREAD

**Issue by wassim** [sybrew/the-seo-framework#260]
My CPT entries are indexed and listed in sitemap.xml. My CPT's taxonomies are indexed but not listed in the sitemap.

Is this a normal behavior?

**Comment by sybrew** [comment]
Hi @wassim,

This is normal behavior, and this shouldn't affect ranking when your website has an acceptable internal-linking structure.

The reason why there are no archives listed in the sitemaps is explained here:
https://github.com/sybrew/the-seo-framework/issues/151#issuecomment-312547890

Cheers 😄
