### ISSUE TITLE
SEO Bar shows sitewide nofollow

### ISSUE THREAD

**Issue by GuardianMajor** [sybrew/the-seo-framework#265]
**Note by @sybrew:** This topic went offtopic. Continue at #270

> As requested per our discussion in issue #138 where you wanted a simple request to be considered as a new feature.
> 
> A quick review, the ability to strip html tags sitewide with an option with a per post override for those times when you want literal tags to appear in the title of the post's page, the title of the shared items while retaining the formatting for the site front-end.
> 
> Thank you.

**Comment by sybrew** [comment]
Suggested option name:
* **Strip HTML from autogenerated titles?** [?]

Suggested [?] tooltip content:
* **This will convert valid HTML, like `<span>title</span>`, to `title` in all autogenerated titles.**

Disabled by default.

**Comment by GuardianMajor** [comment]
Looks great, that would do the trick. Might be worth noting that the placeholder text for the title DOES strip the html tags but when submitted they are put back in currently. So that was a bit confusing too.

I know it is unrelated but I wanted to put this here quickly and if need be open a new issue, but even though the `no-archive` is set globally, each post shows a notice saying, this will be archived by search engines even though you have disabled it on the whole site, so why is overriding that global disable on each post and making it so we have to manually check it for each post, that seems a bit excessive. Thanks.

**Comment by sybrew** [comment]
Yea, I noticed that bug today too. This behavior should be maintained when the option is enabled. I've made a note in the changelogs.

And thanks for notifying me of the SEO Bar inconsistency 👍 I might need to word it differently, but I'm afraid that'll lead to spaghetti code due to forward checking.
The initial (and executed) idea from the bar is that every post states its expected state and, when applicable, the "but/and" (true) state.

**Comment by GuardianMajor** [comment]
I understand and you are welcome, happy to help and glad you are aware of it. 

I know the worry for the code getting out of hand but when the "status" is loaded on that bar, it can simply check the global settings and inform accordingly without needing forward checking, correct? I hope I am not overlooking something in the logic but it can easily display based on the global and then if they want to override that, they will set it under `visibility`, correct?

**Comment by sybrew** [comment]
Well, the more information we leave out, the harder it is to understand why an option has been set in such a way; which will, in turn, increase support requests.

---------

**An example of a category for nofollow:**

1. You've enabled WordPress' option to discourage search engines from crawling the site. This will then take over the robots output.
2. **But**, you've also enabled "nofollow" for all categories. This won't be effective anymore, raising some eyebrows.
3. **But**, you've also enabled "nofollow" for the whole site. This won't be effective anymore, raising some more eyebrows.
4. **But**, you've enabled "nofollow" on the specific post/page/term, too. This won't be effective either.

The verdict:
There are three options trying to achieve the same, but WordPress overrides them. The result might be unintended behavior at any level, and the user is informed of them all.

*N.B. the example doesn't represent the order in the code.*

---------

When your website is in a developing mode, it's likely that you've mixed any of the example's options. The SEO Bar always shows all that's going on, even though it states the obvious at some point.

You know the state via the color at a glance. And when you hover over it, you can see all of the above information. It's up to you whether to resolve it or not; and at what point.

If I'd wish to keep this behavior, while wording everything differently so it'd be neater, then there will be many sentences explaining the same yet slightly different. 
Maintainability will be made very difficult because I'd have to restructure the conditions every time I wish to add one.

In [the file generating the bars](https://github.com/sybrew/the-seo-framework/blob/master/inc/classes/doing-it-right.class.php), you can see these conditions at each `$but_and` variable, this should give you an idea what's going on.

**Comment by GuardianMajor** [comment]
First before I forget, AGAIN 😄, can you provide a direct menu link to the TSF under the wordpress settings menu for example for quicker access, having to load the plugin page to click on settings is a bit inconvenient - please and thank you.

Now, I appreciate your breakdown and I get exactly what you mean but given the following settings (first specific to the homepage and later directly in regards to the robot meta):

![image](https://user-images.githubusercontent.com/5274181/36509702-698c98d8-1715-11e8-8366-b9f5e9d357ae.png)
![image](https://user-images.githubusercontent.com/5274181/36509736-87c70054-1715-11e8-922a-3a585ff1464b.png)
![image](https://user-images.githubusercontent.com/5274181/36509814-bb4f3e32-1715-11e8-8348-40b9197f5c2e.png)

As you can see, the `no-index` is not set for the whole site, just those specific types, so pages and posts should be logically indexed without any additional steps, correct? Same with the `no-follow` below:

![image](https://user-images.githubusercontent.com/5274181/36509888-f3960a5a-1715-11e8-9d67-dba40e3816f3.png)

And as you can see, I don't want the search engines to cache copies of the material, so hence the `no-archive` as seen here applied to the whole site:

![image](https://user-images.githubusercontent.com/5274181/36509940-2a102520-1716-11e8-98bd-e42b24072b16.png)

So given all that, this on a post meter is confusing, can you explain so I can understand correctly if I am misunderstanding?

![image](https://user-images.githubusercontent.com/5274181/36510018-8246ed5a-1716-11e8-985c-1279f3e75e28.png)

If it is globally marked to not follow, then this should apply to the posts/pages automatically too, correct?

And again here:

![image](https://user-images.githubusercontent.com/5274181/36510127-d837d33c-1716-11e8-8faf-88c43a5c9c8e.png)

Why if archiving is set to no for the whole site, is this post (or pages) not following that setting and having it set?

And I am sorry to put all this hear, as you said not the topic of this issue but might as well use the space wisely than pollute the issue list :grin: with a long discussion on top of it. I hope you understand my intent, if you prefer otherwise, by all means I will abide.

Thank you for your time and attention and yes I love the code conditions and design decisions, just mostly concerned about the information not being consistent with what is expected based on the options selected, that's all. I am hoping if a bug, it will resolve, if not then I can better clarify my understanding.

**Comment by sybrew** [comment]
Hi @GuardianMajor ,

Instead of "polluting" the ordered issue list, you're now "polluting" the unordered comment list 😉 
By all means, please open a new issue if you find something off-topic 😄, I'd prefer that, and users stumbling on this topic won't find unrelated information.

In any case, I've replicated your settings and I couldn't find the SEO bar output like that. This explains our subsequential confusion.

Just like that you can't find the SEO settings options menu (which should be placed right above the collapse menu button), I believe there's some configuration altering going on behind the scenes.

Deactivating plugins "one-by-one" should be an easy way to find where this issue stems from.
If you found the conflicting plugin (or theme), please report your findings in a new topic.
If you didn't find anything, then please [contact me privately](https://theseoframework.com/contact/) with the URL to your website and more information will follow suit.

**Comment by GuardianMajor** [comment]
Ok, I deserved that, but I explained why I did it this way and I am sorry that it wasn't the proper place. I will note that for the future discussions, thank you for letting me know.

It surprises me that you are not seeing that, I wonder why. I have no other competing plugins, you are the only SEO plugin and none of the other plugins come anywhere near modifying anything that is involved here.  Are these bars saved for each post or updated dynamically? Just wondering. Because I have noticed some inconsistencies for stuff that has already been published and are updated vs. new items and the behaviors are different it seems. Like for example, the first time I noticed the title was not stripping the html tags, I went back and entered a custom title with it removed and updated the post and while the post's page title changed correctly, any of the items shared from that page still showed the tags, so the update to custom title didn't seem to take effect. But on the next new post, it did and the only difference was one is new and the other was an update. Just wondering.

On the menu item, forgive me, I completely missed it. I have mine collapsed and I didn't realize the search glyph below the settings was yours, my mistake, thank you for pointing it out 😊 It is there, thank you.

**Comment by sybrew** [comment]
Hi @GuardianMajor 

I don't have the time to supervise and I'm trying to provide an open and free space for our users; please stop going off-topic in the future.
Nevertheless, I've converted this issue to a support query for you. So feel free to continue here regardless.

Back to the issues you're facing:
--------

The SEO Bar is generated on-the-fly, there's no caching of the assessments involved.

Could you share the URL you're experiencing these issues with on my contact page (linked in my previous reply)? I currently don't understand why you're experiencing these issues and guesswork takes us only so far.

Thanks!

**Comment by GuardianMajor** [comment]
Thank you, I already acknowledged beforehand that it went a bit off topic and apologized and later again when you mentioned it, there was no need for an upset reaction but I understand. The very top says continue in #270 but that is locked now, so I am assuming you meant here.

I was going to contact you on the private channel you provided when I got home but you beat me to it and did this, so I will then just say one last thing here and if you want we can continue privately.

![archive-inconsistent](https://user-images.githubusercontent.com/5274181/36566862-8e0d447c-17d9-11e8-8543-0a6b162be5fe.png)

While I understand why, as you can see the language on the second half seems to imply contradiction, although the first part makes it clear it is not.

![follow-inconsistent](https://user-images.githubusercontent.com/5274181/36566899-ae6a285c-17d9-11e8-904c-9d19920a54d8.png)

Here you see, the use of and is complimentary to the first portion which removes ambiguity. I achieved this by also checking the `nofollow` for the entire site and `noarchive` both individually and also sitewide. I suspect the language difference on the archive one is probably due to that, not sure though.

Anyway, thank you for your time and attention and I will look forward to the new release that also fixes the current placeholder having stripped tags but not in practice, which would provide a false sense of what is going on, which you already acknowledged will fix. Thanks again and if anything else I will be in touch via contact or a new issue if it turns out to be something more general.

**Comment by sybrew** [comment]
Hi @GuardianMajor,

Don't worry about it 😄  

After I tried to convey you should've opened a new topic, and with that you acknowledged it multiple times while continuing on the same topic, I tried being more straightforward backed with reasoning. I believe we are communicating on different frequencies, but we'll make it work. 😉 

Yes, this is the right topic now for the issue you're facing. 270 is for your HTML tag stripping suggestion.

The reason I asked you to contact me for the URL of your site is that I want to see whether `nofollow` is truly applied to all pages. For now, this seems like an admin-only issue where the active options don't resemble the outcome. I don't know where to trace this issue back to, as I'm missing many important variables.

I also want to ask you if the following option was enabled at the time you took screenshots of the SEO Bar.
**SEO Settings -> Robots Meta Settings -> Following:** `Apply NoFollow to the entire site? [?]`

Thanks!

**Comment by GuardianMajor** [comment]
Again, apologies if there was a miscommunication or I missed something, it wasn't my intention to frustrate or create a problem. I sincerely thought I was acting in the best interest of the discussion, I hope in time, interaction will become smoother, bear with me.

I will happily send you the link but cursory look while not logged shows the meta in the page, allow me tonight to finish grading some papers, and tomorrow after office hours, I will send it to you to look yourself and confirm as well. 

In the meantime the answer to your question: Yes, it has been enabled since last screenshot in my attempt to see if that changes the behavior and that's what I mentioned above that I made the change since then. So now they look like this:

![image](https://user-images.githubusercontent.com/5274181/36580599-c6657382-181d-11e8-87ea-12fd4aec9be5.png)
![image](https://user-images.githubusercontent.com/5274181/36580637-e4aa2e8c-181d-11e8-94ce-76786d803436.png)
![image](https://user-images.githubusercontent.com/5274181/36580651-f3fb61b2-181d-11e8-88c8-088d9631412f.png)
![image](https://user-images.githubusercontent.com/5274181/36580666-05c1e038-181e-11e8-9fb6-442b7eabadc3.png)

**Comment by sybrew** [comment]
Hi @GuardianMajor,

Once again, don't worry about it :) You were acting in the best interest. 
Unlike many other forums, GitHub issues are often focussed pieces that revolve around one thing. Going slightly in another direction (even if it might be related) will make users and developers more easily oversee crucial details related to the work that needs to be done. There's little room to make mistakes in backend software.

Anyway, back to the issue:
-----------------

So, if you'd disable the option again, does the blue notification go away with the text:
> But/and you've discouraged the following of links for the whole site.

If that's true, then I believe you're not filing a bug, but are rather discussing the "redundant" verbatim of the output. Is this correct?

Cheers 😄

**Comment by GuardianMajor** [comment]
> If that's true, then I believe you're not filing a bug, but are rather discussing the "redundant" verbatim of the output. Is this correct?

That could very well be the case 😊

In my defense, I am still getting used to the color coding and that's why I refer to the description to see what it is trying to tell me. The greens are generally assumed to be "all good" but the blue are there there whether you discourage, disable or don't, so I still need to get familiar with them. The orange so far seems to mean, "eh we are almost there" and the red is universally understood to mean "missed the mark" so that's why I was trying to understand (if ever at all) under what circumstances would these two turn green (and by these I mean the "follow" and "archive")?

With regard to bug vs. semantics, that will become clear once I have a better handle on what is happening and what each "state" actually means, which is mostly clear by logic but still trying to get comfortable enough with it to know for sure. So, I will keep you posted on that, but for sure the placeholder text for the title is showing without any tags but in reality when you finalize the post, it is there, and so that seems to be a bug where it is somehow removing while showing that but not in reality, so that is firmly a bug, but you are already aware, so no point dwelling on that. 

I have to test further to say with certainty, but it also seems that once the post is made one way, say with the tags in there because you assumed they were not (like I did the first time based on the placeholder), when you go back to edit the post and change it, upon update, it doesn't take effect and continues to show the tags. Normally I would blame that on cache, but a forced refresh doesn't invalidate that, observed on another browser to ensure as well. Also, there is/are no form of caching/optimization plugins on the site that would hold on to the old version somehow either, so I can rule that out. For context, this is the reason I asked earlier if they are somehow cached and you said they are not, they are generated on the fly, so I suspect a bug. But again, I need to test further by making a few more posts in this way to see if the changes are processed or not to be sure.

**Comment by sybrew** [comment]
Here's a list of the colors, icons, and their meaning. The icons are used in the Extension Manager, and might soon be used in TSF too.

| Color | Icon | Meaning |
|-------|------|-----------|
| Red  |         | Bad / Attention        |
| Yellow |     | Okay      |
| Green |     | Good     |
| Blue  |      | Informational / You made a questionable but probably intentional change we can't justify |
| Red | Open Cross | Error you can't fix |
| Red | Circled Cross | Doing it wrong / Error you should fix |
| Red | Flag  | Very bad |
| Yellow | Flag | Bad / Attention |
| Yellow | Check | Okay |
| Green | Check | Good |
|  | ? |  Unknown (waiting for update) / Informational |
|  | Spinning circle arrows | Loading / Waiting |   

About your bug report:
If you enable the site-wide `nofollow` option (which you shouldn't, as you prevent crawling of the pages), and then every page has a nofollow tag, then it works as intended.

The plugin almost always only handles "Enabled" states. This means that when something's enabled at any level, then it's rendered as enabled and must be disabled at all places for it to be disabled again.

There are per-page settings that can overwrite a disabled state. But there are no per-page settings that can overwrite an enabled state.

Please read the options carefully. If you aren't comfortable using the plugin after some time spent, then I'm afraid this isn't for you. 

I also recommend stop using Firefox. It's a broken browser running on a glorified IE6 Trident engine renamed as Gecko, which doesn't allow the full intent of many developers. Even WordPress has many issues with it they've never been able to resolve, like word breaks in tables on smaller screens. 
One particular case in TSF is that some checkboxes on its settings page should be red, warning you not to use them. One of which is the site-wide `nofollow` tag, **you shouldn't use it**, but it's there for edge cases.

I must agree that for some sentences the verbatim could be improved, but I think this is a case of sole misinterpretation and browser bugs. The plugin generally holds your hand by setting defaults, but from there you're on your own.

From what I read in your comments, there's no bug report related to this plugin. I don't think there's anything to add to this discussion either.
For the next steps, I recommend following the links next to the robots settings to learn more about them, so you can make an informed decision.

Best of luck 😄 Have a wonderful day!

**Comment by GuardianMajor** [comment]
Thank you for the legend, very informative, appreciate it.

The logic behind the `nofollow` sitewide is that it will also follow any link you are putting externally, correct? That could lead to incomplete crawling because then it will go into a different direction away. I will consult the documentation again to see if that behavior has changed. That's why it is not set on the homepage because that where you want it to crawl the links within your site. Again, I will look into that.

Interesting, what browser would you recommend? I mean Chrome is by day becoming more like IE ignoring general standards to make things effectively "Chrome only" much like Microsoft did with IE making everyone life miserable having to maintain multiple code compatibility. I used Chrome for a long while in favor of Firefox until it became practically unusable and very inconsistent for development and testing, as things would end up working just on Chrome as they intent but not everywhere else and that's not how development should work. Safari is a joke and absolutely not worthwhile, Opera is practically dead, and Vivaldi is based on Chromium, so just Chrome with another wrapper. Edge is pretty decent but not yet mature enough to be a daily driver. I know Firefox is not perfect, but so far has been the most consistent in dealing with standards. I wasn't aware that there is color coding in the checkboxes for TSF, I haven't seen them.

BTW, saw the update this morning, great job. The placeholder issue for the title is resolved now. Just looking forward to the implementation of the tag stripping and we should be golden. Thanks again for everything. Also, clear up one quick uncertainty for me, the other plugins you have that stack on each other, can be just simply installed and will aggregate or is there a need for a central manager to make the stack on each other? Wasn't entirely clear on that. Thanks.

**Comment by sybrew** [comment]
Hi @GuardianMajor 

About `nofollow`
-----------------
> The logic behind the nofollow sitewide is that it will also follow any link you are putting externally, correct?
 
This is incorrect. It also applies this behavior to internal links, rendering your site's linking structure useless for crawlers. This will negate all SEO benefits from internal linking, and you solely rely on your sitemap from this point (which you shouldn't).

About browsers and development
-----------------

I recommend any browser using [EdgeHTML](https://en.wikipedia.org/wiki/List_of_web_browsers#EdgeHTML-based) or [Blink](https://en.wikipedia.org/wiki/List_of_web_browsers#Blink-based). The latest versions [Webkit](https://en.wikipedia.org/wiki/List_of_web_browsers#WebKit-based) are fine too.
Browsers should follow the standards laid out by the W3 consortium, which was set up to standardize the web, thus preventing the issues Internet Explorer had.
For development, you should use all browsers you have access to, and I recommend developing first for Blink-based browsers as it's most widespread.

About the plugins
-----------------

I'm not sure what you're asking regarding the "aggregation" for the plugins' "stack" that I maintain. 

In any case, TSF and TSFEM are two stand-alone plugins. 
TSFEM relies on TSF being active for it to do anything, and it actively checks compatibility between the two for itself and its extensions.
The extensions are loaded as stand-alone modules, which can send out signals to TSF and other extensions to enhance or change behavior. The extensions heavily rely on the frameworks built in TSFEM, like hashing, form generation, layout, schema building, and meta output hooks.

**Comment by GuardianMajor** [comment]
Yes, I read up on that and changed the setting, not an issue anymore - thank you for elaborating. I felt the settings that applied to the homepage and the rest of the site would behave different in context. I am although still a bit confused why disabling archive aka setting `noarchive` for the whole site, the post are still showing as being archiveable, shouldn't that make any post `noarchive` unless you explicitly mark them to archive on per post basis? Just want to make sure I understand the behavior, that's all and I am sure there was a reason why it was done this way.

As for the browser, yes, I prefer the EdgeHTML too and love the way Edge works, but as I said can't use it as a daily driver yet due to the limited "extension" or "plugin" (depending not he terminology you prefer) availability and also the fact that it is still trying to get off the ground and has reasonably some issues to overcome but I feel in the long term it will be a great browser. I feel it has a better chance than Chrome did at this stage of development.

That's why in the meantime, I have found Firefox to strike the best balance, granted they are doing some really stupid stuff that is just exhaustingly annoying but not as much as some of the others. I have used SRWare Iron, Comodo Dragon, and Vivaldi (to name a few) and while they are great for the most part, they are all subject to the developer decisions and compromises which make you dependent on the quality of their implementation, they are slow to update and their sources are more times than not closed, for example take Comodo's Dragon and their piss poor support that amounts to a "mad max" forum. 

I have been in the field for a very long time and I have yet to find a single browser that I can use as my daily driver that impresses on all levels, there are always compromises. I tend to find the least amount of compromise with Firefox, even if you have to hack their preferences and override them to get what you want outside of their defaults. I maintain a `user.js` file that greatly neuters any of their more annoying behavior and a custom `config.js` file that override any of their decisions that take freedom of choice away. Sigh, it is a mess when it comes to browsers unfortunately and a lot of work to get what you want.

For the plugins, that's all I needed to know. I figured they are stand alone but can integrate if they find each other but wasn't sure if there is a manger of some kind necessary to make them interact, now I know, thank you for that. I saw a few plugins that I find very interesting and wanted to try them out.

Thank you again for all our help, you've been awesome. I look forward to the enhancement to get the tags stripped but in the meantime, keep up the good work and take care.

**Comment by sybrew** [comment]
`noarchive` urges third parties not to maintain copies for your site. Archiving is helpful for data checking and providing the last iteration of the webpage if it's found to be offline. Not everyone wants this, so they maintain full control of the content they put out.

And no problem @GuardianMajor, feel free to open new topics as you face any more issues.
Cheers 😄

**Comment by GuardianMajor** [comment]
Thank you. So to confirm, the site wide `no-archive` will NOT make each post automatically `no-archive` and that's by design choice, right? So if you want them to follow the decision (whatever the reason) then you have to set that on each post or they will still be archiveable, correct?

PS. I installed the Extension Manager as I realized it a more efficient way to manage the additional plugins in one place than to individually install them, so figured that out - Thanks again.

**Comment by sybrew** [comment]
Hi @GuardianMajor 

Sitewide settings override all settings. So, the sitewide `noarchive` setting will apply `noarchive` to every single page, regardless of the settings put on them individually.

**Comment by GuardianMajor** [comment]
Ok, that's what I thought but in practice getting slightly different result. Here are the current settings:

![noindex](https://user-images.githubusercontent.com/5274181/37428369-496f5700-2789-11e8-9e03-b000492eb090.png)
working as expected
![actual-index](https://user-images.githubusercontent.com/5274181/37428451-838872e6-2789-11e8-972a-e72115978e6d.png)
![nofollow](https://user-images.githubusercontent.com/5274181/37428383-55918eae-2789-11e8-87bf-9bdf5148b693.png)
**not** working as expected
![actual-follow](https://user-images.githubusercontent.com/5274181/37428470-92874c4a-2789-11e8-9d45-310e0a8727bf.png)
![noarchive](https://user-images.githubusercontent.com/5274181/37428396-617c6856-2789-11e8-8a06-4e1704c6e569.PNG)
working as expected (not accounting for the language)
![actual-archive](https://user-images.githubusercontent.com/5274181/37428579-ece750cc-2789-11e8-89e6-a7e95c9b8a8d.png)

Am I wrong here or is the `no-follow` inconsistent and therefore wrong here?

**Comment by sybrew** [comment]
Hi @GuardianMajor 

All the SEO bar data is as expected, so no changes need to be made.
The options enable a negative value, so I understand the confusion. Nevertheless, please take your time to fully understand and grasp what they do. Each of the robots options has a question mark next to it which links to Google's official documentation. I'm afraid I have nothing more to add to this subject.

I only see (and confirmed) an issue with the missing "and" at the `noarchive` option, and "but" is displayed instead. Which will be adjusted in the next version.

**Comment by GuardianMajor** [comment]
Thank you, I understand the SEO principles just fine and what they do, that's not my issue here. My efforts are to understand how TSF is applying them and the logic behind it.

You said before that the "apply to entire site" overrides the individual settings and applies to everything, correct? If so then there is indeed an inconsistency here and if you are not seeing a problem with it, then I need to understand why it is somehow exempt.

Given the above `no-follow` setting `pages` ***"aren't"*** being followed, while `posts` ***"are"*** shown to be followed, why the difference? If you don't see a problem then I need to understand why the difference is not a problem, you see? Knowing the concept of `no-follow` is not the issue here, just how TSF is handling/reporting it.

Given the above `no-archive` settings `posts` ***"aren't"*** being archived (which despite the language you said will be fixed is fine), while `pages` ***"are"*** being archived (which according to you applying to entire site should prevent this), you see? So again, the concept of `no-archive` is not the issue here, just how TSF is handling/reporting it and the difference.

So while you think you don't have anything else to add to the subject, I believe the question has merit and response explaining it  is necessary for clarification or at least appreciated to resolve what appears to be a inconsistent behavior of applying the chosen settings. None of my concerns result from lack of understanding the concept but rather trying to understand how the plugin is managing them; which is a responsible thing for a user to do, otherwise you may not use the software correctly. Fair?

**Comment by sybrew** [comment]
The SEO Bar takes all know data and reports on each individually.

```Markdown
# 1 = no archive.
# 0 = archive.
# X = some weird condition

# Data   = Where we got it.
# Value  = What we got.
# Eval   = What we use instead.
# Report = What we tell you.
```

_This list will be enormous on archives._

| Data | Value | Eval | Report |
| ---- | ---- | ---- | ---- |
| In-post | 0 | 0 | Page is archived. |
| SEO | 0 |  0 | - |
| WP |  0 | **0** | - |
| ---- | ---- | ---- | ---- |
| In-post | 1 | 1 | Page isn't archived. |
| SEO | 0 |  1 | - |
| WP |  0 | **1** | - |
| ---- | ---- | ---- | ---- |
| In-post | 0 | 0 | Page is archived. |
| SEO | 1 |  1 | But, your SEO settings tell us differently. |
| WP |  0 | **1** |  - |
| ---- | ---- | ---- | ---- |
| In-post | 0 | 0 | Page is archived. |
| SEO | 0 |  0 | - |
| WP |  X | **0** |  And your WP settings prevent us from changing this |
| ---- | ---- | ---- | ---- |
| In-post | 1 | 1 | Page isn't archived. |
| SEO | 0 |  0 | - |
| WP |  X  | **0** |  But your WP settings tell us differently |
| ---- | ---- | ---- | ---- |
| In-post | 1 | 1 | Page isn't archived. |
| SEO | 1 | 1 | And, your SEO settings tell us the same.  |
| WP |  0  | **1** |  But your WP settings tell us differently |
| ---- | ---- | ---- | ---- |
| In-post | 0 | 0 | Page is archived. |
| SEO | 1 |  1 | But, your SEO settings tell us differently. |
| WP |  X  | **0** |  But, your WP settings tell us differently |
| ---- | ---- | ---- | ---- |
| In-post | 1| 1 | Page isn't archived. |
| SEO | 1 |  1 | And, your SEO settings tell us the same. |
| WP |  X  | **0** |  But, your WP settings tell us differently |

In your case, the difference is that one has an in-post option enabled on the page, and the other hasn't.

![image](https://user-images.githubusercontent.com/7662236/37537242-397b8b14-294d-11e8-95d7-242948d9dbb5.png)

So, one says it's by default archived... but the website has discouraged archiving regardless.
And the other says it's by default not archiving... and the website has discouraged archiving also.

**Comment by GuardianMajor** [comment]
Ok, thank you for the detailed explanation, but I DO NOT have an in-post option set, you can see:

![image](https://user-images.githubusercontent.com/5274181/37540628-ef60fde4-2914-11e8-86dd-cf67606202c0.png)

but the SEO bar says this:

![image](https://user-images.githubusercontent.com/5274181/37540659-08743c92-2915-11e8-9cbe-8b94c4c52d7e.png)

Showing that it is allowed to archive, despite the previously shared setting applying to the entire site. I am sorry if you felt that I am discussing or attacking the verbatim, while clarity would improve it, as a programmer I have no issue with the and/but system and I am fine with it. My consideration is mostly about why it is saying that it is archiveable when by all indication it should not be.

Same here with the page, no in-page option set, you can see:

![image](https://user-images.githubusercontent.com/5274181/37540823-a449f90e-2915-11e8-8f85-ed875078f0f4.png)

but the SEO bar says this:

![image](https://user-images.githubusercontent.com/5274181/37540843-b946a78a-2915-11e8-9acf-27d3ea331cba.png)

I would be happy to be wrong if I am missing something but all indication is that since the `no-archive` is set site wide, it should not be allowing archiving on the posts or pages by default, since there are not in-post/page settings overriding this behavior as you can see. 

What is the most effective way for me to see what "robots.txt" is being served (for lack of a better word) since I believe that WP doesn't use the physical `robots.txt` (meaning if you FTP into the site, no actual robots.txt file) but rather generates it and serves it on the fly. I could be very wrong on this, it has been a while since I read this. But following the link you provide in the settings:

![image](https://user-images.githubusercontent.com/5274181/37541047-6b97245a-2916-11e8-9b62-cd820776f9ef.png)

displays the file that has this in it:

> User-agent: *
> Disallow: /wp-admin/
> Allow: /wp-admin/admin-ajax.php
> 
> Sitemap: https://majormike.us/sitemap.xml

As you see, quite basic and has little to no options in there, other than the option to add the sitemap adds that link at the end. Is something missing here? Clearly TSF and the SEO bar are reading things correctly from somewhere (just confused about the "discrepancy" for lack of a better word, on archiving). 

Also should be noted, in case it is relevant, the sitemap has been generated by another plugin for a long time, hence why TSF settings shows this:

![image](https://user-images.githubusercontent.com/5274181/37541312-63e9932c-2917-11e8-94ee-982fdc6a3456.png)

I doubt that's the issue but would disabling that and letting TSF handle it better or somehow related to this behavior? I am using `Google XML Sitemaps` by the way if that helps. I'd be happy to disable it and let TSF take over but wanted to get your feedback on it before making the change.

Thanks again and I appreciate your dedication, I don't want you to ever think that what I say about anything is criticism, I am a professional and don't bring ego or judgement in my interactions with other developers; I presume nothing so if the text medium lacks that intent, let me be clear, I appreciate your work and have nothing but respect. None of this is complaint or criticism, just trying to better my own understanding and if it leads to something better or improvements, by all means happy to be part of it.

**Comment by sybrew** [comment]
Hi @GuardianMajor 

The discrepancy and therefore the interpretation of the output thereof is well founded. I didn't know the data on the page mismatched the data used in the SEO Bar. My apologies for misunderstanding.

This is likely caused by an ID collision, often caused by third-party plugins built on WP 2.9 or lower. 
Is this only happening on that page?
You can test this by trying to match the "Robots Meta Settings" on another page, and then check if the SEO bar matches.

**About robots.txt**
It's virtual and outputted by WordPress, then overwritten on-the-fly by TSF. 
But, it can be overwritten completely through FTP. TSF detects this, and reports accordingly.

**About the sitemap**
TSF's sitemap doesn't use an index. So, if you have many pages some might be excluded to save space.
If you rely on the sitemap for analytical purposes, then I don't recommend switching. 
However, TSF's sitemap does listen to any related settings, this is making it more correct in output.

**About criticism**
It's very welcome, in fact! However, it's hard to pull information when there's so much formality. Talk to me as if I'm Siri, Google Assistant, or Alexa instead of a human and we'll likely get where we need to be much quicker 😄.

**Comment by GuardianMajor** [comment]
> The discrepancy and therefore the interpretation of the output thereof is well founded. I didn't know the data on the page mismatched the data used in the SEO Bar. My apologies for misunderstanding.

That's quite alright, I am patient and figured we'll get there. I am sorry I didn't include that portion of the screenshots earlier for you, I didn't even realize its usefulness to you until you posted yours earlier. My apologies for missing that.

> This is likely caused by an ID collision, often caused by third-party plugins built on WP 2.9 or lower.
Is this only happening on that page?
You can test this by trying to match the "Robots Meta Settings" on another page, and then check if the SEO bar matches.

To the best of my knowledge, I have no such plugin. I would happily give you a list of what I have, if it would help. I don't like to install too many plugins so everything serves a very real purpose and are among the highest rated, if not the top of their respective field. It happens on all pages and posts with regards to the `no-archive` so far as the behavior shown above.

I figured the robots.txt was virtually done and remembered that from long time ago but wasn't sure if I had missed an update on that and that's why I don't place a physical robots.txt file in there because I do not want it to interfere or collide with the internal workings. As you can see TSF is no reporting it, so it is not physically there and I have confirmed that through shell.

Ok, good then, I'll stick with the current sitemap solution as it has served me well and runs efficiently enough. I already have it tweaked in such a way that it provides the most efficient set of information and not too much spurious data that would bog it down.

I will bear that in mind, my apologies. The formality is for the sake of respect and also to ensure that the all the relevant information (or what I hope to be) is presented in as much consistent of a manner to aid in the process. I shall trim that to expedite :grin:

**Comment by sybrew** [comment]
Hi @GuardianMajor 

It's very difficult to simulate an ID collision, even if I'd try to copy your environment. Yet, I've seen and proven it many times, although I've been unable to reproduce it. Maybe it also has to do with running older/buggy server-level software, but I can only guess.

In any case, if you could try and create a new post replicating the erroneous one and see if that fixes it, that would be much appreciated 😄. If it does, delete the old post and update the permalink of the new one. 

Cheers!

**Comment by GuardianMajor** [comment]
Ok, I get that. For the record, my environment is not old and to the best of my knowledge bug free. I am running on a Linux server with Apache, PHP 7.2.3 and mySQL 5.5.59 and the latest WP 4.9.4 so not sure why those would be an issue.

As for the case you want me to test, I would be very happy to do it, but I have to be honest, I am not quite sure what you are asking. I wouldn't even know where to begin looking for the "offending post" if there is such a post (to delete and recreate it - if I understood you correctly) and there are new posts created at least twice a day which all show the same state.

If you have some tips for locating such a post, if it exists, that would be appreciated. I am having a hard time wrapping my mind around a colliding post ID to begin with given that WP doesn't generate the same ID for different posts by design. I have looked inside the DB in the raw and there are no posts that have the same ID. Plus, each post is treated as its own, right? so that would mean they should have their own properties applied individually, no?

Again, if I am not understanding your intent correctly, I would appreciate a clarification and hopefully some assist on how to achieve what you are looking for, then I will by all means be happy to hunt it down. Thoughts, procedures, tips or whatnot would be greatly appreciated so I don't presume anything. 

Thanks again 😃
