### ISSUE TITLE
Title Pixel Counter Inaccuracies

### ISSUE THREAD

**Issue by KimchaC** [sybrew/the-seo-framework#266]
Hi,

Perhaps this is a bug on my system, but the pixel counter is giving me an incorrect result.

For example when I enter this title: "This Is A Really, Really Long Title That Actually Barely Fits | On Some Site", the counter reports 643px.

But when I inspect a search result on google in Chrome and replace the title, I get a width of 592.89px.

I noticed that in the plugin, the hidden text that is used to measure the width has the following CSS:
```
body {

    font-family: -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Oxygen-Sans,Ubuntu,Cantarell,"Helvetica Neue",sans-serif;

}

.tsf-description-pixel-counter-shadow, .tsf-title-pixel-counter-shadow {

    font-size: 18px;

    font-weight: 600;

}
```
On google's title on the other hand I see...
```
.g, body, html, input, .std, h1 {

    font-family: arial,sans-serif;

}

#res h3 {

    font-size: 18px;

}
.sl, .r {

    font-weight: normal; // 400

}
```

And I was told that on Windows Chrome, google uses the Roboto font instead of arial. But I think the default for this pixel meter should be arial, because Roboto uses less pixels. When you optimize for arial, it is guaranteed to fit on all platforms.

So the adjustment that is needed is: "font-weight:400; font-family: arial, sans-serif;".

Once I make those adjustment inside the TSF CSS, the counter gives me the correct pixel width.

Please let me know if this is an issue on my side and I will do my best to help you debug this.

Greetings, Kim

**Comment by sybrew** [comment]
Oh wow, I knew it was `"arial,sans-serif"`... did I really leave that out?

You're also right about the font-weight. I believe I've missed those two crucial steps.

**Comment by KimchaC** [comment]
Awesome, thanks for fixing it!
