### ISSUE TITLE
Provide Option to Strip HTML <tags> From Titles

### ISSUE THREAD

**Issue by sybrew** [sybrew/the-seo-framework#270]
Follow up from #265 because the topic got out of hand.

@GuardianMajor wrote:

> As requested per our discussion in issue #138 where you wanted a simple request to be considered as a new feature.
> 
> A quick review, the ability to strip html tags sitewide with an option with a per post override for those times when you want literal tags to appear in the title of the post's page, the title of the shared items while retaining the formatting for the site front-end.
> 
> Thank you.

Suggested option name:
* **Strip HTML from autogenerated titles?** [?]

Suggested [?] tooltip content:
* **This will convert valid HTML, like `<span>example title</span>`, to `example title` in all autogenerated titles.**

Disabled by default.

Note to self: [Articles](https://theseoframework.com/extensions/articles/) should read this option.

**Comment by sybrew** [comment]
#202 needs to be resolved first.

**Comment by sybrew** [comment]
Here's a dirty workaround filter that likely won't cause any issues:
```php
add_filter( 'the_seo_framework_pro_add_title', function( $title ) {
	return wp_strip_all_tags( $title );
}, 0 );
```

**Comment by sybrew** [comment]
With the upcoming commit, we can move this to 3.1.0

**Comment by sybrew** [comment]
In commit 3e7cfe3404bf9632a7b67672dac318ec47f90f16 we've implement the `single_post_title` filter, brought with WordPress, which is used in the default WordPress title rendering functions.

By default, WordPress runs PHP's SPL `strip_tags()` function over it:
https://github.com/WordPress/WordPress/blob/4.9.7/wp-includes/default-filters.php#L110-L114

**I will not remove this filter.** It makes sure the titles are automatically compatible with anything thrown at it. In fact, this behavior was already present on terms before this update.

But, it makes this option moot, and it needs to be reversed.

**Comment by GuardianMajor** [comment]
@sybrew Thank you for the hard work my friend and glad to see it coming. Just to make sure I understand, since this will now rely on the default behavior which strips the tags already, this means that this feature now behave by default as it does in the WP core, correct? Which you are right, would indeed make it unnecessary to have this additional setting. However, if someone still wanted to include tags in their title for say articles that are regarding coding, they can just escape them right?

**Comment by sybrew** [comment]
Exactly, to all remarks 😄

**Comment by GuardianMajor** [comment]
❤️ Beautiful, you are awesome as always my friend, thank you.

**Comment by GuardianMajor** [comment]
I wanted to say thank you and kudos on the latest release, it looks wonderful and works excellent as always my friend, well done.

I did just want to say something about a little feature issue but I will open a ticket for that to keep it organized. Just wanted to confirm this feature is working as expected and thank you.

For the sake of future questions, just wanted to confirm that if you DO want the literal tags showing up, meaning say an article called: "How to use the \<embed\> tag properly" you can achieve this by simply escaping the `<` as `\<` and `>` as `\>` and you will achieve this, correct and nothing is stripped?

**Comment by sybrew** [comment]
Backslashes are used to handle functional characters as-is in code, they shouldn't be used to "hack" the system, and thus we remove them from the real output when deemed unnecessary. 

With this, backslashes are unpredictable, too; we'll have to intricately perform checks on where whom has introduced what.

In any case, you'll have to write the HTML entities if you want to show the tags, with the escaping enabled, instead:
```
"&amp;"  = "&" (ampersand)
"&gt;"  = ">" (greater than)
"&lt;"  = "<" (less than)
"&#92;" = "\" (or bsol, backward solidus)
```

**Pro tip:** use `&amp;` to escape entities, so to show examples:
```
"&amp;gt;" => "&gt;"
```
Example: &amp;gt;

**Comment by GuardianMajor** [comment]
You are absolutely right my friend, I have no idea why I said such a dumb thing, especially that I don't do it like that and exactly as you noted. I am embarrassed by a momentary thought lapse and have no idea what was running in my head when I said that, I should have known better. Please accept my apologies and know that I thank you for kindly replying to such a completely dumb remark, I can't even justify it, don't know what would motivate me to say something so stupid as it is not how I do it anyway. ☺️
