### ISSUE TITLE
Tooltips are not working in IE11 since 3.0.4

### ISSUE THREAD

**Issue by LeBaux** [sybrew/the-seo-framework#274]
As seen on [WordPress Forums](https://wordpress.org/support/topic/seo-seems-inactivated/), version 3.0.4 (upgrading from 3.0.3) introduced a styling issue with popup tooltips when hovering over SEO bar. Observable in Internet Explorer 11 (other browsers were not tested). Here is a [comparison video](https://i.imgur.com/nrZhKPJ.mp4).

**Comment by sybrew** [comment]
Nothing is working in IE11 😅, the final conversion for release in Babel didn't change arrow functions correctly.
