### ISSUE TITLE
Custom metadata for media couldn’t be saved

### ISSUE THREAD

**Issue by LeBaux** [sybrew/the-seo-framework#278]
Issues is affecting both 3.0.4 and 3.0.5. To reproduce, try entering & saving custom metadata in TSF metabox belonging to any media file, under **Edit more details**. [Demonstration](https://streamable.com/8cfxs). Please inform the [reporting user](https://wordpress.org/support/topic/media-seo-settings/), after the issue is fixed.

**Comment by sybrew** [comment]
I forgot that by adding support for ***all*** posts types, attachments were included.

There are some attachment exclusions, and I'll investigate the cause.
I'm yet uncertain if `wp_update_attachment_metadata()` should exclusively be used when dealing with attachments.

**Comment by sybrew** [comment]
[It seemingly affects other plugins](https://wordpress.org/support/topic/pictures-in-media-library/#post-10096684), too.

**Comment by crimann** [comment]
Hey Sybre,
I'm pretty sure the problem is that you used `wp_enqueue_media()` without any `$args` in '/inc/classes/admin-init.class.php'. That way, images uploaded are not getting attached to the proper posts which can break other plugins.

If you replace `\wp_enqueue_media();` on line 144 with something like this, it works:

`global $post;
$args = array( 'post' => $post->ID );
\wp_enqueue_media( $args );`

Would love if you could test this and looking forward to your feedback!

**Comment by sybrew** [comment]
Thanks for looking into this @crimann! 

From [wp_enqueue_media()](https://developer.wordpress.org/reference/functions/wp_enqueue_media/):
```php
    if ( isset( $args['post'] ) ) {
        $post = get_post( $args['post'] );
        $settings['post'] = array(
            'id' => $post->ID,
            'nonce' => wp_create_nonce( 'update-post_' . $post->ID ),
        );
 
        $thumbnail_support = current_theme_supports( 'post-thumbnails', $post->post_type ) && post_type_supports( $post->post_type, 'thumbnail' );
        if ( ! $thumbnail_support && 'attachment' === $post->post_type && $post->post_mime_type ) {
            if ( wp_attachment_is( 'audio', $post ) ) {
                $thumbnail_support = post_type_supports( 'attachment:audio', 'thumbnail' ) || current_theme_supports( 'post-thumbnails', 'attachment:audio' );
            } elseif ( wp_attachment_is( 'video', $post ) ) {
                $thumbnail_support = post_type_supports( 'attachment:video', 'thumbnail' ) || current_theme_supports( 'post-thumbnails', 'attachment:video' );
            }
        }
 
        if ( $thumbnail_support ) {
            $featured_image_id = get_post_meta( $post->ID, '_thumbnail_id', true );
            $settings['post']['featuredImageId'] = $featured_image_id ? $featured_image_id : -1;
        }
    }
```

What's most important here is that a nonce is created. Which is outputted via: 
```js
var _wpMediaViewsL10n.settings.nonce
```

This will only happen when the aforementioned suggestion is implemented.

**Comment by michaelezra** [comment]
Thank you for looking into this, great teamwork:)!
