### ISSUE TITLE
Search Canonical URL points to first page

### ISSUE THREAD

**Issue by sybrew** [sybrew/the-seo-framework#28]
From [MassimoD's bug report](https://wordpress.org/support/topic/canonical-url-in-search-results/):

When performing a search action on any WordPress installation, by default, the canonical URL will point to the first post/page result found.

This is not beneficial when the user wants Search Pages to be indexed by Search Engines. But the feature (as it should be) wasn't either.

Also, allowing Search Result pages to be indexed is a major concern for SEO issues: **Duplicated Content.**
Finding items throughout the site should never be handled through the sitemap or local search, but should instead be handled through WordPress Tags and Categories.

Therefore, this bug (it wasn't intended to be this way), can actually be seen as a positive feature.

In 2.6.5 it was promised to always point to the home page. Such alterations were assumed, but not made.

I need feedback on this one. And I possibly think this can only be conveniently solved by adding options.
See https://github.com/sybrew/the-seo-framework/issues/20 for this more focused, but related, feature request.

I know, many topic labels have been added, but this "bug" covers a wide spectrum.

**Comment by kevinlisota** [comment]
@sybrew Can you tell me where in the plugin this is occuring? When I activate SEO Framework, I see a few things happening

1) search.php - title is rewritten to the home page title. canonical is rewritten to the first search result
2) 404.php - title is rewritten to the home page title, canonical is rewritten to the home page

This is a very significant issue for Google Analytics users, and it is completely polluting our Google Analytics data.

Google Analytics tracks pageviews by URL and page title. Most people find working with the friendly page title easier than working with URLs in reports.

This plugin is causing all 404's and search results to be registered in analytics as a pageview of the home page, which is wrong. We have high traffic, and a somewhat significant amount of both 404s and search queries. Those need to be tracked under their own title. In the case of a search result page, we want the title to show the search query string. That way we can measure search queries.

SEO can and should be addressed on these pages with noindex directives.

Also, the canonical usage is incorrect. If you make one page available at multiple URLs, the canonical URL should be the same on all of them referring back to the "master" page. But all of these pages would have duplicate content. In this case, you have a page with no duplicate content pointing to a different canonical. That isn't correct.

Can you point me to the place in your plugin where you are making these changes? I will have to fix quickly, as our analytics data is getting all messed up based on this.

**Comment by sybrew** [comment]
Hi @kevinlisota 

> Can you tell me where in the plugin this is occuring?

I'm assuming "this" == "topic title". From a quick glance, the issue is happening [here](https://github.com/sybrew/the-seo-framework/blob/7d8b507b6e5f02bf165cda1cbf532b318453850d/inc/classes/generate-url.class.php#L336), although I don't know why. I have yet to check into this issue.

> I see a few things happening [title issues]:

If the title is output incorrectly, then I'm afraid the theme is interfering. 
Could you confirm this by checking the 404.php and search.php template files?

> This plugin is causing all 404's and search results to be registered in analytics as a pageview of the home page, which is wrong.

This is a templating Title issue, not the plugin's issue. If the plugin can't write 404 titles, then the template doesn't allow the plugin to write the titles as per de facto standard.

> Also, the canonical usage is incorrect. If you make one page available at multiple URLs, the canonical URL should be the same on all of them referring back to the "master" page. 

How would one make a page available through multiple URLs? This isn't WordPress standard.
If you're talking about Post objects having multiple categories, then this is taken care of.

> Can you point me to the place in your plugin where you are making these changes?

I believe the issues you're facing aren't within this plugin. Instead, I believe they are superficial as to where this plugin tries to interact, but can't circumstantially do correctly. It's a WordPress API issue.

Please, run this:
https://wordpress.org/plugins/theme-check/

**Comment by kevinlisota** [comment]
Theme check doesn't reveal anything, other than I like to use PHP short tags. We don't use a 3rd party theme. It is created by us.

Our theme has title-tag support turned on, and no theme templates actually output the title tag into `wp_head`. Both the 404.php and search.php templates use a base template that applies to 100% of our pages for the header. The header simply outputs `<?php wp_head(); ?>` The first element of `wp_head` is the title tag generated by core.

When SEO Framework is deactivated, the 404 page has a title tag of "page not found" and search has a title tag of "search results for %searchterm%'. Activating SEO Framework changes both of these title tags to the home page title. I see the generate_title function and will attempt to debug there before resorting to the filters, but something is not right here.

On the canonical issue, even WordPress can present duplicate content at two URLs. For example, the pretty permalink, pretty permalink with query params, ugly permlink. In all of those instances, the canonical says which is the "official" one for search engines. In our case, we also sometimes syndicate our content to other sites. The canonical is set on the other site to point back to us as the official article.

In all of these cases, the content of the page is either identical, or extremely similar. In this case, you are setting the canonical URL on search results page to point to a page that has completely different content than the page you are on. Same thing for a 404 page. The 404 page has its own content which is completely unrelated to the homepage. 

I don't think canonical URL makes sense in either case. The canonical URL for the search results page is the search results page (or possibly even none since it isn't indexed). The canonical URL for the 404 page is also not the homepage.

If you visit a 404 page on google.com or microsoft.com, you'll notice there are no canonical URLs present.

**Comment by kevinlisota** [comment]
Here is what I have found so far. There are two lines in `generate_title`
```
			$title = $this->get_the_404_title( $title );
			$title = $this->get_the_search_title( $title, false );
```
On single pages, archives, categories, tags, etc, they are hitting the `generate_title` function. However, on 404 and search, they are never entering this function at all. I did a simple debug to echo a value in that function, and it doesn't appear on those pages.

Now I need to figure out why 404/search are not using `generate_title`

**Comment by sybrew** [comment]
@kevinlisota 

#### Canonical URL issue

> If you visit a 404 page on google.com or microsoft.com, you'll notice there are no canonical URLs present.

That's actually very clever! I've created an issue for that (linked above this comment).

> In this case, you are setting the canonical URL on search results page to point to a page that has completely different content than the page you are on. 

That's what this topic describes, and it indeed needs to be addressed.

#### Title issue:

Please don't put all the work on yourself, if there's an issue with the plugin, it's my task to resolve it 😄 

We've covered that the theme might not be the issue, but now I suspect there's a WP_Query issue.

Nevertheless, could you please send me a ZIP of the theme you're using on my [contact page](https://theseoframework.com/contact/)? Include a list of plugins you're using too, and I'll try to replicate the issues you're facing.

Thank you so much!

**Comment by kevinlisota** [comment]
I can probably save you a few steps. I instrumented your code for building titles to find out why 404 & search were being handled differently.

The function `build_title` checks if the following two conditions are true. If so, it generates the home page title.

`( $this->is_front_page_by_id( $args['term_id'] ) && ! $this->is_archive() )`

A 404 page and search results page are not archives, we know that, so it it the `is_front_page_by_id` that is the culprit. Obviously that function thinks search and 404 are the front page, but they're not.

That's as far as I've gotten tonight. Will look at it more tomorrow. Happy to hear a suggested fix here.

**Comment by sybrew** [comment]
@kevinlisota You're spot on! Awesome work 😄

**Comment by sybrew** [comment]
Extension label was meant for #20

**Comment by sybrew** [comment]
The issue is that the function is a god-function. It should be split into external calls (i.e. we don't know the query), and title generation calls (i.e. we know the query).

**Comment by sybrew** [comment]
Reopening since there's still code debt for the Title and URL generation god functions.

**Comment by sybrew** [comment]
The refactorization will take about two weeks; which, with far more pressing matters, is impracticable for a sustainable release cycle. I've moved this to a future release.

**Comment by kevinlisota** [comment]
Looks like you are still working on this. I just tested this version of the plugin: 2.9.3-RC1-2017.06.11.0 and here are the issues on is_404 and is_search.

On 404 pages, the `<title>` tag is still being rewritten to use the homepage title. The default in WordPress for this title is "Page not found" which is the correct result, unless someone wants to customize it.

On search results pages, there are a few issues. We use the 's' query string, not pretty permalinks like /search/. I believe most sites use the 's' query string.

Here is a sample URL: http://www.mystie.com/?s=search+term. SEO Framework outputs the following:
- `<title>` tag rewritten to homepage title. The default in WordPress is good, which is "Search Results for 'search term'"
- Adds a canonical of http://www.mysite.com/search/search+term/
- Adds an og url of https://www.geekwire.com/search/search+term/

Search results should not have a canonical or og url, and shouldn't show pretty permalinks in this case. Since the possible search terms are infinite, this can create an infinite number of canonical and open graph URLs. Looking at a few sites around the web like Moz, Google, Microsoft, they do not set canonical URLs on search results pages.

**Comment by sybrew** [comment]
Hi @kevinlisota,

---

#### 404 query when home page is a blog
You're right about the 404 issue, I'll look at it ASAP. The archive pages should've been fixed, at least.

---

#### Search canonical URL

You do use `/search/`, WordPress just doesn't do it.

I believe this is a bug within WordPress, of which I've taken the first steps towards resolving within TSF.

More on this can be found here: 
https://core.trac.wordpress.org/ticket/40082#comment:5

If you've selected pretty permalinks, you should embrace them too 😄!

#### Infinite Canonical URLs

I don't see an issue here... There are an infinite amount of titles within Google too.
Even more so, without a Canonical URL, there would be the same number (i.e. infinite) of non-annotated Canonical URLs as well. It doesn't matter as long as the URL is correct.

Aside from it not having any effect, it does have a plus side:
If you get a couple of backlinks towards your search pages (although very unlikely...), then it's nice to have a single point of reference.

Please note that the huge sites you're referring to are huge because they were in the right place at the right time. Not because of SEO. 
Now, in any case, they don't need SEO, they're thriving on backlinks.

**Comment by kevinlisota** [comment]
Disagree on using pretty permalinks for search terms. If you are serious about analyzing your search trends on Google Analytics, the search query string is the way to go. Analytics has built-in support for it. Without it, you need to add custom scripts to append the search terms. See here

https://support.google.com/analytics/answer/1012264?hl=en&ref_topic=1031951

That is more work than is necessary for most users, and the ability to analyze search terms is more important than a "nice" URL. My advice to all WordPress users who use Google Analytics is to stick with the query string for search terms which works well without modification in Google Analytics.

In addition, pretty permalinks potentially imply a crawlable structure/URL to search engines, whether Google, Bing or Facebook. There is nothing good about having crawlers index or even crawl search results in wordpress. On low-traffic sites, it may not matter, but on sites with any level of appreciable traffic, this is a major performance hit to the server. WordPress search has some of the slowest/least performant MySQL queries in all of WordPress and consistent crawling can hobble a server's database. We've personally experienced this exact issue.

Noindex doesn't help, as you also need a nofollow to stop the crawling. URL parameters for search results are far easier. You can simply use Google search console or Bing webmaster tools to tell them about that one parameter and the whole issue goes away.

**Comment by sybrew** [comment]
Hi @kevinlisota 

I've never heard of Analytics reading Canonical URLs...

So, I conducted a little test with Real Time data, and this is exactly what it shows:
![image](https://user-images.githubusercontent.com/7662236/27273757-c6fbd7e8-54d0-11e7-997b-42abc266d245.png)

```
Address:   /?s=wordpress
Canonical: /search/wordpress/
```

Because of this, unless you truly use 301 redirects, there's no need to adjust the Site Search Tracking settings.

---

#### But, I do index my Search Pages...

Excellent and valid point.

In that or any other case, it would be a nice feature to implement Google Analytics that does something per Google's recommendation:
```
Address: https://example.com/search/users+query/
Script: `analytics.js: ga('send', 'pageview', '/search/users+query/?s=users+query');`
```

This calls for adjustments and future enhancements. And I already have proper Google Analytics implementation planned as a free extension.

But first and foremost, we shouldn't keep ourselves back to basics when it's sub-optimal.

#### In the meantime...

We could set up an option that allows the user to pick a pretty or ugly Canonical URL for Search Pages.
I think that would work out for you 😄, correct? 

---

#### Does it affect my site's performance?

If a mere crawler affects your site's performance, then your server is setup sub-optimal. If you're experiencing issues like those, it might be helpful to setup object caching, so the slow SQL query doesn't get repeated.

They shouldn't DoS your website, and they generally won't try to get URLs that aren't linked to. That the Search Query implies another URL does ask for a single extra request, but that's it.... this doesn't mean the crawl rate will double.

Also, both `noindex` and `nofollow` can be set for the search results pages within the Robots Meta Settings meta box.

**Comment by sybrew** [comment]
@kevinlisota I've created a little plugin that will fix the Google Analytics script JIT (just in time):
https://gist.github.com/sybrew/ab5553dd8a06e73794680c4a2cc24661

I'm currently live testing it on https://theseoframework.com/search/
Will notice if it's working correctly within 3 days.

**Comment by sybrew** [comment]
I've updated the script, and it's correctly working.
It's GPLv3, so feel free to use it in your GPLv2+ code or prompt other GA plugin authors to take notice.

**Comment by erikdemarco** [comment]
There should be a feature to canonical the same search query.

For example this two url gives the exact page but with different url:
http://www.mysite.com/search/search+term/
http://www.mysite.com/search/search%20term/
