### ISSUE TITLE
Can TSF Address Google Structured Data Errors/Warnings?

### ISSUE THREAD

**Issue by GuardianMajor** [sybrew/the-seo-framework#286]
When running the Google Structured Data Testing Tool, I get a set of 2 Errors and 2 Warnings always and for every single post and page on the site. (It was referenced here #285)

![image](https://user-images.githubusercontent.com/5274181/37857323-62aafbf4-2eb7-11e8-8195-fb3363b68d6d.png)

Drilling down, you see these are the complaints it has:

![image](https://user-images.githubusercontent.com/5274181/37857360-9a1e6972-2eb7-11e8-968e-39d2cd53ccfd.png)

So my questions are:

1) For the `image` why isn't the "social image" that is given to the post being placed there? Can't TSF process and pass that value?

2) For the `publisher` why isn't the author or the site being placed here? Or better yet the Google+ identity that is in the settings but doesn't appear on any of the site's meta (another issue I will address separately) or any of the available `presence` information.

3) For the `dateModified` why isn't the post's publish time not being placed here? Wouldn't that value which is available and configured in the settings resolve this?

4) For the `mainEntityOfPage` why isn't the site's identity, author or pretty much any of the available information being passed on? Wouldn't any number of available values resolve this?

I tried to keep it simple, if you need more let me know. TIA.

**Comment by GuardianMajor** [comment]
@sybrew 

1. I see, so unless you put a featured image, that will always show up empty? I was going to ask if maybe we can have an option to use the social image instead of featured, but since you said it will come in Articles, I will wait for that. I do have Articles installed but to the best of my understanding it was to handle AMP/Non-AMP parity, but it would be a welcome resolution, thank you.

2. I see, but about cases where a Person is publishing on behalf of an Organization, can that be provided as an option for the Person schema to include (if any) a `publisher` to associate as well? The reason I ask is that if the scheme is set to Person, then the validation tool should know that and ignore that, correct? So if it is still parsing it, perhaps we can provide the organization on whose behalf a Person is publishing to that or just add the Person (as say in the case of a self-publisher) to that instead. 

3. I understand, you are correct but even when a post is not "modified" per se, the mere act of publishing the post, the modified date =  publish date, now if the post is later modified, then the two would differ accordingly. Can we make that adjustment to avoid their overly narrow view of this for the benefit of the users? I appreciate hearing it will come for non-AMP in the next update, thank you.

4. I appreciate it, take your time, just let me know what I can do (if anything) to help you.

I read the link you posted, forgive me for having initially missed this and thank you. There is a logo, as stated, site icon as well but the only thing missing is the Organization schema, but I am hoping my above argument for providing the support yourself will be considered. Thank you again.

**Comment by sybrew** [comment]
Hi @GuardianMajor 

Foreword: The extension will remain dormant if the site represents a Person, according to the **"Schema Settings -> Presence -> About this website"** settings.

1. Yes. This will change, as per your suggestion.
2. It can not, the specification doesn't allow it. Articles must be factual: A person may be but is likely opinionated. The validation tool is helpful but isn't tweaked to differentiate AMP from non-AMP. Ergo the errors.
3. Structured Data is meant for bots, not for users. Them being the same indicate that the post hasn't changed since the publication. What bots do with it to provide information to the users, is ultimately up to them. Adding additional parameters to this will make the program very difficult to understand.
4. I've investigated it and I can't find any issues. Make sure you're running the latest version of TSF and TSFEM. Also, do you mind sharing the page with erroneous information? Cheers!

The logo can be set via  **"Schema Settings -> Presence -> Website logo
"**. Or via the Customizer, provided your theme supports it.

**Comment by GuardianMajor** [comment]
2. That is not true at all, while the site is run by say New York Times, it is not writing the article, a person is and they may or not be opinionated but that's the very nature of content. If you were to have a publication called Sybrew Times, you are therefore opinionated and not factual in your publication?

3. I understand that, but to avoid errors for missing fields, until there is a value to for modified, publish can be a legitimate placeholder and it makes the information no more difficult than when there is publish and modified times? How is having both fields fulfilled confusing?

4. I have the latest published version of both, so that can't be the issue. It is the same site as I emailed you before but you can check here: [majormike.us](https://majormike.us) and the logo is set in presence website logo and also through WP/theme's system as well.

**Comment by sybrew** [comment]
Hi @GuardianMajor 

For 2, I'm simply propagating what's provided, and I'm abiding to the standard. You can combat this on [Schema.org's GitHub page](https://github.com/schemaorg/schemaorg).

For 3. and 4., I was under the impression you were using the Articles extension.
Instead, we're discussing why **your theme is doing these things...** You should forward this to the theme author. Therefore, I have nothing more to add than to recommend using the Articles extension, which does all these things according to specification.

Cheers!

**Comment by GuardianMajor** [comment]
@sybrew 

You misunderstood me, I am not combating you, just making the case for providing that on our end to bridge the gap until such time as they make it part of the "standard" if you will, or at least have the option for the user to make that choice, even if you choose to honor it strictly by default.

I AM using the Articles extension. I never said my theme is doing anything. I simply stated in response to your statement that those information are set both within the plugin and wordpress per "Or via the Customizer, provided your theme supports it." It has nothing to do with the theme and I wasn't discussing any such thing.
