### ISSUE TITLE
Opengraph 'conflict' override

### ISSUE THREAD

**Issue by useyourblinker** [sybrew/the-seo-framework#291]
I can't seem to find anyone else having this issue.

My theme (OceanWP) has recently started including OpenGraph tags in it.

I have disabled the feature, but it seems as though (even though the theme is not outputting OpenGraph), The SEO Framework insists the following:

Note: Another Open Graph plugin has been detected.

(this is right below where you check the box for 'Output Open Graph meta tags?')

Despite that the OG tags are turned off in the theme, The SEO Framework seems to no longer output meta settings in all cases.

Is there any way to override this when we are confident that the page will not have two OG tags?

![image](https://user-images.githubusercontent.com/29338083/38001084-ed45e622-31f8-11e8-83ba-0f20f9b5829d.png)

See setting in OceanWP (which is enabled by default when upgrading to the latest version - but when disabled, SEO Framework still no longer outputs og: tags)

![image](https://user-images.githubusercontent.com/29338083/38001113-0f436772-31f9-11e8-8ffe-2cc7e1f330f3.png)

Update2: Here is the example website. I have removed and re-added SEO Framework, Reset settings, and am using no cache of any kind: https://doakengineeringdesignpc.com/ 

Update: The developer of OceanWP is going to disable OpenGraph tags by default on his theme now. There is no longer a conflict, but The SEO Framework still lists the error AND outputs no OG: tags. I am baffled.

**Comment by useyourblinker** [comment]
Just to add - all that the developer of OceanWP has done is make OpenGraph be 'disabled' by default on that theme (it is only a checkbox).

This issue is because even after 'disabling' OpenGraph on this theme, TSF does not seem to start producing og: tags on its own.

This does not occur on other websites with the same theme, as long as OpenGraph is disabled for that theme. I don't know if this is true for other OpenGraph conflicts (I'm looking at you JetPack), but there doesn't seem to be any way to 'reset' the situation. I am happy to give wp-admin access if needed to look at the issue.

**Comment by sybrew** [comment]
Hi @useyourblinker 

It's not OceanWP that's causing this issue. Themes aren't tested for this in TSF.

These are the plugins that might conflict:
https://github.com/sybrew/the-seo-framework/blob/366c157e759ebb5c73da27908f0120033598566f/inc/classes/detect.class.php#L152-L168

If there's one listed there that you use but find extraneous, let me know!

**Comment by useyourblinker** [comment]
@sybrew  This is fantastic. I will add these Plug-Ins to our list.

We have one developer who loves using 'Header and Footer' (now called 'Head, Footer, and Post Injections'). Disabling this plugin and waiting a bit of time has resolved the issue.

OceanWP was definitely not the issue here, so thank you for clarifying that. I should have started this and kept it on wordpress.org I think due to it apparently being an individual issue.

But if any of those Plugins are in there - I will note that they can conflict. Thank you. We have many sites that use Header and Footer, so we will substitute other things.

**Comment by sybrew** [comment]
No problem 👍

If you wish to continue using "Head, Footer, and Post Injections", I suggest filtering it out of the conflicting plugin list.

This should work:
```php
add_filter( 'the_seo_framework_conflicting_plugins', function( $plugins ) {
	unset( $plugins['open_graph']['Header and Footer'] );
	return $plugins;
} );
```

Continued: https://github.com/sybrew/the-seo-framework/issues/295
