### ISSUE TITLE
Override Breadcrumb Titles

### ISSUE THREAD

**Issue by KimchaC** [sybrew/the-seo-framework#292]
Hi,

Is there a way to override SEO Framework's breadcrumbs?

For many of my pages it would make sense to show a shorter breadcrumb rather than the full title. 

Thanks, Kim

**Comment by sybrew** [comment]
Hi @KimchaC 

Could you exemplify what you wish?

e.g.:
1. This is the breadcrumb I have now.
2. This is the breadcrumb I want.

Thanks!

**Comment by KimchaC** [comment]
Sure,

1. Blog > Citizenship By Investment: All You need to know...
2. Blog > Citizenship By Investment

Essentially, the breadcrumb is a replacement for the page path. But just like we are discouraged to put long page paths, I think the breadcrumbs should be short.

And reusing the title in the breadcrumb does not really help, since it is just duplication of content. I would rather put a few short keywords in there.

**Comment by sybrew** [comment]
Hi @KimchaC 

Who recommends not using long page paths? [Google](https://support.google.com/webmasters/answer/76329?hl=en) recommends just trimming unnecessary parameters, like `/?queryparameters=[...]`.

When the "breadcrumb" is too long, Google simply trims where it deems necessary:
![image](https://user-images.githubusercontent.com/7662236/38470782-13ce48b6-3b68-11e8-9e24-bd4034122fae.png)

When you remove structural data, you're obscuring information that could be helpful to both the potential visitor and the search engine.

Note that the breadcrumb path is simply a replacement for a non-user-friendly URL.
So, A becomes B:
```
A_raw:  https://example.com/books/authors/stephen-king/the-green-mile/
B_raw:  https://example.com > Books > Authors > Stephen King > The Green Mile

A_trim: https://example.com/.../stephen-king/the-green-mile/
B_trim: https://example.com > ... > Stephen King > The Green Mile
```

This is why the page title is included, so you know the URL doesn't lead to something else.
As such, removing the page name from the breadcrumb isn't even possible at Google Search.

**Comment by KimchaC** [comment]
According to Brian Dean of Backlinko "An industry study found that short URLs rank better in Google.

https://github.com/sybrew/the-seo-framework/issues/292#issuecomment-379570338

I agree with you, but by including the page title instead of the URL, we are right now just duplicating information.

Take a look at the example from google in the image you posted. The breadcrumb is a different way of phrasing the title instead of the same.

**Comment by sybrew** [comment]
I invite a developer to create a free extension that allows users to choose the "breadcrumb" title via a dropdown-selection field.

The fields should ask which breadcrumb title to use:
1. SEO Title
2. Page Title

They may be auto-populated via JavaScript, to give a clear example.

Issue #254 should be resolved first (always enabling breadcrumbs). So the extension should be marked for TSF3.1 or later.

**Comment by TomasLess** [comment]
Hi @sybrew,

what I think is that we always should take into account plugin users first. And if we see that people asks for this feature as I do, there is no reason to "fight" against it. Personally, I would even pay for this option.

Your solution is very weak, since Page titles are used across different locations and custom/dynamic fields and simply we need customization for the breadcrumb.

There can be these options:
1. SEO Title
2. Page Title
3. Custom Title

> "I highly discourage opting in for a custom breadcrumb-title-entry, as the data won't necessarily resemble something from the page."
Come on, if someone choose the third option he definitely understands, and there is no problem to have default Page/SEO title and rewrite it only in case Custom Title is filled in.

Thank you.

**Comment by sybrew** [comment]
Not so long ago I added [more in-post tabs](https://github.com/sybrew/The-SEO-Framework-Extension-Manager/blob/1.5.2/inc/classes/inpostgui.class.php#L134-L165), so this feature shouldn't be an issue, provided I can hook into the data.

Keep in mind that this isn't a matter of will, but of time. 
I'm going through all that needs to be done, this will be shown the light of day too.

**Comment by TomasLess** [comment]
Thanks, it would be perfect to have this feature. I would kindly recommend to create public roadmap e.g., in trello with upvotes. You have the ability to do very well, since you've developed and excellent plugin so far! 👍

**Comment by sybrew** [comment]
This issue is tied closely to #276. As such, I'm closing this and suggest moving forward there.
