### ISSUE TITLE
Wrong links

### ISSUE THREAD

**Issue by vralle** [sybrew/the-seo-framework#294]
Hi!
When Edit the post, Error 404 for next scripts:
`https://site.dev/app/plugins/the-seo-framework-extension-manager/extensionsfreefocustrunk/lib/js/tsfem-focus-inpost.js?ver=1.0.0`
`https://site.dev/app/plugins/the-seo-framework-extension-manager/extensionsfreefocustrunk/lib/css/tsfem-focus-inpost.css?ver=1.0.0`

WP 4.9.5
```
define('WP_SITEURL', 'https://site.dev/wp');
define('WP_HOME', 'https://site.dev');
define('FORCE_SSL_ADMIN', true);
define('FORCE_SSL_LOGIN', true);
define('CONTENT_DIR', '/app');
define('WP_CONTENT_DIR', dirname(__DIR__) . '/app');
define('WP_CONTENT_URL', WP_HOME . '/app');
/* Multisite */
define('WP_ALLOW_MULTISITE', true);
define('MULTISITE', true);
define('SUBDOMAIN_INSTALL', true);
define('DOMAIN_CURRENT_SITE', 'site.dev');
define('PATH_CURRENT_SITE', '/');
define('SITE_ID_CURRENT_SITE', 1);
define('BLOG_ID_CURRENT_SITE', 1);
define('WP_DEBUG', true);
```
The SEO Framework 3.0.5
The SEO Framework - Extension Manager 1.5

**Comment by sybrew** [comment]
Hi @vralle ,

Is the site running on a Windows installation?

Cheers :)

**Comment by sybrew** [comment]
Verified to be a PHP on Windows issue.
