### ISSUE TITLE
the_seo_framework_ogimage_output filter

### ISSUE THREAD

**Issue by janeks** [sybrew/the-seo-framework#3]
Can we have a filter that won't output `meta property="og:image"`

For a Facebook, image needs to have width and height properties and it's much easier to replace the default output with custom one. 

The even better option would be to have a filter to disable the whole 'og' section. 

For dynamic pages the  `og` properties section has to be custom build and the main issue I'm having is to disable default output. The `the_seo_framework_output_canonical` filter works as expected. The other filters do not follow this pattern.

**Comment by sybrew** [comment]
Hi janeks,

There's an option to disable the og_image output, you can overwrite it with the settings filter.
The option is named: `og_tags`.

Facebook doesn't require the width and height to be set, they auto-detect this. 
Please see https://developers.facebook.com/docs/sharing/opengraph/object-properties
https://developers.facebook.com/docs/sharing/webmasters#images

They do advice an aspect ratio of 1.91:1 and only accept a maximum of 1500px. The latter is taken care of automatically (unless a filter is used).

The reason it's not disabled when no image is found is because an og:image tag has to be set to abide to their protocol, and then it may be empty.
Multiple og:image tags are allowed, so the empty one may still be present without an issue.

In version 2.7.0 an image overhaul is planned, I'll be sure to be more consistent with such functionality as you've suggested.

I hope this clears things up!

**Comment by janeks** [comment]
Deactivating output is not the option. I'll look into `og_tags`

Facebook does not require w x h but when you click on Facebook link, you won't see an image on the first share. Only when you have image dimensions you will. That's why Yoast SEO added this option. 

"When content is shared for the first time, the Facebook crawler will scrape and cache the metadata from the URL shared. The crawler has to see an image at least once before it can be rendered. This means that the first person who shares a piece of content won't see a rendered image"

"Use og:image:width and og:image:height Open Graph tags.Using these tags will specify the image to the crawler so that it can render it immediately without having to asynchronously."

----------------------------------------

How I can have an empty `og:image` tag if  `if ( empty( $image ) )	$image = $this->get_image_from_cache();`

I think it's up to developer to decide what output if any he wants to get from a filter. 

------------------------------------------

You have a very good plugin and excellent support. A few standard filters going to make it even better. 

I'm working with the beta version and was hopping to have a little more control over output.

**Comment by sybrew** [comment]
Thank you so much janeks! I think I've overlooked that information :+1: 
I'll look into it, although I never ran into that problem myself. I can't promise it for 2.6.0 as all features have already been set and it takes quite some time to test such functionality.

You're right about the filter, and there are no workarounds for it at the moment.
And I must indeed add another filter for it. I'll keep you posted on this thread.

Until then, have a great weekend!

**Comment by sybrew** [comment]
Hi janeks,

The following filter has been introduced, which should be in beta within a few hours:
`the_seo_framework_ogimage_output_switch`

Usage:
```
add_filter( 'the_seo_framework_ogimage_output_switch', 'my_ogimage_switch', 10, 2 );
function my_ogimage_switch( $default = true, $id = 0 ) {
	//* $id is always an integer.
	if ( 6 === $id ) {
		return false;
	}
	
	return $default;
}
```

Untested, as always :). But should work as intended!

I'll look into the dimensions for a future update, as it requires a lot of testing (i.e. what if the file is gone or when the server doesn't support fileinfo, etc.).

I hope this helps! Have a great day :).

**Comment by janeks** [comment]
For now I’ve decided to switch back to production version an added bunch of filters to render.class.php
Example:

```
public function og_url() {

if ( false === (bool) apply_filters( 'the_seo_framework_output_og_url', true ) ) { return; }
```

I think most filters should let other plugins to hook into a function and provide custom content or no output. Custom content is fine but quite often you need to hit the database multiple times to supply value for each filter. It’s more efficient to disable SEO plugin output and generate your own meta in one pass.

**Comment by sybrew** [comment]
Hi janeks,

The filter I've provided is a fix for the incompetence of the other filter. Maybe I shouldn't check for `empty`, but rather a boolean and string type.

E.g.
```
$image = apply_filters( 'the_seo_framework_ogimage_output', '', $id );

if ( false === $image )
	return '';

//* Convert to string.
$image = (string) $image;

if ( '' === $image )
	$image = $this->get_image_from_cache();

$output = '<meta property="og:image" content="' . esc_attr( $image ) . '" />' . "\r\n";
```

What do you think?

Besides that, unsure what you wish to achieve with the explanatory statement/opinion, because the following comes to my mind:

All filters are stored in the `global $wp_filter`, there's no database interaction going on.
https://developer.wordpress.org/reference/functions/apply_filters/#source-code
https://developer.wordpress.org/reference/functions/add_filter/#source-code

If database interaction is going on, it's mostly passed through the autoload feature (within the options table). Which is then stored in WordPress object cache.
https://developer.wordpress.org/reference/functions/add_option/#source-code
https://developer.wordpress.org/reference/functions/wp_load_alloptions/#source-code

Could you clarify on how I should enforce filters? I think we can learn a thing or two :smiley:. Thanks!

**Comment by janeks** [comment]
I haven’t checked your new filter.  Needed a quick fix and modified the code before you posted the answer.

I wish I had a plugin I’m working on up and running but it’s still under development.

Scenario:
-	I have a lightbox with couple of images similar to: http://photoswipe.com/#&gid=1&pid=2 
-	I want to share this particular image on Facebook.

How do you do that with The SEO Framework? Facebook going to read og: tags from this page:  http://photoswipe.com/  That’s not what the user is looking for.

My plugin has a page with dynamic content based on query parameters (URL). In this scenario The SEO Framework creates og:image tag that points to header image (in case of my test page) and I don’t have any control over image dimensions, title and description.  On the other hand if I have an action,  filter or couple of filters to disable The SEO Framework output and replace it with custom values I can build my own meta section. 

Performance
To change a value of each tag in case  filter always returns default, I have to call database for each filter. To build and render the whole meta section with a single database call I need to have filters that return noting if filter value is an empty string or false. 

I ‘have this feature implemented for Jetpack, Yoast SEO and All In One SEO Pack. They are easy to work with. Yoast has both `do_action( 'wpseo_opengraph' );`  and filters for individual tags. In case of filters if I return empty string it won’t output a tag.

----------------------------------------------------------------------------

Dynamic content filters are only a part of the story. They are quite easy to implement. It took me couple of minutes to add these filters. The other issue is The SEO Framework lacks an interface to add custom  Facebook and Twitter tags to individual post or pages. The auto detection never going to work – too many variables. Both All In One SEO Pack and Yoast Yoast SEO realized that and now we have an option to override defaults with custom values on the page level. 

The last paragraph should be posted as a new thread. This one is about customizing og and Twitter tags.

**Comment by janeks** [comment]
I have a better example, the one that uses "The Seo Framework". 

Dynamic page: [http://abcfolio.com/wordpress-plugin-andora-lightbox-live-preview-gallery-with-captions/?andoraimg=15&andoracust=3080](http://abcfolio.com/wordpress-plugin-andora-lightbox-live-preview-gallery-with-captions/?andoraimg=15&andoracust=3080)


Check the Open Graph section created by my plugin and compare og:image to twitter:image:src. Twitter meta is generated by The Seo Framework.

Links to the dynamic page are created for each of the lightbox images: [http://abcfolio.com/wordpress-plugin-andora-lightbox-live-preview-gallery-with-captions/](http://abcfolio.com/wordpress-plugin-andora-lightbox-live-preview-gallery-with-captions/) 

Check how the Facebook button works.

**Comment by sybrew** [comment]
Hi janeks,

I've decided to remove the newly introduced `the_seo_framework_ogimage_output_switch` filter and make the filter listen to "false" instead, prior to the empty check.
This also counts for the `the_seo_framework_twitterimage_output` filter.

[The commit](https://github.com/sybrew/the-seo-framework/commit/42127b7280ad0065883922f5c114949c4ee8f6a7).

About the custom image importer, this has been discussed and it's on the road-map for 2.8.0.
There still has a lot to of work to be done to foresee a stable future for The SEO Framework. The 2.6.0 update makes sure of this.

Please be aware that The SEO Framework is just over a year old, and it initially was never intended to have an all-in-your-face interface &mdash; and it never will. I try to co-operate with the WordPress core environment as much as possible, to eliminate a learning curve.

Many add-ons are planned, both free and premium, for each and every SEO need.
For now, I hope the improved filters will suffice your needs.

Have a great day!
