### ISSUE TITLE
Write custom description into metabox

### ISSUE THREAD

**Issue by jserrao** [sybrew/the-seo-framework#300]
I'm using the `the_seo_framework_custom_field_description` filter to successfully write a custom description into the SEO framework for all my CPTs. 

My question: is there a filter to use to write those same custom descriptions into the metabox editors see at the bottom of every page?  It's just blank now, which makes sense but I'd might as well write in the custom description here as well. 

I checked the documentation and didn't see any filters listed - maybe I'm looking in the wrong spot?

**Comment by sybrew** [comment]
It's a bug. See #297 

This should be possible from that filter as of 668cbccc336dab1ab6c5626d8eb50ed7350605e8
You can download a copy [here](https://github.com/sybrew/the-seo-framework/archive/668cbccc336dab1ab6c5626d8eb50ed7350605e8.zip). 

Let me know if it works as intended 😄. If so, it'll be shipped as-is with 3.0.6.

**Comment by sybrew** [comment]
I just tested it. And it's still as it's supposed to be, I got a bit too far ahead with this.

The filter was (and still is) meant to be an "overwrite" hook for ***another* custom field**. 
Having the main custom field being overwritten when another plugin (or theme) tells it to be will cause issues in the long run. The reason being that it's essentially inconsistent and unexpected behavior.

Moreover, it falls outside of TSF's post meta API.

That said, I will implement the filter's behavior in the SEO Bar.

**Comment by sybrew** [comment]
I made it a little more consistent now. 😄 

If you have any more requests, or even find bugs, then feel free to open a new issue. 
Cheers!

**Comment by jserrao** [comment]
@sybrew - happy to test. You want me to test the latest code on `master` since commit [f7189f1](https://github.com/sybrew/the-seo-framework/commit/f781c32c5d15d17b47823bc3b6923ad81f7189f1)?

**Comment by sybrew** [comment]
Yes, please 😄. 
I only push commits of which I am thus far certain they're stable; unless otherwise stated.

**Comment by jserrao** [comment]
@sybrew - I was testing this afternoon post commit [26231b7](https://github.com/sybrew/the-seo-framework/commit/26231b70aa4dfed9d7afa9946f271e1537241efd) and still see this issue. Maybe it broke again somewhere in your refactoring? 

Happy to retest, just let me know.

**Comment by jserrao** [comment]
@sybrew - sorry I confused the SEO metabox with the SEO bar?!? What's the difference?

**Comment by sybrew** [comment]
Hi @jserrao 

This is the SEO Bar:
![image](https://user-images.githubusercontent.com/7662236/39710379-eeccc31e-521c-11e8-8566-367faf85c92a.png)

And this is the SEO meta box:
![image](https://user-images.githubusercontent.com/7662236/39710428-0fe78dcc-521d-11e8-88cb-842ac115dcce.png)

The meta box functions as user-input and it represents what should be used. If we'd allow filters to process it regardless of input, we'll run into walls fast.
So, the filter you've used should "actually only" apply when there's another separated input field; as a fallback or replacement.

When you use the "generated" description filter, then it ought to be represented as a placeholder.

**Comment by wassim** [comment]
@sybrew the commit was pushed in 3.0.6? Still doesn't work for the SEO bar here.

**Comment by sybrew** [comment]
@wassim make sure the filter runs on the admin-side too. It should work as intended.

If it still doesn't, could you please share the snippet you're using, so I can reproduce the error? Thanks!

**Comment by wassim** [comment]
@sybrew my apologies, I wasn't running the filter on the admin side too. Works fine now.
