### ISSUE TITLE
Date variables in Meta titles and descriptions

### ISSUE THREAD

**Issue by sillyonthestreet** [sybrew/the-seo-framework#301]
This is a feature suggestion...

I'm sure many people will find this useful. A variable so you can add the current date (month/year) via a variable in the meta titles and descriptions.

Yoast has a similar feature where you can add %%currentmonth%% and %%currentyear%% in metas.

**Comment by sybrew** [comment]
Discussed here: https://github.com/sybrew/the-seo-framework/issues/140
Feel free to leave suggestions related to this there 😄 

If you have any more suggestions, feel free to open a new issue!
