### ISSUE TITLE
Increase TSFEM exposure

### ISSUE THREAD

**Issue by sybrew** [sybrew/the-seo-framework#302]
After releasing several neat extensions, I still feel (...know) that users aren't aware of the Extension Manager's existence. 

I belief users can truly benefit from the extensions, and I'll be releasing more extensions over time, too.
Highlighting it via the plugin's information page, in the changelogs, and throughout the fora helped. But unfortunately, it isn't enough.

To tackle this, I'm going to add a single notification on the dashboard.
Now, this doesn't hold true to the original promise imposed to the users; it being "Free of ads".

So, let me relief any doubts you might have, by explaining what it will do.

**I want the notification to be:**
- Dismissable.
- Non-intrusive.
- Self-hiding.
- Helpful.
- Suggesting rather than imposing.
- Friendly ("want to", not "have to").
- Well built, using what WordPress provides.
- Only be outputted when the user can actually make use of it.
- Still holding true to the "your clients don't have to know what you're using..." statement.
- Et cetera...

That's a long list, and I think I've achieved most of it. 
In 59be3363f7d03ccaaa09e0738b55825b6a5a1df7, you can see the workflow in code.

From 3.0.6, the plugin will try to send a notification while running the plugin upgrade process. 
This happens once, and when it doesn't get through for any reason whatsoever, you won't see it, ever.

To sum up, this notification will only be shown when:

0. The upgrade happens when the applicable user is on the admin pages.
1. The constant `TSF_DISABLE_SUGGESTIONS` is not defined or false.
2. The current dashboard is the main site's.
3. The applicable user can install plugins.
4. TSFEM isn't already installed.
5. PHP and WP requirements of TSFEM are met.

**This is what it'll look like:**

![image](https://user-images.githubusercontent.com/7662236/39508925-8ff640ae-4de4-11e8-8da3-265ecfd47d89.png)

The link will open the WordPress' informative Plugin Thickbox, as you see in the "Add new" plugin dashboard.
The "Install Now" button will directly install it.

![image](https://user-images.githubusercontent.com/7662236/39509173-84e2765a-4de5-11e8-8c1a-314877559c87.png)

When it's done installing, you can activate it.

![image](https://user-images.githubusercontent.com/7662236/39509159-74e8ae2c-4de5-11e8-8981-cd8469ce3bc6.png)

------------------

#### Additional notes:

1. We might repeat this process (...not showing duplicated notifications) in the future, as we release more extensions.
2. I haven't tested the "FTP credential" system yet. Although the Shiny Updates API is pretty straightforward in this, I'm not sure if it'll work as expected.

------------------

#### Background information:

Unfortunately, WordPress "Shiny Updates" JS API is incomplete, so we'll have to hijack it.
This hijacking happens only when the user is directly interacting with the notification, with a timer attached that auto-resets it to prevent mistakes. The only problem this might cause is when you're on the `/import.php` admin page. Even then, you'll really have to try and want to break it; so, this is a non-issue.

**Comment by sybrew** [comment]
The installer was added in 59be3363f7d03ccaaa09e0738b55825b6a5a1df7. But, it was removed later because we shouldn't install plugins from non-WordPress.org sources.

With that, only during database-upgrades, users might see a notification (from v3.3 onward).

In 16431adae338d542eb6c6d0b401be448c574e78f we added a new one-time notification for new users to view the installation guide on our site. Although not directly related, we may wish to improve this notification to be so.

**Comment by birdbrainsolutions** [comment]
Hi sybrew, I got this link from u/LeBeaux on reddit.

>Hi, I've been thinking about testing your plugin and I might be able to help (free). I've been in online/offline sales since 2004 and also do graphics/web design so I understand a lot of markets. PM me if interested

>>At the moment, we have a plan on how to make all this work. WordPress plugins are pretty specific market and we spend a couple of months looking at all angles we can take. We are doing everything in open, so if you have any ideas, you can contribute to our github under tag growth! Thank you.

You can email me at birdbrainsolutions@gmail.com if you're interested so I can check out the plugin thoroughly

**Comment by LeBaux** [comment]
Hey @birdbrainsolutions, nice of you for stopping by! I mentioned on Reddit that we currently have a good idea on how to market TSF(EM). I pointed you to our Github, so you can get a feel for our current efforts.

Nevertheless, if you do have any specific ideas on how we can further make our free users aware of our extensions, please post them here directly. This way, other users and contributors can see and discuss the ideas in the open.

Thanks :slightly_smiling_face:

**Comment by birdbrainsolutions** [comment]
Hi Pierre,

From a sales/marketing perspective, I have barely seen any updates on
github (admittedly I have not checked that much).

I have spoken to an SEO person to test your plugin and update me on what he
likes about it, and in the mean time I will check your
site/plugin/copywriting and update you accordingly.

Let's make this the greatest seo plugin ever made and make sure that people
know about it!

yours sincerely,

Nick

**Comment by birdbrainsolutions** [comment]
Hi Pierre,

I haven't heard back from you, are you still interested in a (free)
marketing plan for the SEO framework?

Because I checked your site, wordpress plugin page and what people are
saying about your plugin and have quite a few ideas about it.

yours sincerely,

Nick

**Comment by sybrew** [comment]
Hi @birdbrainsolutions 

Thanks for your interest in supporting us!
Could you forward your ideas to https://tsf.fyi/contact? I'll be sure that Pierre received it. 

Thanks!

**Comment by sybrew** [comment]
We'll just continue to bombard the user until we are sustainable.
