### ISSUE TITLE
Feature Request: Automatically populate excerpt field

### ISSUE THREAD

**Issue by hubmacfan** [sybrew/the-seo-framework#308]
I realize there are some people who would like to write a separate excerpt and a separate meta description, but this is one feature I definitely miss from Yoast. It would be nice to have the option to have the meta description automatically populate the excerpt field.

**Comment by sybrew** [comment]
It's currently the other way around 😄 

I don't think it's beneficial to make it a two-way street.
In fact, I don't want this plugin to touch the visual aspect of the site just yet (aside from the sitemap).

**Comment by hubmacfan** [comment]
I didn't realize that. I'll just have to re-train myself. Keep up the
excellent work!
