### ISSUE TITLE
Override taxonomy meta

### ISSUE THREAD

**Issue by wassim** [sybrew/the-seo-framework#311]
I'm trying to override cpt's taxonomy meta. The filter `the_seo_framework_term_meta_defaults` doesn't work, am I missing something here?

Thanks!

**Comment by sybrew** [comment]
Hi @wassim 

If you create a new term, does it then work?

The filter stops enacting the moment a term is saved, as we use flags to determine the state of TSF data-migration.

**Comment by wassim** [comment]
@sybrew doesn't seems to work with newly created terms neither 🤔

**Comment by wassim** [comment]
I think i haven't been clear on this, what I was trying to do is to auto-generate a custom meta description for a custom taxonomy. I've found a way to do this, don't know if this is the cleanest way though @sybrew 🤷‍♂️

```
add_filter('the_seo_framework_generated_description', function($description, $args) {
	$admin_screen = get_current_screen()->taxonomy;
	$custom_desc = '';
	if ($admin_screen == 'mytax' || is_tax('mytax')) {
		$custom_desc = 'hello world';
	}
	return $custom_desc ?: $description;
}, 10, 2);
```

**Comment by sybrew** [comment]
Hi @wassim 

That should work 😄. Just be sure to clean off the bugs as AFAIK you shouldn't have access to the "current_screen" object on the front-end.

**Comment by sybrew** [comment]
A "permanent" solution is suggested at #316
