### ISSUE TITLE
Allow Editor Access to Settings Page

### ISSUE THREAD

**Issue by ednailor** [sybrew/the-seo-framework#322]
One of the things I love about this plugin is the white label part. We have a Multisite setup that we use this on and it's great. However, in the environment we do not offer Admin level rights to users, with Editor being the highest level possible. 

How can I allow access to the Settings page to Editors?

**Comment by sybrew** [comment]
Hi @ednailor 

You'll need to add the following filter in a plugin or mu-plugin, and it must run before `plugins_loaded` priority `5`.

```php
add_filter( 'the_seo_framework_settings_capability', function( $capability = 'manage_options' ) { 
	/** @see https://codex.wordpress.org/Roles_and_Capabilities#Capability_vs._Role_Table */
	return 'publish_pages';
} );
