### ISSUE TITLE
spurious _doing_it_wrong warning

### ISSUE THREAD

**Issue by drzraf** [sybrew/the-seo-framework#328]
$ `wp eval 'var_dump(wp_title());'`

`<span><strong>Notice:</strong> The_SEO_Framework\Query::can_cache_query was called <strong>incorrectly</strong>. You&#039;ve initiated a method that uses queries too early. - In file: /web/app/plugins/autodescription/inc/classes/generate-title.class.php - On line: 283 (This message was added in version 2.9.0 of The SEO Framework.) In /web/app/plugins/autodescription/inc/classes/query.class.php on line 86.</span><br>`

**Comment by sybrew** [comment]
`wp_title()` is a templating function... Why would it run in CLI?

We're running our extended version of WP_Query that mimics the front-end on the back-end (so to match expected and input values). The message you're seeing has been added to catch query caching errors early, so users won't get incorrectly generated metadata.

**Comment by drzraf** [comment]
Even worse... I just found that error inside a XML wxr-export file .... what obviously broke it...

**Comment by sybrew** [comment]
Hi @drzraf 

Thanks for notifying me that this issue goes beyond the templating functionality.

Note that you should suppress debugging on production websites. They can disclose sensitive data and vulnerabilities to visitors. 

See the useful constants in WordPress that help you do that:
https://codex.wordpress.org/Debugging_in_WordPress

For example
```php
define( 'WP_DEBUG', true );
define( 'WP_DEBUG_LOG', true );
define( 'WP_DEBUG_DISPLAY', false );
@ini_set( 'display_errors', 0 );
```

**Comment by drzraf** [comment]
https://github.com/humanmade/WordPress-Importer

**Comment by sybrew** [comment]
Thanks for sharing the importer. I think you've used WordPress itself to export?
In any case, with neither pieces of code, I could replicate the issue. Are you running an older WordPress version?

**Comment by sybrew** [comment]
With all the changes we've made, I think this issue will no longer arise from v3.1 henceforth.
