### ISSUE TITLE
whatsapp share image

### ISSUE THREAD

**Issue by colomet** [sybrew/the-seo-framework#329]
that is how looks like the image by sharing with whatsapp. From the main page.

![captura de pantalla 2018-06-04 20 49 14](https://user-images.githubusercontent.com/3929177/40935784-7657d47c-6839-11e8-85b2-fa0dc6d6fa64.png)

**Comment by colomet** [comment]
That is the original image
https://books4languages.com/wp-content/uploads/2018/05/Books4Languages-social.png

**Comment by colomet** [comment]
is not possible to have a square image for that??

**Comment by sybrew** [comment]
You can hold <kbd>SHIFT</kbd> while grabbing a cropping-corner to make square images in WordPress' image cropper. 
For most users, their main sharing audiences are on Facebook and Twitter, and therefore we default to their recommended aspect ratio.

If you wish to follow up, please see the related topic: #220
