### ISSUE TITLE
Wrong Tip Message

### ISSUE THREAD

**Issue by GuardianMajor** [sybrew/the-seo-framework#331]
@sybrew my friend, I anticipate you are about to release a new update and I wanted to share with you something I came across and hopefully you can resolve it in the next release.

When you go to Posts > Categories > Pick a Category and Edit, at the very bottom you get the Robot Meta and when you hover over Archive tip, you see this:

![wrong-tip](https://user-images.githubusercontent.com/5274181/41584116-4bee4c8e-735b-11e8-9348-b9782d2b6694.png)

It seems to be duplicating the tip for Follow, just though you might want to fix that, no biggie.

**Comment by sybrew** [comment]
Thanks for the report @GuardianMajor, much appreciated 😃

**Comment by GuardianMajor** [comment]
No problem my friend, just a little housekeeping and I figured to let you know before the next release in case you want to tidy it up, that's all. I see that you have been busy getting things ready for release, kudos and thanks for that. ❤️
