### ISSUE TITLE
Posts page has noindex tag

### ISSUE THREAD

**Issue by Sammortinger** [sybrew/the-seo-framework#332]
This plugin is adding a noindex tag to my posts page, and unfortunately I can't figure out how to stop this. I inspected the page to ensure it was coming from the SEO Framework plugin, and also made sure that I didn't have noindex checked in the meta box for the page. I don't see anything in the general settings, and yet it is receiving a noindex tag. The page is https://wpmodo.com/blog, any help would be appreciated!

**Comment by sybrew** [comment]
Hi @Sammortinger 

This happens because there are no posts found.  Once the blog is populated the tag should be cleared.

On the [front-page of the plugin](https://wordpress.org/plugins/autodescription/), you'll find this:
> [This plugin goes further, behind the screens it:] Discourages 404 pages and empty categories from being indexed, even if they don’t send a 404 response.

🤔 I should add an SEO Bar check for this...

**Comment by sybrew** [comment]
I'm adding an SEO bar feature that'll guide other users with extra information.
