### ISSUE TITLE
Why placeholder for inputs?

### ISSUE THREAD

**Issue by ultravibe** [sybrew/the-seo-framework#333]
We have a website with thousands of posts, and literally can be close to or over a hundred a day that editors have to update SEO information. Because the inputs are placeholder text, are those set or do we have to set each one? Also - because they are placeholder, it makes it harder to edit the default - you have to type the whole thing in again.

I may be missing something in the settings, but for orgs using this and dealing with tons of posts every day, workflow is seriously affected... Could there be an option to have the text in input boxes be set by default?

**Comment by sybrew** [comment]
Hi @ultravibe, 

The placeholders should represent what's used on the front-end.
You may choose to overwrite the content, and then that'll be used.

Copy+pasting the placeholder is something a browser may implement. Anything I choose to do with this will either be very ugly or a UX and accessibility nightmare. Previous: #27 

The original idea of this plugin, which still stands strong, is that the AI will look for any other fields you might have utilized within WordPress, and make the most out of that. This should prevent any obstruction of workflow, and it should improve SEO efficiency without requiring the user interacting with the plugin.
