### ISSUE TITLE
Moving the metabox under ACF fields

### ISSUE THREAD

**Issue by vladmirom** [sybrew/the-seo-framework#340]
Hi there, 

We were using this code snippet to move TSF metabox under custom fields created with ACF:
`function move_seo_to_bottom() {
  return 'below'; // Or below, what suits you best.
}
add_filter( 'the_seo_framework_inpost_seo_bar', __NAMESPACE__ . '\\move_seo_to_bottom' );`
However, after the recent updates, it's not working anymore. Seems that there's has been changed or removed recently. 

Is there any nice way to move the metabox under ACF, or to the very bottom of the page?

**Comment by sybrew** [comment]
The nicest way is to just drag the meta box to the bottom with your mouse. The setting will be saved per user, per post type.

`the_seo_framework_inpost_seo_bar` (removed in 3.1) is for the SEO Bar, which is this thing:
![image](https://user-images.githubusercontent.com/7662236/43251989-c49cecac-90c1-11e8-95c1-a76a6a6e415c.png)

You'll need to use this filter, instead:
`the_seo_framework_metabox_priority
`

For example:
```php
add_filter( 'the_seo_framework_metabox_priority', function( $priority = 'high' ) {
	return 'low'; // Accepts 'high', 'default', 'low'
} );
```

_FYI:_ `the_seo_framework_inpost_seo_bar` will be removed in 3.1. Use the General Layout options insead.

**Comment by vladmirom** [comment]
Thank you for the fast answer. Works good for Pages, however, the metabox has disappeared from custom post types. Do you happen to know why?

**Comment by vladmirom** [comment]
Hmm, the whole point to move the metabox is to make it most usable for the customer. 
Using screen options, or dragging the metabox down manually is a bit time consuming and sometimes annoying. My idea was to move it to the bottom automatically for all post types and pages, so the end user is not moving the metabox.

**Comment by vladmirom** [comment]
I found the solution. Since the priority is 'high' by default it moves SEO metabox below post editor and above ACF, changing it to 'default' decreases the priority of metabox and moving it under ACF. Also, it is showing on custom post types.

Thank you for help. I close the issue.
