### ISSUE TITLE
No SEO options for Product Attributes 

### ISSUE THREAD

**Issue by paulka007** [sybrew/the-seo-framework#356]
Hello

I've been following along and found most answers in the forums but this one has stumped me. If I look at the the post https://github.com/sybrew/the-seo-framework/issues/118 it seems you can edit the SEO settings of the attributes.

However Mine is blank:
![image](https://user-images.githubusercontent.com/16636353/45258175-c2971800-b3b3-11e8-8103-ed42b3f56189.png)

But I can seethe seo title in the listing page:
![image](https://user-images.githubusercontent.com/16636353/45258182-e8242180-b3b3-11e8-8ef8-2df75302fb98.png)

Any ideas?

**Comment by sybrew** [comment]
Hi @paulka007 

Have you resolved this, or posted the support inquiry elsewhere? I'm trying to find out what the issue is since you're not the only one experiencing it.

Thanks!

**Comment by paulka007** [comment]
Hi Sybre,

It's a strange issue, it disapeared as I was collecting screenshots so
closed the issue. I thought at first I was just looking in the wrong place.
But basically I think if there are no products in an attribute the seo
options are hidden.

So when I create a new attribute option there are no seo options, until I
add a product then its fine.

Kind regards,
Paul Kresfelder

**Comment by sybrew** [comment]
Thanks, @paulka007 for the feedback!

You can't edit the Attribute's SEO settings.

However, you can edit the Attribute's terms SEO settings, **when archives are enabled** for the Attribute.
1. Go to the attributes overview.
2. Select "Configure terms".
3. Select the term you wish to alter, SEO settings should appear there.

A commit will appear soon that will make this more concise and predictable. It will be shipped with v3.1.
