### ISSUE TITLE
Default excerpt_feed to false across sites

### ISSUE THREAD

**Issue by wetterisbetter31** [sybrew/the-seo-framework#365]
Is it possible to default excerpt_feed across all sites to false with use of a filter or does this need to be unchecked on each site individually. I'm not seeing an option to modify those properties. Thanks!

**Comment by sybrew** [comment]
Option `excerpt_the_feed` can be changed from `1` to `0`.

There's a filter available that allows you to adjust the defaults: `the_seo_framework_default_site_options`
This must run in a plugin, before `plugins_loaded` action 5.

```php
add_filter( 'the_seo_framework_default_site_options', function( $defaults = [] ) {
	// Adjust defaults here...
	$defaults['excerpt_the_feed'] = 0;

	return $defaults;
}, 10 ); 
```
