### ISSUE TITLE
robots.txt file throws 404

### ISSUE THREAD

**Issue by chuckreynolds** [sybrew/the-seo-framework#37]
Trying to figure out why the generated `robots.txt` file throws a 404 error code. 
I can view it w/ my browser but Google search console and Fetch show it as 404.

Thoughts?

WP: 4.6.1
Plugin: 2.7.0
PHP 7.0.12-1+deb.sury.org~trusty+1

**Comment by sybrew** [comment]
Hi Chuck,

The `robots.txt` file is outputted by WordPress, The SEO Framework merely filters its contents.

If you encounter a 404 issue in Google, please check its message date. If that's in the past, mark it as resolved. If you can access it (and no .htaccess rules exist for it), the message should no longer come back.

Google also offers a [robots.txt tester](https://www.google.com/webmasters/tools/robots-testing-tool?hl=en&siteUrl=), what does it say?

Cheers!

**Comment by chuckreynolds** [comment]
k. had some time to do more testing... the virtual file created by WP is throwing a 404... no idea why but i created a hard file instead of dealing with filtering all the stuff i wanted in there anyway. I thought it was related to this but I don't believe it is. closing.
