### ISSUE TITLE
Allow direct instantiation of plugin through Composer/WPackagist

### ISSUE THREAD

**Issue by danielpost** [sybrew/the-seo-framework#375]
Disclaimer: I suspect this is more of a feature request than an actual issue, so feel free to close this if it's outside the scope or not feasible.

In some cases, when I want complete control of a plugin, I install them through Composer/[WPackagist](https://wpackagist.org/) to the `vendor` folder, and `require_once` the main plugin file to instantiate the plugin.

This usually works fine, but for some reason struggles with The SEO Framework. When debugging I can see all the constants getting defined, but I don't see any metaboxes or settings pages. Any idea what might cause this? I'm thinking perhaps it's related to an activation hook being skipped or a reference to the plugins folder somewhere.

**Comment by sybrew** [comment]
The idea is that the plugin _should_ be available through those methods, so it's a bug 😞.

Could you zip and attach the output contents of Composer to this issue? I think GitHub supports file uploading via comments.
If you're afraid it might contain sensitive information, feel free to send it to me via [my contact page](https://theseoframework.com/contact/) instead.

This will help me with debugging and comparing as I'm not an avid Composer user myself. Thanks!

**Comment by sybrew** [comment]
Hi Daniel,

Thanks for the file! It cleared it all up for me.

You are right in that `_init_tsf()` is the main plugin's loader function. The alias of this function is `the_seo_framework()`, which might also be called elsewhere, like in the compatibility checker.

`do_action( 'plugins_loaded' );` runs before themes are included. This means that any action hooked into it thereafter won't work.

We need this action for compatibility checks, debugging, and setting up the API.

> 1. plugins_loaded action https://github.com/WordPress/WordPress/blob/4.9.8/wp-settings.php#L327
> 2. theme functions inclusion https://github.com/WordPress/WordPress/blob/4.9.8/wp-settings.php#L424

I'm not sure if I can provide a solution/workaround that suits your workflow 🙁

**Comment by danielpost** [comment]
Hi Sybre,

Thanks for the response. That does make a lot of sense. While I prefer to load plugins my way using Composer, it really isn't a big deal to install some the normal way.

Just to try things out I swapped out the `plugins_loaded` hook in `load.php` for `after_setup_theme` and everything does seem to work now. Manually changing the plugin every time it's updated is obviously a terrible idea, but just out of curiosity: do you know off the top of your head if there's any functionality in TSF that depends on `plugins_loaded` and wouldn't work with `after_setup_theme`? Is it the aforementioned compatibility checks, debugging and API?

**Comment by danielpost** [comment]
Apologies for the delay in response time. This definitely seems like the way to go and is something I was considering as well. Thank you for all the help!

**Comment by sybrew** [comment]
No problem 😃
