### ISSUE TITLE
Home Page Setting Placeholders are incorrect.

### ISSUE THREAD

**Issue by mjulian87** [sybrew/the-seo-framework#377]
If no values are entered under Home Page Settings -> Meta Title / Meta Description, then the values are correctly pulled from the Home Page.

However, under the Social tab, the titles are correct, but the descriptions fall back on the wrong value. They fallback on `get_generated_description( [ 'id' => $home_id ] )` rather than `$frompost_description`.

The issue is from tsf.js. If I comment out the `_initSocialDescInputs` function the fields have the correct starting value (but obviously don't update).

**Comment by mjulian87** [comment]
The issue appears to be coming from the switch around line 1737. If you fall through the switch to reference, then `tsf.params.socialPlaceholders.twDesc` and `tsf.params.socialPlaceholders.ogDesc` are incorrect.

If you fall back on `referenceValue` the same way that `_initSocialTitleInputs` does, then it appears to work as expected.

```
case 'reference' :
	val = val.length ? val : referenceValue;
	break;
```

**Comment by sybrew** [comment]
Confirmed. I spent three days on getting this right... and I still overlooked that 😞 

There's no issue when the JS files are turned off. So, this is luckily only a JS issue.

**Comment by sybrew** [comment]
Unfortunately, I've had to move this due to the sudden release announcement of WordPress 5.0.
