### ISSUE TITLE
Manually created seo title showing up with - site title

### ISSUE THREAD

**Issue by chuckreynolds** [sybrew/the-seo-framework#38]
AFAIK the post/page title will also have the site title on L or R if it's automated (aka you didn't manually write your post seo title). I'm having it show up regardless if I manually add my title to the "Post SEO Settings" > "Custom Post Title".  I'd like it to not do that... or give me an option to disable that? 

WP: 4.6.1
Plugin: 2.7.0
PHP 7.0.12-1+deb.sury.org~trusty+1

**Comment by sybrew** [comment]
Hi Chuck,

This has been done to enforce best practices among novice SEO users.
It's actually stated very clearly in [Google's best practices](https://support.google.com/webmasters/answer/35624?hl=en#3). And several topics on this issue exist on the WordPress.org plugin support forums.

I quote:

> **Brand your titles**, but concisely. The title of your site’s home page is a reasonable place to include some additional information about your site—for instance, `"ExampleSocialSite, a place for people to meet and mingle."` But displaying that text in the title of every single page on your site hurts readability and will look particularly repetitive if several pages from your site are returned for the same query. In this case, consider including just your site name at the beginning or end of each page title, separated from the rest of the title with a delimiter such as a hyphen, colon, or pipe, like this:
> `<title>ExampleSocialSite: Sign up for a new account.</title>`

Your request is however very popular; and I will add it as an advanced feature through a free extension.
For now, you'd (unfortunately) have to use filters:
```
add_filter( 'the_seo_framework_add_blogname_to_title', function( $default = true ) { 
	
	//* From a hard-coded list.
	$excluded = array( 5, 8, 42, 85 );
	if ( is_singular() && in_array( get_the_ID(), $excluded, true ) )
		return false;

	//* Or from custom metadata :)
	if ( is_singular() && get_post_meta( get_the_ID(), $key = 'my_title_additions_exclusions_setting', $single = true ) )
		return false;

	return $default;
}, 10, 1 );
```

Programming your own extension should take less than an hour with the code above 😄.
See [inpost box actions](https://github.com/sybrew/the-seo-framework/blob/05ae0de535e91dcd6b7bb1104388d6c922a23917/inc/classes/inpost.class.php#L289-L293).
See [inpost checkbox markup](https://github.com/sybrew/the-seo-framework/blob/05ae0de535e91dcd6b7bb1104388d6c922a23917/inc/views/inpost/seo-settings.php#L189-L218). `$this` can be exchanged with `the_seo_framework()`.

I'll keep you updated on its progression! Extra hooks will be added to make this more seamless, of course.

**Comment by chuckreynolds** [comment]
Yeah so... I'm aware of best practices, and I understand why you'd want 'novice' people to have that auto-enabled, however having a checkbox in settings to turn that off would be nice. 

The reason I've started looking at and testing this plugin, in particular, is because everything else out there is so... novice... as you put it. I can handle having to add a filter to do it but... like those other plugins... I have a set of filters and/or functions to turn off a lot of that novice stuff that either clutters the admin, and/or makes decisions for me which I'm unable to control by the plugin making said decisions. I'm just looking for an advanced plugin that doesn't do "best practices" for me. 

Thanks for the filter info. Hope this is at least considered in the future. cheers. 👍

**Comment by sybrew** [comment]
Hi Chuck,

You're absolutely right. 

For the record, granular/advanced control is not only in consideration, but it's planned as well 😄.
For this reason, I'm re-opening this issue as the added tags (enhancement & Free Extension) already state its state of progression.

Most of the framework for the said options is already finished, so adding these kind of options should be a breeze in the near future. All these enhancements are planned to be started on as early as December.

Cheers!

**Comment by phrench** [comment]
It looks like this is already implemented now and the issue can be closed?

Good choice and thanks for adding it! This feature was really needed.

**Comment by sybrew** [comment]
Hi @phrench,

That shouldn't be happening! Thanks for the bug report 😄

**Comment by sybrew** [comment]
Hi @phrench,

Unfortunately, I'm unable to reproduce the issue you're facing. Neither with 2.7.3 nor the current development version. Could you please check your caches? Cheers!

**Comment by sybrew** [comment]
Moved to https://github.com/sybrew/the-seo-framework/issues/120.
It's no longer planned as an extension, but rather in the core plugin.
