### ISSUE TITLE
Pull usable content from page builders

### ISSUE THREAD

**Issue by sybrew** [sybrew/the-seo-framework#380]
From [blackeye's comment](https://wordpress.org/support/topic/elementor-compatibility-8/#post-10880515):

Reimplement description generation support for page builders, including Divi, Elementor, Beaver Builder, Visual Composer, and SiteOrigin's Page Builder.

The `''` in this ternary condition should be replaced with a callback:
https://github.com/sybrew/the-seo-framework/blob/3.1.4/inc/classes/post-data.class.php#L378

**Comment by black-eye** [comment]
+1 :)

**Comment by sybrew** [comment]
Inquiry for Divi: https://github.com/elegantthemes/create-divi-extension/issues/228

Related: [Focus' page builder supprt](https://theseoframework.com/extensions/focus/#faq/are-page-builders-supported)

**Comment by harrymade** [comment]
Elementor +1

**Comment by krassomatiker** [comment]
Elementor +1

**Comment by sybrew** [comment]
@krassomatiker Elementor will be supported in TSF v4.1 😄 ETA before or on August 11th, 2020.

**Comment by krassomatiker** [comment]
@sybrew thx!
