### ISSUE TITLE
is there any changes in versions

### ISSUE THREAD

**Issue by davvidp** [sybrew/the-seo-framework#386]
i'm currently using wordpress version, if i upgrade the plugin from github version, are there any major changes?

cheers

**Comment by sybrew** [comment]
Short answer: No, there are no differences.

Long answer:
This repository is the development directory for the plugin. 

However, as I release tags here, they're often completely identical to the version on WordPress.org.

Updates on WordPress.org receive a little more love, like quicker distribution of minor patches. When I'm wholly satisfied, I tag the plugin on both WordPress.org and here.
