### ISSUE TITLE
Problem with Robots.txt page blocking google bots from searching homepage

### ISSUE THREAD

**Issue by bridgeconnector** [sybrew/the-seo-framework#388]
Hello,

I have downloaded The SEO Framework plugin on my website, https://bridgeconnectorministries.com

The home page is being blocked from google bots doing a search on the home page:

On this page:
https://bridgeconnectorministries.com/robots.txt

this is what displays:

User-agent: *
Disallow: /

When I go into the SEO settings page on WordPress, and scroll down to the Sitemap settings, under the Robots.txt tab, 
this is what you see:   When I click the link "here" (below) it navigates me to the robots.txt page, but I am unable to make any change to correct the problem. 

Add sitemap location in robots.txt
 Add sitemap location in robots? [?]

The robots.txt file can be found here.

This appears to be a bug with the plug in. Can you please help me solve this problem?

Thankyou so much!

**Comment by sybrew** [comment]
Hi there!

Did you recently set up the site, or migrated to WordPress?

Whatever the reason may be, there's a tricky little option active on your site.

1. Go to this page: `wp-admin/options-reading.php`
2. Deactivate the "Search Engine Visibility" option.
3. [Ask Google to recrawl your URLs](https://support.google.com/webmasters/answer/6065812?hl=en).
4. Wait a few days, and your site will be indexed.

That's it :)

**Comment by sybrew** [comment]
Closing as resolved.
