### ISSUE TITLE
Post image showing up in open graph tags for taxonomy/term archives

### ISSUE THREAD

**Issue by xsynaptic** [sybrew/the-seo-framework#395]
The bug: some taxonomy/term archives will include an `og:image` even through none was assigned.

Plugin version: latest. I'm also using another plugin called Taxonomy Images to associate images with terms but this does not appear to be in conflict with the SEO Framework. 

From sifting through the code it would appear as if the `get_the_real_ID` function is the root cause. This function will return a term ID (via `get_queried_object_id`) but the image generation class assumes whatever ID was returned is a post. If you have a term with the same ID as a post with a featured image then SEO Framework will generate an `og:image` tag for the taxonomy/term archive _from the post_.

A temporary fix: 

```php
add_filter('the_seo_framework_og_image_args', function( $args ) {
	if ( is_category() || is_tag() || is_tax() ) {
		$args['post_id'] = false;
	}
	return $args;
});
```

**Comment by sybrew** [comment]
I knew about this... it's odd I never opened an issue for it. So, thank you for that! 😄

I'm glad the workaround is this simple; a fix might make it in a minor release. Cheers!

**Comment by sybrew** [comment]
I'd have to rewrite the image generation flow, just like I did with the titles, canonical URLs and descriptions in the last 3 major updates. See the main issue: #166.

A patch would hinder external calls to the methods and filters in place, as they're not aware of the state-check.

So, I'm going to rewrite the functionality, and with that, introduce support for manual image selections. 
See #110.

**Comment by sybrew** [comment]
As we're going to overhaul the API in the next release, I feel more confident bringing a slightly API breaking patch in the minor 3.2.2 release.

I don't consider "patches" "fixes", but it'll resolve the issue nevertheless.
