### ISSUE TITLE
No site should enable these options for Posts - maybe is a good idea to do it

### ISSUE THREAD

**Issue by colomet** [sybrew/the-seo-framework#397]
maybe that warming is not always true. If somebody have a ecomerce site or a site about a company with not blog, they have no post or just post for internal use and do not require to have it indexed

![captura de pantalla 2018-12-27 a las 15 51 43](https://user-images.githubusercontent.com/3929177/50484152-55a19f80-09ef-11e9-9487-e216d6b08a8a.png)

**Comment by sybrew** [comment]
The emphasized warning isn't a blocking feature: it is to steer users away from using it who do not know the impact.

Users (like you) who do know what effect the option has, and in which scenario it might be beneficial, can use the option regardless.

Unfortunately, I've seen many users tick boxes they shouldn't have ticked. The SEO Framework is there to help users without SEO knowledge, as well as giving the power and freedom to users who do.
