### ISSUE TITLE
Exclude CPT

### ISSUE THREAD

**Issue by 9585999** [sybrew/the-seo-framework#398]
Hi, how exclude CPT from sitemap?

I try filter 

```php
add_filter('the_seo_framework_sitemap_exclude_cpt', function ($excluded = []) {
    $excluded = ['table'];

    return $excluded;
}, 10);
```

but this is not work...

**Comment by sybrew** [comment]
Hi there!

The `table` CPT doesn't seem to be an intended public post type. I recommend disabling all SEO for it completely. You can do this via the SEO settings page, under **Post Types -> Disable SEO**.

If you'd still like to use the filter, then you should also add to the `$excluded` array, not overwrite it. This ensures compatibility with other plugins that try to use the filter. For example:
```php
add_filter('the_seo_framework_sitemap_exclude_cpt', function ( $excluded = [] ) {
    $excluded[] = 'table';

    return $excluded;
}, 10);
```

Be sure to clear the sitemap's cache after applying the filter. Update any post or the SEO settings, and it should flush.

**Comment by 9585999** [comment]
@sybrew 

Your recommendations work as expected.

Thank you for help!
