### ISSUE TITLE
Require the Extension Manager through Composer

### ISSUE THREAD

**Issue by chrisschwartze** [sybrew/the-seo-framework#399]
Since the old Extension Manager is now deprecated. I'd love to have a way to require https://theseoframework.com/extension-manager/ through Composer. 

Before, I was requiring it through wpackagist. 

Thoughts?

**Comment by sybrew** [comment]
It is available through Composer 😄 

See: 
1. https://packagist.org/packages/sybrew/the-seo-framework-extension-manager
2. https://github.com/sybrew/The-SEO-Framework-Extension-Manager/blob/master/composer.json

```dash
composer require sybrew/the-seo-framework-extension-manager
```
