### ISSUE TITLE
Meta tags use the site icon instead of the post's image

### ISSUE THREAD

**Issue by alanorth** [sybrew/the-seo-framework#4]
Meta tags for `og:image` and `twitter:image:src` use the site icon instead of the image contained in a post. See attached screenshot with the [Twitter cards validator](https://cards-dev.twitter.com/validator). Also applies to sharing via WhatsApp, etc.

![screen shot 2016-05-05 at 17 04 33](https://cloud.githubusercontent.com/assets/191754/15045703/b2b595f0-12e4-11e6-914b-860db9f115ff.png)

I was testing with [a post on my blog](https://mjanja.ch/2015/04/ramping-up-the-ethiopia-lug/). Running WordPress 4.5.1, with plugin version 2.5.2.4.

**Comment by sybrew** [comment]
Hi Alan,

Thanks for opening this ticket, and I understand your concern. Many others share this concern with you.

Currently, attached images aren't added into the Open Graph and Twitter image.

This is the order in which the images are fetched:

> 0. Defaults override filter
> 1. Featured Image (best practice)
> 2. Fallback filter 1
> 3. Header Image (theme dependent)
> 4. Fallback filter 2
> 5. Site Icon (from Customizer)
> 6. WPMUdev Avatars site avatar (removed in 2.6.0)

In a near-future version the images from the posts will be considered. More on that will be made public when time is due.

I hope this clears things up!

**Comment by alanorth** [comment]
Thanks for the response, @sybrew. I've been ignoring featured images for the last few years because I don't like how most themes handle them — I usually only have one image in the post, and themes usually show the featured image above the post, which means my image usually comes twice. In any case, I'm eagerly awaiting the next version. 👍

**Comment by alanorth** [comment]
What ever happened to this issue? I'm still getting a HUGE site icon on [Twitter cards](https://cards-dev.twitter.com/validator) instead of an image from the post. Try with this post from one of my blogs, which has a very nice image in it: https://englishbulgaria.net/2016/05/vratsa-is-a-picturesque-thracian-city/

**Comment by sybrew** [comment]
Hi Alan,

As I'm the only author of these plugins, I'm afraid you'd have to think in months rather than weeks.

Getting images from the post is still on the roadmap and it's planned as a free add-on. 

I've been very busy writing a [Jetpack like framework](https://github.com/sybrew/The-SEO-Framework-Extension-Manager) for the add-ons, I hope to have version 2.7.0 and the add-on/extension manager ready by 1st of September, from there I can rush all these features in without compromise :+1:.

If you have any suggestions, feel free to let me know!

**Comment by sybrew** [comment]
A separated uploader (see #34) has just been added. Bulk-fetching from content's source is still on the roadmap as an extension 😄

**Comment by sybrew** [comment]
From 2.8.0 henceforth, the output will be like:

0. Defaults override filter
1. SEO Settings image uploader (new!)
2. Featured Image (best practice)
3. Fallback filter 1
4. Header Image (theme dependent)
5. Fallback filter 2
6. Site Logo (from Customizer WP 4.5; new!)
7. Site (fav)icon (from Customizer WP 4.3)

For the "fallback" uploader, please continue on the updated #68 issue. Cheers!
