### ISSUE TITLE
Disable indexing of custom posts

### ISSUE THREAD

**Issue by abombelli** [sybrew/the-seo-framework#40]
Hello

How can we disable indexing of all single pages of a specific custom post?

Thanks,
Aldo

**Comment by sybrew** [comment]
Hi Aldo,

Yes this is possible.
This can be achieved through the "noindex" option, which is found in the SEO settings metabox beneath the content editor.

If you wish to prevent all entries from a custom post type from being indexed, there are filters available. These can be found on the [Filters API](https://theseoframework.com/docs/api/filters/) page.

Cheers!

**Comment by abombelli** [comment]
Thanks! I guess it is this filter: the_seo_framework_robots_meta_array?

**Comment by sybrew** [comment]
Yes, that's the filter 😄

It contains this array as its first (and only) parameter:
```
$meta = array(
	'noindex'   => $this->get_option( 'site_noindex' ) ? 'noindex' : '',
	'nofollow'  => $this->get_option( 'site_nofollow' ) ? 'nofollow' : '',
	'noarchive' => $this->get_option( 'site_noarchive' ) ? 'noarchive' : '',
	'noodp'     => $this->get_option( 'noodp' ) ? 'noodp' : '',
	'noydir'    => $this->get_option( 'noydir' ) ? 'noydir' : '',
);
```

**Comment by sybrew** [comment]
Hi Aldo,

I'm closing this issue as I believe it has already been resolved. If you have any more questions in the future, do let me know!

Have a great day!
