### ISSUE TITLE
Image generation rewrite: back to basics

### ISSUE THREAD

**Issue by sybrew** [sybrew/the-seo-framework#403]
> " Normal people don't understand this concept; they believe that if it ain't broke, don't fix it. Engineers believe that if it ain't broke, it doesn't have enough features yet. - Scott Adams

Related:
- #166, this is the 4<sup>th</sup> post in the series.
- #395, this will fix it.
- #110, this is a prerequisite.
- #268, this will allow it.

The image generation code stems from an early release, 2.0.5, and was improved further in 2.5.0. Over time, I've combobulated integration for Open Graph image dimensions, AJAX uploading, WooCommerce gallery support, and more. This lead to an inconsistent system that's all over the place; some might call it spaghetti code, and they'd be right.

## This is what we're going to do:

1. Standardize callers.
2. Deprecate all old callers.
3. Rewrite the generation code.
   - Synchronize it with WordPress' API, which improved its image handling significantly in the past two years.
4. Upgrade all attached systems (social meta output, extensions, etcetera).
5. Add more features.

## I'm a user, what can I expect?

Fewer (goal: zero) bugs, faster operation, and more features!

## I'm a developer, what can I expect?

I'll deprecate all related methods and make all attached filters inoperable under normal conditions.
Your implementations won't break, but warnings will be shown. 

A full list API of changes will follow.

In 3.5 or 3.6 I'll remove the deprecated code. You don't have to worry about updating: Your site won't crash when calling undefined methods, because the factory (`the_seo_framework()`) has fail-safes.

**Comment by joshuafredrickson** [comment]
I'm not sure if this is included yet, but I've come across an issue when using an og:image on a CDN. The upload URL is prepended to the image's full URL.

Instead of `https://cdn.example.com/og-image.jpg`, it returns `https://wordpress-site.com/wp-content/uploadshttps://cdn.example.com/og-image.jpg`.

I believe this is related to the resizing process found in `parse_og_image()`.

**Comment by sybrew** [comment]
Hi @joshuafredrickson 

This isn't the right place for support. Please refer to [our support forum](https://wordpress.org/support/plugin/autodescription/) in the future.

In any case, the bug you're encountering is caused by the CDN rewrite plugin active on your website. You should contact the authors of that plugin.

**Comment by sybrew** [comment]
We want to consider adding filters to the image selection. I do have to check if the ID of this is independent of the size.

Ref: [Inje's support inquiry on w.org](https://wordpress.org/support/topic/specify-ogimage/).
