### ISSUE TITLE
Title H1 field

### ISSUE THREAD

**Issue by koreos** [sybrew/the-seo-framework#404]
Hi, please add H1 Title field (main content title) to the amazing SEO Framework - the best plugin for SEO!

In dashboard we need name pages like: 01, 02, 03, 10, 12...
But in H1 title: 1, 2, 3, 10, 12...

**Comment by sybrew** [comment]
Hi @koreos, 

I'm glad you like the plugin!

Please note that headers are theme territory. Although they're great signals in SEO, they're something the plugin shouldn't control.

The `h1` tag is usually defined in the page title at the top of the content editor. `h2~6` can be defined within the content editor.

Please advise with your theme author on this issue. Cheers!
