### ISSUE TITLE
twitter:creator displayed on homepage if the first article's author has it set

### ISSUE THREAD

**Issue by karex** [sybrew/the-seo-framework#405]
Steps to reproduce:

1. Set "Twitter profile name" in a user's profile.
2. Create a post with that user, and make that the first post on the homepage.

Checking the twitter card meta tags, we can see that the `twitter:creator` tag is present on the homepage with the profile name of the author of the first post. 

This happens because for some reason the main loop is already engaged when these tags are generated. Maybe an `is_single()` check might be enough at an appropriate place, but further modifications might be needed as well.

**Comment by sybrew** [comment]
Thanks for reporting this issue! I have yet to confirm it, but the code points towards an apparent oversight.

On the homepage, `get_the_real_ID()` returns 0. `get_post()` will therefore return the first object found in the query.

https://github.com/sybrew/the-seo-framework/blob/60864136e375605ccf3f8356e531dc0d0f6d2d87/inc/classes/user-data.class.php#L58-L68
