### ISSUE TITLE
Transform grammatical gender pronouns for wildcards

### ISSUE THREAD

**Issue by sybrew** [sybrew/the-seo-framework#414]
Grammatical gender is embedded in languages from Latin origin.

```
English: This girl
Dutch:   Dit meisje

English: This guy
Dutch:   Deze jongen
```

"Dit" and "Deze" mean the same but are of different gender based on the subject.
When we introduce wildcards (e.g. `%s`), this can become a problem. For instance:
```
English: This %s
Dutch: Deze/dit %s
```

We want to eliminate this discrepancy.

Ref: https://wordpress.slack.com/archives/C02RP50LK/p1550962610020600
More background: https://wordpress.org/support/topic/some-notes-from-a-translator/

## Affected sentences

- [x] Bots are discouraged to archive this %s.
   - **Suggested:** "%s may not be archived."
- [x] Bots are allowed to archive this %s.
   - **Suggested:** "%s may be archived."
- [x] Apply %1$s to this %2$s
   - %2$s is the issue.
   - **Suggested:** **Removal**. See #345.
   - **Replacement:** "Set %s to:"
      - %s = noindex/nofollow/noarchive
- [x] This tells search engines not to show this %s in their search results.
   - **Suggested:** "This urges robots not to show this webpage in their indexes."
- [x] This tells search engines not to follow links on this %s.
   - **Suggested:** "This urges robots to discard value of any link on this webpage."
- [x] This tells search engines not to save a cached copy of this %s.
   - **Suggested:** "This urges robots not to create a cached copy of this webpage."
- [x] Exclude this %s from local search
   - **Suggested:** "Exclude this webpage from all search results queried on this site."
- [x] This excludes this %s from local on-site search results.
   - **Suggested:** **Removal**, redundant.
- [x] Exclude this %s from all archive listings.
   - **Suggested:** "Exclude this webpage from all archive listings queried on this site."
- [x] This excludes this %s from on-site archive pages.
   - **Suggested:** **Removal**, redundant.
- [x] %1$s the %2$s is protected from public visibility. This means indexing is discouraged.
   - %2$s is the issue.
   - **Suggested:** "%s this is protected from public visibility. This means indexing is discouraged."
      - %s = But/And

## Candidate sentences

- [x] Note: The feed is already converted into an excerpt (summary) through the %s.
   - Not necessarily an issue, but we might wish to convert this to markdown.
   - "excerpt (summary)" can become just "excerpt".
   - **Suggested:** "Note: The feed is already converted into an excerpt through the `[Reading Settings](%s)`".

**Comment by tobifjellner** [comment]
Improvement suggestions:
• "%s may not be archived." → "Crawling bots are discouraged from archiving this content (%s)"
• "%s may be archived." → "Crawling bots are allowed to archive this content (%s)"
• "%s this is protected from public visibility. This means indexing is discouraged." → "This is protected from public visibility, which means that indexing is discouraged."

**Comment by tobifjellner** [comment]
One more:
%1$s is %2$s since version %3$s of The SEO Framework! Use %4$s instead. 
→ 
The function %1$s is <strong>deprecated</strong> since version %2$s of The SEO Framework! Use %3$s instead.

**Comment by tobifjellner** [comment]
Another quite similar one:
%1$s was called %2$s. %3$s %4$s   →
`The function %1$s was called <strong>incorrectly</strong>.`
The error message can be output separately.

**Comment by sybrew** [comment]
I added escaping functions over all strings, so nefarious translations don't stand a chance! This, unfortunately, means we can't add HTML easily.

There are more strings affected by this:
- `Apply %1$s to this %2$s` -> `Apply <code>noindex</code> to this %s`
- `Apply %1$s to %2$s Archives?` -> `Apply <code>noindex</code> to %2$s archives?`
- `Apply %s to every second or later archive page?` -> `Apply <code>noindex</code> to every second or later archive page?`
- etc...

**Comment by tobifjellner** [comment]
In some other place you were using markdown. If you've imported support for markdown, then that might help in some cases. (Although many polyglots aren't used to it, so you may need to spray in comments about the meaning of single underscores around some words. (Doesn't really solve how to mark code, though.
