### ISSUE TITLE
List issues in the SEO Bar, instead of writing them out.

### ISSUE THREAD

**Issue by sybrew** [sybrew/the-seo-framework#415]
The SEO Bar talks to you when you hover over or tap it.

![image](https://user-images.githubusercontent.com/7662236/53305386-5769d100-3881-11e9-894a-be3f919f8392.png)

It's a nice little anthropomorphic touch to the plugin. However, there are a few problems with it:
1. Translating this doesn't go well.
    - For example, the "But/And" at the beginning begs for consideration.
2. The users can get confused, as they have to assimilate the sentence structure.
    - Ref: https://github.com/sybrew/the-seo-framework/issues/265#issuecomment-373803828

So, I'm proposing to list all "why" issues with the item. 
When there aren't any issues (bar block is green), we should state that everything's OK.

For example:
```html
%s may not be indexed:<ol><li>This blog isn't set to public.</li><li>%s is in draft</li></ol>
```

Result:
![image](https://user-images.githubusercontent.com/7662236/53305521-ca277c00-3882-11e9-976d-f713dcbab4d4.png)

Note: WordPress' and browser CSS interfere, we need to adjust this:
```css
.widefat p,
.widefat ol,
.widefat ul {
	color: #32373c;
}

ol {
	margin: ?;
}
```

<del>Cross-issue: Aria-labels shouldn't contain HTML tags.</del> <ins>Fixed in 9fbf39e255e53181c2518d37b0f06883713110a2</ins>

**Comment by tobifjellner** [comment]
I like this from a translation point of view.

**Comment by sybrew** [comment]
We have to rewrite the SEO Bar for #345. As such, we might as well do this.
