### ISSUE TITLE
Author archive title obtains protected prefixes on post ID collision.

### ISSUE THREAD

**Issue by TBarregren** [sybrew/the-seo-framework#416]
If there is a post with post ID *n* and post status set to *private*, and there is a user with user ID same as the post id, that is *n*, then the title tag of the user's author archive is prefixed with "Private: ".

This happens in `Generate_Title::merge_title_protection()` where `$id` is assigned the user's ID but the code assume it to be a post ID. Since there is a post with that ID and that post has `private` as `post_status`, method prepend the title with "Private: ".

A provisional workaround is to implement the filter `private_title_format` with this ugly hack:

    add_filter('private_title_format', function ($format) {
        global $wp_query;
        if (isset($wp_query->query['author_name'])) {
            $format = '%s';
        }
        return $format;
    });

See also #258

**Comment by sybrew** [comment]
Thanks for reporting this bug! I was able to confirm this.

Until a patch is released, this workaround would suffice:
1. Create a new post (which creates a new ID).
2. Copy all data from the old post into the new post.
3. Delete the old post permanently.
4. Confirm the permalink of the new post is identical to the old post.
