### ISSUE TITLE
Every request deletes and updates rewrite_rules in wp_options

### ISSUE THREAD

**Issue by andresb** [sybrew/the-seo-framework#421]
**Big, active website clogs MySql logs with the same 3200 item array written to wp_options on every request.**
I don't have another description. I woke up to alerts caused by a 100% full disk on my MySql server and 300 Gb of binary logs created since yesterday morning. The rewrite_rules option is being updated constantly without any change to permalinks or other plugins.

**To Reproduce**
1. Go to mysql
2. SHOW FULL PROCESSLIST \G
3. Witness the same 3200 item array go 500 times through the screen - Info: UPDATE `wp_options` SET `option_value` = 'a:3202:{s:13:\"sitemap\\.xml$\";s:39:\"index.php?the_seo_framework_sitemap=xml\";s:13:\"sitemap\\.xsl$\";s:39:\"index.php?the_seo_framework_sitemap=xsl\";s:11:\"^wp-json/?$\";s:22:\"
4. Watch binary logs get full like there's no tomorrow.

**Expected behavior**
Sane flushing/updating schedules.

**Additional context**
Very few other plugins. W3TC with Object and DB cache enabled.
Query alteration disabled (just in case), "Use object cache" enabled under "Performance".
Version 3.2.4

**Comment by sybrew** [comment]
Hi @andresb 

That must be frustrating! 😦 

TSF is part of the big mesh that generates the rewrite rules, and it adds its rules on top to prevent adding a trailing slash to `sitemap.xml` (so you won't get `example.com/sitemap.xml/`). So, this is why you see it at the very beginning of the options.

Now, TSF only flushes the rewrite rules when you change the options of the plugin. 
Have you deducted the cause yet by disabling other plugins?
