### ISSUE TITLE
missing canonical

### ISSUE THREAD

**Issue by blue-eyed-devil** [sybrew/the-seo-framework#422]
I am using SEO Framework in WP multisite environment where one blog serves as main content storage.
Obviously every blog has its own pages and posts, but some posts from main content storage are displayed in child blogs/s.
My issue is a canonical tag.
It is rendered with page or post created and stored in particular blog, but once I display post from main content storage in child blog, all relevant meta data are missing. the only meta data that are generated are:

```
name="robots"
name="description"
property="og:image"
property="og:locale"
property="og:type"
property="og:title"
property="og:site_name"
```

**Comment by sybrew** [comment]
Hello!

Since 3.2.4, the canonical URL will no longer be outputted when it matches the query and when the `noindex` robots directive is present. 

See #370
