### ISSUE TITLE
Shortcodes from other plugins or functions - be able to use them

### ISSUE THREAD

**Issue by curlygirly1** [sybrew/the-seo-framework#423]
Hi, please enable the use of dynamic and other shortcodes in meta fields.
like [year] etc. If it is supported, how to configure custom functions for my shortcodes to work in your plugin?

**Comment by sybrew** [comment]
Duplicated support inquiry: https://wordpress.org/support/topic/shortcode-support-31/

I'll answer your question there. Cheers!

For users stumbling upon this page, please see our "most requested filters" API docs:
https://theseoframework.com/docs/api/filters/
