### ISSUE TITLE
Remove noarchive if noindex is set

### ISSUE THREAD

**Issue by uok** [sybrew/the-seo-framework#427]
Just a small optimization:
if a page is set to `noindex, noarchive`, output for meta robots can be reduced to `noindex `

**Comment by sybrew** [comment]
Hi there!

Those two tags serve different purposes. One directs the indexing state; the other directs the archiving state. It's up to the search engine or crawler to honor this, and we can't assume one implies the other.

https://developers.google.com/search/reference/robots_meta_tag#valid-indexing--serving-directives

With that, I'm closing this issue. However, feel free to prove me wrong, and I'll consider its implementation. 👍
