### ISSUE TITLE
Previews don't update with Gutenberg

### ISSUE THREAD

**Issue by rpsstudios** [sybrew/the-seo-framework#429]
Hey,

I have been running down a Wordpress post preview issue and I think your SEO Framework plugin is breaking them somehow. On a fresh install of Wordpress with the default 2019 theme, I first created and published a new blog post. After this, I made an edit and clicked preview and it showed my changes. I then installed the SEO Framework plugin and clicked on the posts page to edit this post again. I then made some changes and clicked the preview button and now my changes won't update. You can see a screen recording of the steps here: https://www.dropbox.com/s/ifylzcgiy7w1qq1/seo-framework-preview-issue.mov?dl=0

Martin

**Comment by sybrew** [comment]
Hi Martin,

I caught this issue a few times as well, and it made me paranoid, and now I always keep a copy ready in case it fails to update.

Now, could you reevaluate this issue after WordPress 5.2 is released? 

This is a known issue for many plugins, and it supposedly lies in Gutenberg itself:
https://github.com/WordPress/gutenberg/issues/12617

**Comment by rpsstudios** [comment]
Hey,

Advanced Custom Fields Pro and WP Rocket both have issues with preview as
well. So either this isn't a feature that is used often, or it must be a
Wordpress core issue. I just tried WP5.2 beta and that didn't fix the
issue. Any other ideas?

Martin




*Martin Blumenfeld • Pixel Pusher*

*RPS Studios Inc.*

p. 778.808.5863
e. martin@rps.is
w. www.rps.is

**Comment by sybrew** [comment]
The fix was forwarded into the latest Gutenberg release 6 days ago; so, it may take a while before it reaches WordPress 5.2 beta. It may even have to wait until WordPress 5.2.1.

I'm unaware of any workarounds.

**Comment by rpsstudios** [comment]
Sounds good, thanks!


*Martin Blumenfeld • Pixel Pusher*

*RPS Studios Inc.*

p. 778.808.5863
e. martin@rps.is
w. www.rps.is

**Comment by rpsstudios** [comment]
Do you have a link to the Gutenberg commit that fixes this issue?


*Martin Blumenfeld • Pixel Pusher*

*RPS Studios Inc.*

p. 778.808.5863
e. martin@rps.is
w. www.rps.is

**Comment by sybrew** [comment]
Hi Martin,

All details related to the problem (including commits, discussions, etc.) are found on Gutenberg's GitHub issue, to which I've linked to in my first reply on this issue.

**Comment by sybrew** [comment]
WordPress 5.2.1 fixed this issue.
