### ISSUE TITLE
qTranslate X sub-directory translation path adds multiple directories.

### ISSUE THREAD

**Issue by sybrew** [sybrew/the-seo-framework#43]
From [ctw12's support thread](https://wordpress.org/support/topic/wrong-canonical-url-on-homepage/):

qTranslate X subdirectory option currently adds multiple sub-directories to the Canonical URL since The SEO Framework 2.7.0 update's URL generation rework.

Expected:
`http://example.com/en/`

Actually output:
`http://example.com/en/en/en/`

**Comment by jobbyx** [comment]
Hi!

Any news regarding this bug? Fixing it would help me out big time.

Thanks!

**Comment by sybrew** [comment]
Hi jobbyx,

The biggest changes (features, that is) have been implemented last week. And in the past half year the code cleanup + PHP5.3 shift + performance optimizations have also been completed.

This means I can finally start working out those nasty bugs 😄. You'll be notified (if you're subscribed to this thread) automatically when the fix is implemented.

Cheers!
