### ISSUE TITLE
Filter to add external sitemap.

### ISSUE THREAD

**Issue by janeks** [sybrew/the-seo-framework#430]
Is there a filter that can be used to add external sitemap? Similar to Yoast `wpseo_sitemap_index` filter.

**Comment by sybrew** [comment]
Hi @janeks 

TSF doesn't have support for a sitemap index (yet, see #31). As such, you can't point to them via TSF.

However, you can add another sitemap to your WordPress site, and register the endpoint (e.g. `example.com/news-sitemap.xml`) with Google and Bing.
1. Google: https://support.google.com/webmasters/answer/183668?hl=en
2. Bing: https://www.bing.com/webmaster/help/how-to-submit-sitemaps-82a15bd4

**Comment by sybrew** [comment]
Reopening as a feature request.

**Comment by sybrew** [comment]
In the upcoming commit, a filter will be added; which paves the way to add your sitemaps:
`the_seo_framework_sitemap_endpoint_list`

```php
add_filter( 'the_seo_framework_sitemap_endpoint_list', function( $list ) {
	$list['mine'] = [
		'endpoint' => 'sitemap-mine.xml',
		'regex'    => '/^sitemap\-mine\.xml/',
		'callback' => 'my_output_sitemap_callback',
	];

	return $list;
} );

function my_output_sitemap_callback() {

	the_seo_framework()->clean_response_header();

	if ( ! headers_sent() ) {
		\status_header( 200 );
		header( 'Content-type: text/xml; charset=utf-8', true );
		header( 'X-Robots-Tag: noindex, follow', true );
	}

	// Output sitemap content here... either via file streaming or other means of output.
	// Example: https://www.php.net/manual/en/function.stream-get-contents.php

	echo "\n";

	exit;
}
```

Optionally, by extending the [Sitemap builder object](https://github.com/sybrew/the-seo-framework/blob/master/inc/classes/builders/sitemap.class.php), you can quickly generate URLs by looping over post IDs via the `generate_url_item_values()` method; however, this is meant for basic sitemaps only. Moreover, depending on your requirements, you may wish to use `build_url_item()`, or create your alternative thereof.
