### ISSUE TITLE
Duplicate Title

### ISSUE THREAD

**Issue by WulfmanGer** [sybrew/the-seo-framework#439]
TSF duplicated my <title> ...

WP-Settings:
Title Website: My Name
Subtitle: My Subtitle ;)

TFS: Setting Homepage
Meta-?? (German Version: Metatitel-Zusätze): My Subtitle
Meta-Title: My Subtitle | My Name

<title> Now:
My Subtitle | My NameMyName | My Subtitle

Sorry for my english ... you can see this live @ https://www.platzeck.net/

If you go to an Article:
<title> Now:
Article-Name | MyNameMyName

=> Where's the mistake? I have now tried several possibilities in TFS ... negative. The "best" way is to delete "Title" and "Subtitle" in the WP settings - only then do I have other errors on the page :) - Not really an solution :( ... an change in TFS is not posible - no text = use WP-Default ... (=> which produce duplicate title)

**Comment by sybrew** [comment]
Hi @WulfmanGer, 

The Twenty Ten is a 9-year-old theme, and it still uses the infamous broken title standard. 
It forever will use that, too, thanks to WordPress' stance on backward compatibility.

What this means is explained on the free [Title Fix extension page](https://theseoframework.com/extensions/title-fix/).
That free extension also resolves the issue you're facing.

**Comment by sybrew** [comment]
I see you've been able to fix it 😄 cheers!
