### ISSUE TITLE
Unable to get correct canonical url from the REST API

### ISSUE THREAD

**Issue by k1sul1** [sybrew/the-seo-framework#444]
So I digged around a bit and managed to write the following snippet that adds SEO data to the API responses, which I can use in my React frontend.

```
// foreach all rest enabled post types 
    register_rest_field($type->name, 'seo', [
       'get_callback' => '\k1\REST\getSeoData',
    ]);
// end foreach

function getSeoData($post) {
  if (function_exists("the_seo_framework")) {
    $id = $post['id'];
    $seo = the_seo_framework();

    return [
      'title' => $seo->get_title($id),
      'description' => $seo->get_description($id),
      'og:description' => $seo->get_open_graph_description($id),
      'og:title' => $seo->get_open_graph_title($id),
      'og:image' => $seo->get_social_image_url_from_post_thumbnail($id),
      'canonical' => $seo->get_canonical_url(['id' => $id]),
    ];
  }

  return false;
}
```

This works as expected, except get_canonical_url doesn't get the custom canonical url I defined from /wp-admin. Am I doing something wrong or is there a bug somewhere?

**Comment by sybrew** [comment]
Hi @k1sul1 

`get_canonical_url()` shouldn't be called directly when you supply input parameters, because there's an index that is missing that most other API functions don't have: `get_custom_field`.
```php
@param array|null $args : Private variable. Use $this->create_canonical_url() instead.
```

So, this would do better:
```phpdoc
[
    'canonical' => $seo->create_canonical_url( [ 'id' => $id, 'get_custom_field' => true ] ),
]
```

--------------

P.S. get_social_image_url_from_post_thumbnail() will be deprecated in the next major release (v3.3.0).
This is the proposed alternative when you exclusively want the post thumbnail URL:
```php
$url = \The_SEO_Framework\Builders\Images::get_featured_image_details(
	[
		'id'       => $id,
		'taxonomy' => '',
	]
)->current()['url'];
```

**Comment by k1sul1** [comment]
Cheers! I'll try those tomorrow. 

Are you planning on adding this kind of functionality to the core of this plugin? I've added it to [my "toolkit"](https://github.com/k1sul1/k1kit) but it would be great if I didn't have to.

**Comment by k1sul1** [comment]
The canonical part works :+1: 

When I tried to apply the "patch" for the image, I got 

```
NOTICE: PHP message: PHP Warning:  require(/var/www/wp/wp-content/plugins/autodescription/inc/classes/builders/images.class.php): failed to open stream: No such file or directory in /var/www/wp/wp-content/plugins/autodescription/bootstrap/load.php on line 148
wordpress    | NOTICE: PHP message: PHP Fatal error:  require(): Failed opening required '/var/www/wp/wp-content/plugins/autodescription/inc/classes/builders/images.class.php' (include_path='.:/usr/local/lib/php') in /var/www/wp/wp-content/plugins/autodescription/bootstrap/load.php on line 148
```

As the error states, that class doesn't exist. (Yet?). Running 3.2.4.

**Comment by sybrew** [comment]
I'm glad that worked!

That's correct. The class doesn't exist yet. 

It'll work like that from v3.3.0, which has yet to be released; it's still in development, the beta launch should be either this or next week.

**Comment by evanlesmez** [comment]
Is there an equivalent for "set_title" or "set_description"?

**Comment by sybrew** [comment]
There's no setting going on here, only getting.

Please stick to [your topic](https://github.com/sybrew/the-seo-framework/issues/620) if you have more specific questions.
