### ISSUE TITLE
Author Archive - property="og:image" (Use Gravatar Image)

### ISSUE THREAD

**Issue by royashgit** [sybrew/the-seo-framework#447]
For author archive pages the plugin automatically outputs the fallback image. 

`<meta property="og:image" content="https://www.example.com/fallback.jpg" />`

Instead we would like to output the gravatar image for each author.  For example we use this code to output the gravatar on the authors page:

`<?php echo get_avatar( get_the_author_meta( 'ID' ), 256 ); ?>`

How could we modify with a function to achieve this requirement?

many thanks,
Andrew

**Comment by sybrew** [comment]
Hello!

My apologies for leaving you in the dark, I had to conduct some research beforehand.

Below will be the code you'd want to use when The SEO Framework v3.3 or later is released. Now, I couldn't be bothered writing code that'll soon stop working; the next update is around the corner, after all.

Note that, unfortunately, we can't detect whether the author has a Gravatar set without calling the Gravatar server first. Doing so will cause unwanted delays during page generation. 

To mitigate this issue, we'd want to store the response in your database. I chose not to include that.

```php
\add_filter( 'the_seo_framework_image_generation_params', 'my_tsf_custom_image_generation_args', 10, 2 );
/**
 * Adjusts image generation parameters.
 *
 * @param array      $params : [
 *    string  size:     The image size to use.
 *    boolean multi:    Whether to allow multiple images to be returned.
 *    array   cbs:      The callbacks to parse. Ideally be generators, so we can halt remotely.
 *    array   fallback: The callbacks to parse. Ideally be generators, so we can halt remotely.
 * ];
 * @param array|null $args The query arguments. Contians 'id' and 'taxonomy'.
 *                         Is null when query is autodetermined.
 * @return array $params
 */
function my_tsf_custom_image_generation_args( $params, $args ) {

	if ( null === $args ) {
		// In the loop.
		if ( \is_author() ) {
			// Register our Gravatar callback.
			$params['cbs']['gravatar'] = 'my_tsf_custom_gravatar_generator';
		}
	} else {
		// Out the loop. Author queries can't be performed externally.
		// Therefore, do nothing.
	}

	return $params;
}

/**
 * Generates image URL and ID via Gravatar.
 *
 * @generator
 *
 * @param array|null $args The query arguments. Accepts 'id' and 'taxonomy'.
 *                         Leave null to autodetermine query.
 * @param string     $size The size of the image to get.
 * @yield array : {
 *    string url: The image URL location,
 *    int    id:  The image ID,
 * }
 */
function my_tsf_custom_gravatar_generator( $args = null, $size = 'full' ) {

	$author_id = isset( $args['id'] ) ? $args['id'] : \the_seo_framework()->get_the_real_ID();

	// N.B. get_avatar_data and get_avatar_url expect the 'size' index to be an integer. We can't use $size here.
	$data = get_avatar_data(
		$author_id,
		[
			'size'   => 512, // Let's get something more crisp.
			'scheme' => \the_seo_framework()->get_preferred_scheme(),
		]
	);

	yield [
		'url' => $data['url'],
		'id'  => 0, // Only pass an ID when the image is hosted on THIS site.
	];
}
```

**Comment by royashgit** [comment]
Hello, thanks for the detailed answer. I will wait for the 3.3 update!

To clarify, all authors will have a gravatar image and yes we want to avoid making things slow. 

I suppose this function works on the server level and Facebook will properly display the authors image when the page is shared. 

This can be tested on this page: https://developers.facebook.com/tools/debug/

**Comment by sybrew** [comment]
Hello! Now TSF v4.0 is released, that snippet should work. If you have other requests, please open a new issue :) Cheers!
