### ISSUE TITLE
Meta-title at the start page adds itself to the main title

### ISSUE THREAD

**Issue by JSBmanD** [sybrew/the-seo-framework#452]
**Describe the bug**
I have meta-title for start page set up. When you look at the title at the start page it will consist "meta-title+title" without spacing or anything.

**How to reproduce the bug**
1. Go to meta-title setup
2. Make it
3. Update start page and look at the title

**Expected behavior**
If meta-title appears, it should remove main title from the string or at least add space between.

**Screenshots**
![bug](https://user-images.githubusercontent.com/5402335/62825884-54f2fd80-bbbb-11e9-87f8-4eb2f5774439.png)
As you can see there's no space after second "|" and the same text appears twice.

**Additional context**
Last WP and plugin version. Title fix extension doesn't seem to be working.

**Comment by sybrew** [comment]
Hello!

Thank you for opening this issue!

If it doesn't have a space between the separators, then it's not added by TSF.

Have you tested for plugin/theme conflicts yet (by deactivating them)? There may be one activated that uses the `pre_get_document_title` filter for the homepage. 

We try to deactivate all hooks for that filter at `init`, but one may have been registered on or after that action, which is rare.

**Comment by JSBmanD** [comment]
Thanks, Better AMP was adding string, after changing plugin everything works.
