### ISSUE TITLE
Conflict with Jetpack (and other plugins) causing PHP warnings

### ISSUE THREAD

**Issue by aheckler** [sybrew/the-seo-framework#453]
**Describe the bug**

Jetpack assumes that `$shortcode_tags` is an array, since it's defined as such in WP core. However, The SEO Framework unsets it here:

https://github.com/sybrew/the-seo-framework/blob/3.2.4/inc/classes/sitemaps.class.php#L257-L267

This will cause PHP warnings since any plugin that relies on any of these globals for the page view of the sitemaps will not get the default value of what they expect.

The error we're seeing is: `[09-Aug-2019 18:03:58 UTC] PHP Warning: array_keys() expects parameter 1 to be array, null given in /home/myuser/public_html/wp-content/plugins/jetpack/vendor/automattic/jetpack-sync/src/Functions.php on line 36`

**How to reproduce the bug**
1. Install & activate Jetpack.
2. Turn off Jetpack's Sitemaps feature.
3. Install SEO Framework plugin.
4. Activate the SEO Framework sitemap instead.
5. See your debug.log file.

**Expected behavior**
No warnings.

**Screenshots**
N/A

**Additional context**
We have a "defensive" PR ready for inclusion in Jetpack here:

https://github.com/Automattic/jetpack/pull/13219

But maybe there's something you can do from the SEO Framework side?

**Comment by sybrew** [comment]
Thanks for doing dedicated research on this! 😄 

I already fixed this last June for the upcoming TSF v4.0 update (ETA within three weeks) as I bumped into this issue internally. I now use [remove_all_shortcodes()](https://developer.wordpress.org/reference/functions/remove_all_shortcodes/) instead. 

See: https://github.com/sybrew/the-seo-framework/commit/da33f663de97439b600b269016d4079c8899c1c2#diff-818889a7b6451244983ffec8b63dfd0e

I think you can drop https://github.com/Automattic/jetpack/pull/13219. PHP warnings are useful for finding bugs.

**Comment by aheckler** [comment]
Thanks!
