### ISSUE TITLE
Setting nofollow for entire site does not work

### ISSUE THREAD

**Issue by uok** [sybrew/the-seo-framework#455]
Thanks for this great plugin!

**How to reproduce the bug**
Set noindex and nofollow for entire page.
Noindex works, nofollow does not.

TSF 3.2.4

**Comment by sybrew** [comment]
It was a mess. It was fixed in a rework at https://github.com/sybrew/the-seo-framework/commit/2211aecb3fe6048930dd6079dc1570f86823f58e#diff-d0a013bfb3ed466eb7205c9ffeb0a1f9.

According to the changelog, these fixes were applied in that commit.
```md
* The global site-wide `noindex` option no longer sets `nofollow` automatically, too. Albeit, that's implied.
* The global site-wide `nofollow` option now has an effect.
* The global category and tag `noarchive` options now have an effect.
* The global category and tag `noindex` options no longer set `noarchive` automatically, too. Albeit, that's implied.
```

**Comment by uok** [comment]
Thanks & have a nice weekend!
