### ISSUE TITLE
Meta Tag Canonical displaying wrong URL.. how to change it ?

### ISSUE THREAD

**Issue by Wbz69** [sybrew/the-seo-framework#458]

**Comment by Wbz69** [comment]
Many pages on my site showing 1 same URL as canonical page.
However those pages are all different...

https://www.example.com/training/be-strong
> canonical = https://www.example.com/this-page-01

https://www.example.com/training/be-smart
> canonical = https://www.example.com/this-page-01

It is generating many issues with correct indexing and link sharing... Facebook gathering the meta data of the Canonical URL when the URL is shared (so wrong image, wrong title...).

Is there any way to manage this issue with the plugin ?
It seems to me that this feature is automated...

**Comment by sybrew** [comment]
Hello!

Yes, this feature is automated. I assume you're referring to pages that are built from a shortcode? Do you have a plugin name for me?

Those types of pages have complete disregard for the WordPress API. The developer of those should actively communicate with WordPress and overwrite its information; only then we can relay the correct data. 

Instead, most of these plugins plug into higher-level systems (adding needless layers of plugin compatibility, like for Yoast SEO), instead of fixing the lower-level WordPress API.

WordPress mostly generates the canonical URL we use&mdash;after all; we only touch up the scheme and secure it against SEO attacks.

**Comment by Wbz69** [comment]
Hey !
Thanks for answering quick... (I may have double my question[ in another thread ](https://wordpress.org/support/topic/canonicals-missing-how-can-i-fix/#post-11856000))

This issue concerns mostly pages custom made from WooCommerce products types and Moodle.

I forgot to mention, I was working with a multisite managing 2 subdmains, so the url :
**https://www.one.site.com/training/be-strong**
showing the following canonical:
**https://www.two.site.com/this-page-01**

I read on another thread I can set the page on **noindex** to 'kill' the canonical url... however it also kills seo optimization and indexing !

However, the SEO plugins seems to only manage 1 site.... 
I understand your position regarding Wordpress API (and that's the reason I chose this plugin on all my sites).
Maybe we have to develop a custom solution for this particular case...

**Comment by sybrew** [comment]
Yes, you have infiltrated on that topic ;)

I'm a bit lost on your findings. I think I need an URL to your site to inspect this. In any case, I think we have a workaround ready for you, via the snippet below.

So, if you want to disable the canonical meta tag for a set of pages, please implement this filter:
```php
add_filter( 'the_seo_framework_rel_canonical_output', function( $url, $id ) {

	// Supply an array of IDs you'd wish to disable the URL for.
	$excluded_ids = [ 42, ];

	if ( is_singular() ) {
		if ( in_array( $id, $excluded_ids, true ) ) {
			$url = '';
		}
	}

	return $url;
}, 10, 2 );
```

**Comment by Wbz69** [comment]
@sybrew Thanks a lot... I will try this asap.

Here are somme urls with this issue...
**Main URL :**
https://campus.odbi.fr/formation/etre-createur-de-sa-performance-silvia-janostinova/

**Canonical URL:**
https://academie.odbi.fr/protocoles-de-coach/

And when I use the **[Facebook Debugger tool]**(https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fcampus.odbi.fr%2Fformation%2Fetre-createur-de-sa-performance-silvia-janostinova%2F) the information displayed is from the canonical url.

**Comment by sybrew** [comment]
Thanks for the links!

Yes, I see you're using the plugin: "OptimizePress." It also outputs SEO tags; these are conflicting with the ones from TSF.

I did some browsing on your site, and only the pages created with OptimizePress are behaving oddly. In the current state, I don't think any SEO plugin will work nicely with OptimizePress.

Keep in mind that OptimizePress is a paywall-gated plugin, so I can't help you further with this issue. Creators not honoring our approach of open source are hard to deal with, and I must draw a line somewhere.

Disabling SEO for those pages and letting Google figure it out seems like the best approach. Or, drop it altogether and use a page builder that does integrate well with WordPress, like Gutenberg, Elementor or Beaver Builder, instead.

As an aside, I see your server doesn't support opcode caching and is probably using an insecure version of PHP (5.6). Contact your hosting provider on enabling opcode caching (i.e., OPcache), and your site will be ~60 times faster. Also, when you upgrade to PHP 7.0, your website will be ~20 times faster. And when you upgrade to PHP 7.3, your website will be ~30 times faster.

This is all I can do from here. Please consider my suggestions above. Have a nice weekend 😃

**Comment by Wbz69** [comment]
Wow... thanks for the time you spend on checking and answering my issue... a rare kind of dev :) !
I knew Optimize Press could cause SEO issues... I'll take on everything you wrote and will convince the tech guy !
Thks again
