### ISSUE TITLE
Sitemap dynamic generation?

### ISSUE THREAD

**Issue by majestica** [sybrew/the-seo-framework#460]
Hi, please tell me your plugin generates a sitemap on the fly? If I have 200,000 posts on my site, generating a site map can take a lot of time, could you add support for wp cli, we can create a sitemap by cronjob via wp cli at night, so that clients have a static site map. 

P.S The way I look at a physical file does not exist (sitemap.xml virtual), so what should I do (

**Comment by sybrew** [comment]
Hello!

Yes, TSF's sitemap is virtual and generates when requested. It may use transient caching to store the output.

From TSF v4.0 (ETA: this month), the sitemap will take an X number of posts, sort them by last updated, and creates sitemap URL entries for it. We sort the posts descending by last-updated date; so, the latest post updated will be on top. That's all you need to notify search engines on your most recent posts.

For pages, it'll take all pages and orders them ascending by publishing date. So, the first page you created should be on top.

Once a search engine knows a page or post has been updated, the sitemap is rendered redundant, and older posts may as well be purged from it.

You can define the number of posts via the SEO Settings. The maximum number of allowed posts are 50,000, as [per Google's guidelines](https://support.google.com/webmasters/answer/183668).

We also store the results in your database via transient caching. It can be invalidated and replaced when you update a post. It'll also be removed automatically after seven days of no updates.

If you wish to use precaching, all you need is to run an HTTP query to your sitemap to generate and store it. Send the request to `/dev/null` to ignore the response. If you don't publish new posts daily, then I recommend binding the cron-initiation to the WordPress `save_post` action.

For example, using wget, this is how the cron command should look like:
```
wget -q -O - https://example.com/sitemap.xml >/dev/null 2>&1
```

We don't have dedicated CLI support for generating the sitemap, as the caching is controlled via a [display view-file](https://github.com/sybrew/the-seo-framework/blob/18f048707aaef8f911deba8d7bb7c374af56cdfa/inc/views/sitemap/xml-sitemap.php).
