### ISSUE TITLE
Canonical missing on woocommerce product pages

### ISSUE THREAD

**Issue by extremeshok** [sybrew/the-seo-framework#462]
**Describe the bug**
Canonical missing on woocommerce product pages

**How to reproduce the bug**
View the source of a woocommerce product page, <link rel="canonical"  is missing

**Expected behavior**
<link rel="canonical" href="https://siteurl.com/" />

**Comment by sybrew** [comment]
Hello!

Thanks for opening a bug report. Alas, this is an intended feature.

Since TSF v3.2.4, canonical URLs are removed when the page has the `noindex` robots-setting applied and when the canonical URL doesn't point to another page. This helps speeding up deindexing of pages.

See #370

**Comment by extremeshok** [comment]
why would product pages have the noindex applied to them ? This would make zero sense

Every online shop wants the products to be indexed.

Google bots are happily indexing the page and then reporting the <link rel="canonical" is missing

**Comment by sybrew** [comment]
Hi @extremeshok,

I don't know why they're marked for `noindex`. There may be a setting enabled unintentionally. What does the SEO Bar say when you hover over the `I`?

If you wish for me to investigate, could you send me a screenshot of what Google has found and one or multiple links to the affected pages? You may do so confidentially, via [our contact page](https://theseoframework.com/contact/).

Thanks!
