### ISSUE TITLE
Add title & description input fields for quick-edit.

### ISSUE THREAD

**Issue by sybrew** [sybrew/the-seo-framework#464]
Previous: #155

Per [Oksana's request](https://wordpress.org/support/topic/bulk-edit-titles-metadescription/):

We want to add quick-edit options for the title and description fields.

Currently, the API doesn't allow us to implement this faultlessly. We have to figure out:
1. How to implement the pixel and character counters.
1. How to implement the floating title prefixes and affixes.

**Comment by SchneiderSam** [comment]
Love that!

**Comment by sybrew** [comment]
Implementing this feature requires an overhaul of the `description.js` and `title.js` files, where their augmentations must become iterable, instead of expecting a single input field of their sorts on the page.

The biggest issue is that we'll need to maintain backward compatibility, where the "legacy" fields without iteration remain accessible. We'll also need to rethink forwarding data to the scripts; performance is also an issue.

Nevertheless, implementing this will make implementing #20 a breeze later.

I'm now halfway through the implementation (titles don't work yet):
![image](https://user-images.githubusercontent.com/7662236/86512872-f273a300-be05-11ea-890d-a86499ff51ed.png)

A big commit will follow. Feedback is appreciated 😃
