### ISSUE TITLE
Tabs in setting menu are not working

### ISSUE THREAD

**Issue by tsmedienagentur** [sybrew/the-seo-framework#471]
I have a problem with the tabs in the setting menu.
They're not working. I can't select them. It shows me just the first tab of every setting section.

I already disabled all plugins and themes. I'm using Wordpress 5.2.3 and The SEO Framework 4.0.1.

Here are the errors I'm getting in the console:

![error1](https://user-images.githubusercontent.com/42976722/65123814-5e5e5980-d9f4-11e9-9b04-d498c1f632cc.PNG)
![error2](https://user-images.githubusercontent.com/42976722/65123815-5e5e5980-d9f4-11e9-8978-96934ceaa379.PNG)
![error3](https://user-images.githubusercontent.com/42976722/65123816-5ef6f000-d9f4-11e9-933a-4a0b558c77f3.PNG)

**Comment by sybrew** [comment]
Hello!

Your server's firewall is acting up and halts script loading, sending an HTTP 403 error: Forbidden.
Please contact your hosting provider; those images should tell them enough on how to resolve this for you.

**Comment by tsmedienagentur** [comment]
Hello,

I finally found the problem.
It was the new 7G Firewall for Security. i changed it back to 6G Firewall and everything works fine now.
