### ISSUE TITLE
Open/close SEO settings panels doesn't work on Chrome Windows 10

### ISSUE THREAD

**Issue by wjadevries** [sybrew/the-seo-framework#472]
I opened and closed panels on my iPad, and then opened WordPress on my Windows 10 PC. 
The panels were open/closed as I left them on my iPad.
But on my Windows 10 PC I cannot open/close the panels on Chrome.

The tabs are also not working on Chrome desktop (they are working on my iPad).
![2019-09-19_20-22-26](https://user-images.githubusercontent.com/38012502/65271684-ec822f00-db1d-11e9-97f8-3e6e1cc729fe.jpg)

**Comment by sybrew** [comment]
Hi @wjadevries 

Please see our collection on resolutions for these kinds of errors after upgrading:
https://wordpress.org/support/topic/4-0-admin-interface-not-loading-correctly/

If those don't help, let me know!
