### ISSUE TITLE
Page SEO Settings blocking page editor text when scrolling

### ISSUE THREAD

**Issue by wjadevries** [sybrew/the-seo-framework#473]
In Chrome on my PC the Page SEO Settings isn't staying on the bottom if I scroll down, which means it's blocking my editor.
It works fine on my iPad.
![2019-09-19_20-37-22](https://user-images.githubusercontent.com/38012502/65271742-0e7bb180-db1e-11e9-8bd6-9d6f76f0d911.jpg)

**Comment by sybrew** [comment]
This is an issue with WordPress 5.0~5.2.3 and Chrome 77.0.3865.75. It is fixed in both Chrome 77.0.3865.90 and WordPress 5.3.

Tip: You can invoke a Chrome update when you go to this URL: `chrome://help`, or go to “**⋮** -> Help -> About.”
