### ISSUE TITLE
Homepage title is wrong

### ISSUE THREAD

**Issue by nullfud** [sybrew/the-seo-framework#475]
The homepage title is wrong, when i search for nullfud, or authentic crypto news, it shows the following title in google:

nullFUD: Authentic Crypto News

Even though it's set to Authentic Crypto News - nullFUD (thats the name of the site once it's visited)

I am using premium, and the title fix is enabled. Please fix this.

**Comment by sybrew** [comment]
Answered here: https://github.com/sybrew/The-SEO-Framework-Extension-Manager/issues/16#issuecomment-533984160
