### ISSUE TITLE
BuddyPress post-meta variable conflicts

### ISSUE THREAD

**Issue by lqdforce** [sybrew/the-seo-framework#479]
Accessing buddypress Member pages throws warnings about TSF's post-data.class.php file.

go to Buddypress
list all members page
click any username
see warnings
expected to see no php warning on post type that buddypress uses for its member pages.
well, these should all be excluded from any seo/robots/sitemap anyway, for privacy, but that's not directly related to the scope of this project.

warning code:
Warning: array_intersect_key(): Expected parameter 1 to be an array, bool given in //public/wp-content/plugins/autodescription/inc/classes/post-data.class.php on line 115

Warning: Invalid argument supplied for foreach() in //public/wp-content/plugins/autodescription/inc/classes/post-data.class.php on line 120

Warning: array_merge(): Expected parameter 2 to be an array, null given in //public/wp-content/plugins/autodescription/inc/classes/post-data.class.php on line 124

disabled all wordpress plugins, set theme to twenty nineteen, same issues apply.
the 3 warnings are repeated over and over on those pages, listed almost 30 times.
otherwise, functionality.
also tried rolling back buddypress to 4.4.0 , no good. not sure where this is coming from.

**Comment by sybrew** [comment]
Duplicate: https://wordpress.org/support/topic/buddypress-5-0-php-warnings-referring-to-tsf-post-data-class-php-on-member-page/

Earlier: https://wordpress.org/support/topic/buddypress-errors-on-multivendor-website-after-the-update/

**Comment by sybrew** [comment]
From [my reply on the w.org forums](https://wordpress.org/support/topic/buddypress-5-0-php-warnings-referring-to-tsf-post-data-class-php-on-member-page/#post-12003035):

> Instead of relying on WordPress for handing us valid post objects, we test the post object a little more intimately.

> I found that when utilizing this trick, we could automatically add invalid-query-detection support, which very much eliminates all compatibility issues caused by “not-really-WordPress” solutions. So, for example, your titles are also correct again, without having to intervene.

Doing that addresses the statement made here: https://github.com/sybrew/the-seo-framework/issues/176#issuecomment-425440994
