### ISSUE TITLE
Auto-generated description doesn't show shortcodes from the_excerpt()

### ISSUE THREAD

**Issue by hmaesta** [sybrew/the-seo-framework#489]
### 🐛 **Describe the bug**
WordPress allows the use of shortcodes on the excerpt using:
```
add_filter( 'the_excerpt', 'shortcode_unautop');
add_filter( 'the_excerpt', 'do_shortcode');
``` 

That means you can programmatically return data in `the_experct()` function, the source of the auto-generated description by TSF. 

While using `the_experct()` or `get_the_experct()` I can achieve the desired result, TSF just ignores the shortcodes.

### 🔍 **How to reproduce the bug**
1. Add the following code to `functions.php`:
```
add_filter( 'the_excerpt', 'shortcode_unautop');
add_filter( 'the_excerpt', 'do_shortcode');

function shortcode_example_func() { return 'YEAH!'; } 
add_shortcode('shortcode_example', 'shortcode_example_func');
```
2. Create a post with the following content on the Excerpt: 
```
That's just a [shortcode_example] test.
``` 
3. Where `the_excerpt()` is called, the result is: `That's just a YEAH! test`, while on the page source you can see that on descriptions tags generated by TSF the result is: `That's just a test.`

### 🏆 **Expected behavior**
The expected behavior is that the descriptions tags generated by TSF shows the same content of `get_the_excerpt()` - with the content of shortcodes.

**Comment by sybrew** [comment]
I love how you set up this issue! 🏆 

We avoid using the `get_the_excerpt()` function because it's a templating function. So, we pull the raw excerpt from the post instead. Therefore, the default templating filters won't work. 🛑 

Now, we have a implemented a filter for just your use-case. 🚀 
```php
add_filter( 'the_seo_framework_allow_excerpt_shortcode_tags', '__return_true' );
```

The shortcodes must be registered at `init`, without an admin-bias, to also show as effective in the description input-field-placeholders. 🤔 

I hope this helps! Cheers 🙌

**Comment by hmaesta** [comment]
Thank you for the fast response, Sybre! Emojis can be a great way to improve readability. 

Unfortunately, I couldn't manage to make it work. 😣

The first snippet showed the plain shortcode, as you mentioned – and the second one did not make any difference. 

I moved all the code to the top of `functions.php`, without any success.

**Comment by sybrew** [comment]
Hi @hmaesta! 

I accidentally handed the wrong filter previously, which was for custom meta descriptions, not generated descriptions. So, I must've edited it after you already implemented the wrong one. 

Does the revised filter work?

**Comment by hmaesta** [comment]
Oh, that's right. I implemented the wrong one.
Now it's working like a charm. **Thank you!** 🙌

_Just one more thing..._

Some excerpts are a little longer, for example:
> Is this a great article? I think that yes, it is. But some people may not like it. For example, we have [likes quantity="500"] likes on this article.

The problem is sometimes the plugin may breakdown the description because it's too long – and it breaks in the middle of the shortcode, generating something like:
```
<meta name="description"
      content="Is this a great article? I think that yes, it is. But some people may not like it. For example, we have [likes quantity=&#8221;500&#8221;" />
```
Is it possible to avoid this?

**Comment by sybrew** [comment]
Oh, that completely slipped my mind!

Yes, that's possible. Exchange the previous `do_shortcode()` filter with this one: `the_seo_framework_fetched_description_excerpt`. It's a legacy filter, so the parameters are shifted.

To summarize, this is all that you need to implement to make this all work:

```php
add_filter( 'the_seo_framework_allow_excerpt_shortcode_tags', '__return_true' );
add_filter( 'the_seo_framework_fetched_description_excerpt', function( $excerpt, $deprecated, $args ) {
	return do_shortcode( $excerpt );
}, 10, 3 );
```

Then, TSF will parse the excerpt after the shortcode is rendered.

**Comment by sybrew** [comment]
Hi @hmaesta 

Sorry for the confusion. In the latest edits of my previous comment, I added the tried-and-tested code. Cheers!

**Comment by hmaesta** [comment]
Now it's perfect! 🏆
That was the best issue I have ever opened on Github – and I am even counting the ones I open to resolve it myself. 

Sorry to make you lose some time with the last problem... 😅

Thank you, Sybre. Have a great day! 👋

**Comment by sybrew** [comment]
It's was my pleasure. 😃 

Have a great day too! 👋
