### ISSUE TITLE
Add 302 redirect option to posts & pages

### ISSUE THREAD

**Issue by phrench** [sybrew/the-seo-framework#49]
Despite what Google officially is saying, it seems 302 pass more link juice than 301. See http://www.linkresearchtools.com/case-studies/11-things-didnt-know-links-redirects/

Any chance you can add a 302 redirect option in addition to the 301 redirect option?

**Comment by sybrew** [comment]
HI @phrench,

As they are, as well as I, still skeptical about the results of their findings; it seems to be just a fluke. 
And I'll definitely will check into this and I will keep my eye out; however, it's far from the recommended guidelines.

A 302 redirect "extra option" would be nice, but it's also quite at the advanced side of things, and Google might eventually even fix this fluke, and we'll be worse off from it.
I'll leave this open and we'll see what others think :).

**Comment by sybrew** [comment]
Hi @phrench,

A filter is on its way. I do not believe this should be in the hands of novice users just yet.

The filter:
`the_seo_framework_redirect_status_code`

Example:
`add_filter( 'the_seo_framework_redirect_status_code', function() { return 302; } );`

**Comment by phrench** [comment]
Hi @sybrew 

Great news! I set my 302s by using a redirection plugin.

Regarding novice users: Same could be said for the noindex checkbox, canonical and the 301 itself. I think it makes perfectly sense to offer a choice for the redirect: 301, 302 or 307.

You can still add a warning or tooltip.

PS: Thanks for your plugin, I'm using it already on 30+ sites. Please make sure upgrades are always non-destructive and don't require user input since I have auto-update enabled.

**Comment by sybrew** [comment]
Hi @phrench,

That's correct: the same could be said about those options. However, the 302's being beneficial is based upon out-of-the-ordinary experiments. So maybe my word choice for "novice" wasn't correct; shall I say "rather conventional" 😄?

In general, many of those Robots and Canonical options shouldn't be touched. However, if I look at how I set up my own site's pages; I activate those so often I don't believe they should be exclusive:
![image](https://cloud.githubusercontent.com/assets/7662236/21722225/f02cadc0-d42b-11e6-9f6a-4dfdd86cc9fc.png)

Every extra option makes it more difficult for the end-user to use the plugin and control its website. Especially when it comes to ***every single post***: less is more.
https://wordpress.org/about/philosophy/ - Decisions, not options.

Nevertheless, a filter is a great start for any new and rather nonconforming optimization, so the tech-savvy users among us can experiment before it going live.

About the auto-update: I always make sure I perform a full "update-routine" before I publish big updates. 
Please keep in mind that 2.8.0 will no longer support PHP 5.2. That too should be handled (thanks for reminding me!).

**Comment by sybrew** [comment]
Smooth upgrade is now in place: https://github.com/sybrew/the-seo-framework/commit/807ececf839cb9360f8a7ac30b34dc61c0f800aa :)

**Comment by phrench** [comment]
That's what advanced SEO is about: Trying different things and pushing boundaries ;)

I run a lot of onpage and offpage experiments and while everybody is using 301 just because it gets mentioned everywhere, there's better options than those best practices. I mean let alone canonical is so powerful and gives you so many possibilities. But you never read about this. Which I like.

Just to be clear: I'm using a Wordpress bulk management dashboard which handles the updates on the connected WP sites. Not sure how native auto-updates is related to this.

Yes, luckily the bulk management tool allows to execute custom PHP code on all connected sites. All my hostings are at least PHP 5.3

Thanks!

**Comment by sybrew** [comment]
301 still is the standard, that 302 might work better is still an unknown (but rather welcome) side-effect. I'm just not ready to embrace it yet. Reasons for are mentioned in my previous replies.

>Not sure how native auto-updates is related to this.

Any update is related to this, that's in the magic of semantic programming 😄. Even your bulk management tool should work flawlessly.

Cheers 😄

**Comment by sybrew** [comment]
I'm closing this issue because:
1. The filter has been implemented. Feel free to use it!
2. It's risky business. It's always best to follow the standards and guidelines; regardless of (single use case) testing results.
3. I'm white-hat, and so is The SEO Framework 😄. Abusing SEO is a nice way towards upgrade your website to a [Penguin petting zoo](https://en.wikipedia.org/wiki/Google_Penguin) for your visitors at Facebook, and Facebook only.
4. No feedback is coming in nor new tests have been conducted.
