### ISSUE TITLE
Option To Remove Blog Name From "General" and "Social" Tabs

### ISSUE THREAD

**Issue by btward79** [sybrew/the-seo-framework#493]
When you are in a single post. Looking at the SEO settings, the option "Remove the blog name? [?]" from the title is all or nothing. If you check the box, it removes the blog title from search and social. 

I find myself checking the box to update our social accounts, and then unchecking the box for SERP.

If you are able to have a "Remove the blog name? [?]" on the General tab and the Social tab that would be fantastic! Thanks for such a good piece of software.

**Comment by sybrew** [comment]
Hello!

We're going to implement a feature in the upcoming major update that removes them from all social titles. Would that satisfy your request? See: https://github.com/sybrew/the-seo-framework/issues/394

Moreover, if you manually fill in a social title, the blog name will also be removed. Essentially, the option is built into the text field. The Open Graph title carries over to the Twitter title, automatically.

**Comment by btward79** [comment]
Sybre,

Perfect. 

Though I have to admit your layout is so slick for some reason manually inserting the title slipped my mind. That will work for me if it saves some additional work on your end.

Have a blessed day sir.

Brandon
World Events and the Bible <https://worldeventsandthebible.com/>

**Comment by sybrew** [comment]
Thank you so much, Brandon. Have a blessed day yourself too!
