### ISSUE TITLE
The new core Sitemap for WP

### ISSUE THREAD

**Issue by SchneiderSam** [sybrew/the-seo-framework#495]
Any news for this new comming change?

https://make.wordpress.org/core/2020/01/27/feature-plugin-xml-sitemaps/

**Comment by sybrew** [comment]
I'll probably disable it when we know how to--nothing proposed is an improvement over TSF's, plus the interoperability with the robots-settings isn't present in a feasible manner.

**Comment by sybrew** [comment]
We're going to add limited support for this sitemap:
1. We'll let it run when TSF's (now called "optimized") sitemap(s) are disabled.
2. We'll add back its robots.txt entry when TSF's sitemap(s) are disabled.

No further enhancements are planned. This Core feature is redundant for TSF users, after all.
