### ISSUE TITLE
No images in sitemap

### ISSUE THREAD

**Issue by alanorth** [sybrew/the-seo-framework#5]
I'm used to having images get indexed explicitly via the sitemap, but noticed they don't appear in The SEO Framework's sitemap. It made me wonder if it's even necessary to explicitly list them, or if bots consume them reliably directly from the posts. What do you think, @sybrew?

**Comment by sybrew** [comment]
Hi Alan,

I recently posted a reply on a very related question right here:
https://wordpress.org/support/topic/regarning-google-news-sitemaimage-sitemap-and-video-sitemap?replies=3#post-8365456

I hope it will clear things up :). 
If not, let me know! Have a great day!

**Comment by sybrew** [comment]
To add onto that, bots aren't really good at fetching images from CSS (in my experience, none of my CSS images show up in Google), they do however take whatever's in their path through when inside the `<img>` tag.

**Comment by alanorth** [comment]
Yes, I think you're right. Аs long as Google can consume the post's HTML content in a structured way — and that the content has appropriate markup — then I suppose they will index the images too. Also, it seems the [image-specific stuff for sitemaps](https://www.google.com/schemas/sitemap-image/1.1/) might be Google specific anyways.

Happy to close this now. Thanks for the discussion!

**Comment by sybrew** [comment]
You're right! I am however considering the [Schema.org ImageObject (LD+Json)](https://schema.org/ImageObject), but that's not on the Roadmap as of yet.

A lot of things are coming over time! Stay tuned :)
