### ISSUE TITLE
please add Host: to robots.txt

### ISSUE THREAD

**Issue by antonmarin** [sybrew/the-seo-framework#50]
https://yandex.ru/support/webmaster/controlling-robot/robots-txt.xml?ncrnd=5966#host

**Comment by sybrew** [comment]
Hi @antonmarin,

This is already done through the Canonical URL. See [Use canonical URLs](https://support.google.com/webmasters/answer/139066?hl=en). 

I quote:

> [...]  With content syndication, it's also easy for content to be distributed to different URLs and domains entirely. For example:
>
> Your server is configured to serve the same content for the www subdomain or the http protocol.
> a) http://example.com/green-dresses (http)
> b) https://example.com/green-dresses (https)
> c) http://www.example.com/green-dresses (http + www)

In the next update you'll have more control over the HTTP/HTTPS hosts directive. www/non-www is already completely supported through the *Site Address (URL)* setting set in http://example.com/wp-admin/options-general.php.

I hope this explains it :) 

If this wasn't what you were looking for, let me know! Cheers!

**Comment by antonmarin** [comment]
I see.
As i understand it is not absolutely same for different search engines

**Comment by sybrew** [comment]
The canonical URL certainly works the same for all popular search engines:

https://yandex.com/support/webmaster/controlling-robot/html.xml#canonical
https://blogs.bing.com/webmaster/2011/10/06/managing-redirects-301s-302s-and-canonicals/

The hosts addition, alas, is currently only Yandex specific.

**Comment by antonmarin** [comment]
ok.
How add it manually? I searched for a file but not found (( File exists? Or it's a redirect?

**Comment by sybrew** [comment]
Hi @antonmarin,

The robots.txt "file" is virtual, and it's outputted by WordPress and overwritten by The SEO Framework.
If an actual robots.txt file is found in the root folder of your website, you're in full control of it 😄. You can add your own manually through FTP.

I hope this helps! Good luck!

**Comment by antonmarin** [comment]
So how to add Host: to robots.txt if file doesn't exist?

**Comment by sybrew** [comment]
You can create files through FTP.
Please advice on this with your hosting provider :)

**Comment by sybrew** [comment]
Hi Anton,

I hope you're doing well, and that you've been able to add your own robots.txt file. 
If you still have any questions regarding this subject, feel free to ask!

I'm also closing this topic; because this feature has been included in other forms already.

Cheers!
