### ISSUE TITLE
Feature: Social image upload for posts

### ISSUE THREAD

**Issue by sybrew** [sybrew/the-seo-framework#51]
A feature that has been requested so many times, I simply can't ignore it anymore with the philosophy: "Use what WordPress gives you".

Planned for 2.8.0 release.

**Comment by NateDotLife** [comment]
Similarly, the ability to set a default OG thumbnail for posts without featured images would be amazing!

**Comment by sybrew** [comment]
That would be a great idea as well indeed!

Then, that should be added in the General Settings of the "new" Social Settings metabox ... That metabox is going to be huge next patch as I'm also merging Knowledge Graph in it, so I'll need to figure out a way to improve this.

**Comment by digisavvy** [comment]
Hey there,
I know this doesn't directly answer the suggestion, but this code block could help in the meantime:
`/**
 * Default social images
 */
add_filter('the_seo_framework_og_image_args', function($args) {
    if ( has_post_thumbnail() ) {
        $thumb_id = get_post_thumbnail_id();
        $thumb_url_array = wp_get_attachment_image_src($thumb_id, 'large', true);
        $thumb_url = $thumb_url_array[0];
        $args['image'] = home_url( "$thumb_url" );
    } else {
        $args['image'] = home_url('/wp-content/uploads/2017/01/digital-marketing-la.png');
    }

    return $args;
});`
If there's a post thumbnail (aka featured image) it will be used as the default og:image. If one is not present then default to an image path that I define. Make sure to update the line after the 'else' clause to reflect the image you wish to use.

**Comment by sybrew** [comment]
Hi @digisavvy,

That's already happening: 
See [this](https://github.com/sybrew/the-seo-framework/blob/f63f8583147f88dbe9460fa2f0a0336d053ea2d1/inc/classes/generate-image.class.php#L89-L91), and [this](https://github.com/sybrew/the-seo-framework/blob/f63f8583147f88dbe9460fa2f0a0336d053ea2d1/inc/classes/generate-image.class.php#L198-L223). Which uses [this](https://github.com/sybrew/the-seo-framework/blob/f63f8583147f88dbe9460fa2f0a0336d053ea2d1/inc/classes/generate-image.class.php#L267-L350) to generate the URL and adjust images that are too big.

Most of which was already present in 2.0.5, which was released on June 25th, 2015; when it was still called "Autodescription" 😄.

**Comment by NateDotLife** [comment]
So the only bit that's missing is the ability to set a default :) cool cool, really looking forward to this update! 👍

**Comment by sybrew** [comment]
Enjoy: https://github.com/sybrew/the-seo-framework/commit/6ca4425abf3edafd75d7d47e60e54eb8bca91cc2

@NateDotLife the image fallback uploader is planned as well for 2.8.0, stay tuned 😄 

:small_airplane:
