### ISSUE TITLE
Consider only `rewrite` as valid for supported post types.

### ISSUE THREAD

**Issue by sybrew** [sybrew/the-seo-framework#513]
From [ooksanen's comment](https://github.com/sybrew/the-seo-framework/issues/20#issuecomment-597146481) (@ooksanen):

`the_seo_framework()->get_rewritable_post_types()` only requests post types that have both `public` and `rewrite` set to `true`. When a post is `public`, it implies `rewrite`, but not vice versa.

`the_seo_framework()->get_supported_post_types()` relies on the function mentioned above, which curates the state of TSF's post type support.

Methods `get_hierarchical_post_types()` and `get_nonhierarchical_post_types()` are also affected.

@ooksanen Do you want to test this **workaround**?
```php
add_filter( 'the_seo_framework_forced_supported_post_types', function( $post_types ) {
    return array_merge( 
        $post_types, 
        array_values( 
            \get_post_types( [ 
                'public'   => false, 
                'rewrite'  => true, 
                '_builtin' => false 
            ] )
        )
    );
} );
```

**Comment by ooksanen** [comment]
Should've guessed there's a filter for that. Works like a charm. Cheers @sybrew!

**Comment by sybrew** [comment]
We may want to consider disabling SEO for the non-public post types by default, where the user can activate them as desired, instead of vice-versa. Whether this is feasible (sporadic behavior) or even intuitive is up for debate.

**Comment by sybrew** [comment]
I tracked down my steps. 

We excluded them in the past because many devs don't know the difference between rewrite and public (looking at you too, Automattic). This caused a rich profusion of issues.

With WP sitemaps coming (and including non-rewriteable post types and taxonomies), it'll be a common issue, so we can now be complacent about that and revert our rewrite exemption rule.

Moreover, we now allow full control over post type and taxonomy support. So, we'll henceforth (commit incoming) support all rewritable post types and taxonomies by default.

**Comment by sybrew** [comment]
We should not support post types that don't have `public` in them. They aren't meant for public view, as it aptly suggests. We're not supporting the `[ 'public' => false, 'rewrite' => true ]` post types for this reason.

However, we are going to support `[ 'public' => true, 'rewrite' => false|true ]` henceforth.
