### ISSUE TITLE
New filter for sitemap extra post id's (Polylang post types excluded from translation not included in sitemap)

### ISSUE THREAD

**Issue by Ciantic** [sybrew/the-seo-framework#514]
I have Polylang installed, and I use it only for some post types. E.g. WooCommerce `product` post type is not included in the polylang translateable post types intentionally.

This means that sitemap totally ignores the post types which are excluded from the translation. It happens accidentally because the Polylang filters all of the posts in each WP_Query request with a language. 

This means that the SEO Framework's `the_seo_framework_sitemap_nhpt_query_args` and `the_seo_framework_sitemap_hpt_query_args` totally disregards the post types which are set to be non-translateable.

There is no way to fix this in SEO Framework, but helper filter could be added to here:

https://github.com/sybrew/the-seo-framework/blob/7b7e891d96c0b74fd4252c5e77eb6b3615156d97/inc/classes/builders/sitemap-base.class.php#L175

For example I suggest adding a filter `the_seo_framework_sitemap_extra_post_ids`:

```php
$_items = \apply_filters( "the_seo_framework_sitemap_extra_post_ids", array_merge( $hierarchical_post_ids, $non_hierarchical_post_ids ));
```

This way I could query more post id's easily there.

## Current workaround I use at the moment

```php
        /**
         * Polylang accidentally excludes the products from sitemap, we need to
         * add them back:
         */
        add_filter('the_seo_framework_sitemap_nhpt_query_args', function ($args) {
            $args["lang"] = ""; // This forces the non-translateable post types back in the mix
            return $args;
        }, 10, 1);
```

Which is not optimal (because it's not accurate), or generate urls completly myself with a new query.

**Comment by sybrew** [comment]
> This means that sitemap totally ignores the post types which are excluded from the translation. It happens accidentally because the Polylang filters all of the posts in each WP_Query request with a language.

We should amend the query filter, so to include these in the primary language's sitemap. I'm not sure if your workaround is fitting, or that we should look for alternatives.

Nevertheless, I agree with your suggestion to allow filtering the IDs. That doesn't take away that we should address the Polylang issue as well.

**Comment by Ciantic** [comment]
The workaround does not work in all cases because it will ignore the Polylangs language filter completly for non-hierarchical post types. It just happens to work for me, since `product` is only non-hierarchical post type I use (some people use `post` and that might be a problematic for them).

I guess you could implement third and fourth query just for polylang: Get all non-translateable post types in non-hierarchical and hierarchical post types.

**Comment by sybrew** [comment]
We should filter `pll_get_post_types`, but we can't since its caching mechanism blocks us before the template header is processed.

I'm awaiting their implementation for https://github.com/polylang/polylang/issues/451, which might shed some positive light on the subject.

The filter is underway, regardless.
