### ISSUE TITLE
Shortcode in title not working in structured data

### ISSUE THREAD

**Issue by squareloop1** [sybrew/the-seo-framework#517]
**Describe the bug**
I have a shortcode in a post title and added the filter as mentionend here: https://theseoframework.com/docs/api/filters/

It is working for the normal title but in structured data the shortcode does not get resolved and is still showing as a shortcode. Is there any special filter I need to use to make the shortcode work in structured data too?

**How to reproduce the bug**
1. Add a shortcode to a title with filters set
2. Check structured data for the title shortcode

**Expected behavior**
Should resolve the shortcode in structured data too

**Comment by sybrew** [comment]
Hello!

Are you experiencing this issue with the Articles extension? We may need to rethink where we get the title from.

Until then, I believe this filter will resolve the issue you're facing:
```php
add_filter( 'single_post_title', 'do_shortcode', 999 );
```

**Comment by squareloop1** [comment]
I couldn't check with the Articles extension yet, as I am currently still waiting for my pro plan to get activated.

The filter for `single_post_title` seems to work and the shortcode is successfully rendered in structured data now too. Thanks alot!
