### ISSUE TITLE
Add column for meta description in posts page

### ISSUE THREAD

**Issue by callaloo** [sybrew/the-seo-framework#522]
Hi there! Is it possible in the posts pages to introduce a column for meta description? It would help to know which posts have the meta autogenerated (e.g. SEO Press shows the entries blank) and those which are set manually by the user (hence they are populated).

**Comment by sybrew** [comment]
Hello!

We depict the "autogenerated" status via the letter G in the SEO Bar, for both titles and descriptions.

I hope that suffices for now 😄

**Comment by callaloo** [comment]
Ooh. Okay.
