### ISSUE TITLE
Sitemap 404 when using reverse proxy set up with sub-directory

### ISSUE THREAD

**Issue by andrewwu** [sybrew/the-seo-framework#529]
**Describe the bug**
I'm trying to move my WP site to a sub-directory but the accessing `/sitemap.xml` results in a 404 error.

Here's the set up:

* Blog: https://blogsite.com
* Main website: https://mainsite.com

I have a reverse proxy set up such that the blog is accessible at https://mainsite.com/blog

`WP_HOME` and `WP_SITEURL` are set to https://mainsite.com/blog

I've debugged this to this function here: https://github.com/sybrew/the-seo-framework/blob/master/inc/classes/bridges/sitemap.class.php#L384

```php
# $path_info returns the following:
(
    [path] => /blog/
    [use_query_var] => 
)
```

This is expected as `WP_HOME` is updated to use `/blog`. However, since this is a reverse proxy set up, the `$raw_uri` variable, set using `$_SERVER['REQUEST_URI']`, does not know about the `/blog` path.

https://github.com/sybrew/the-seo-framework/blob/master/inc/classes/bridges/sitemap.class.php#L111

**How to reproduce the bug**
1. Visit https://mainsite.com/blog (not an actual working link)
2. See 404 error 

**Expected behavior**
Sitemap is expected to render as usual.

**Additional context**
I'm able to fix this by modifying this function:

```php
private function get_sitemap_id_from_uri( $raw_uri ) {

// The path+query where sitemaps are served.
  $path_info = $this->get_sitemap_base_path_info();
  $path_info['path'] = '/'; // not so pretty fix
  ...
}
```

Is it possible to get a filter added for this or is there another solution you can recommend?

Thanks!

**Comment by sybrew** [comment]
Hello!

Have you configured the proxy using `WP_PROXY_HOST`? Not doing so would cause a plethora of issues, like having all canonical URLs pointing to other pages, RSS feeds broken, etc.

I believe that using that constant family, along with setting the `WP_HOME` and `WP_SITE` URLs to the expected public URL, would resolve the issue.

Alternatively, you can filter `home_url` to remove the `/blog/` part. However, I'm not sure which side-effects that might bring.

Another solution would be setting a proxy rule that forwards `blogsite.com/sitemap.xml` to `mainsite.com/blog/sitemap.xml` like in [this example rewrite ... break proxy_pass rule](https://stackoverflow.com/questions/36222000/how-to-change-request-uri-in-nginx-proxy-pass). But that's a high-maintenance can of worms you might not want to open.
