### ISSUE TITLE
Remove useless code

### ISSUE THREAD

**Issue by timbiernoth** [sybrew/the-seo-framework#531]
1. Remove the complete robots meta-tag if the values are default. This-> "max-snippet:-1,max-image-preview:standard,max-video-preview:-1" is default.
2. Remove self-closed stuff "/>" if HTML5

**Comment by sybrew** [comment]
Hi Tim,

Thank you for diving into this! I took notice you love optimization; so, keep these scrutinies coming!

1. When no such robots tag is supplied, in France, robots must assume it's completely blocked&mdash;it means no information from the content (or even the description metatag) may be taken. Moreover, `max-image-preview:standard` is the default for TSF, but not for search engines; for them, the default is `large`. For more information, see https://github.com/sybrew/the-seo-framework/issues/480.
2. We cannot assume HTML5 support is present without reading the output buffer of PHP. For example, in Twenty Twenty, [you can see its support is outputted unconditionally](https://themes.trac.wordpress.org/browser/twentytwenty/1.4/header.php#L12); it's plainly "printed". Moreover, this output can be overwritten via an output buffer provided in another plugin, which we'll only be able to read after they're done&mdash;and we cannot make assumptions on when. With those edge-cases in mind, it's best to use a default that's supported by all sites and browsers.

This also applied to the `<title>` tag; [where with HTML5](https://www.w3.org/TR/html52/syntax.html#escapable-raw-text), it may even contain the `<>` characters in their plain entity form (with the exception of `</` ([source](https://www.w3.org/TR/html52/syntax.html#ref-for-escapable-raw-text④))). We cannot assume all browsers support this, either.

If you have any more points for improvement, let me know! Until then, I'm marking this as "Won't fix".
