### ISSUE TITLE
Polylang sitemap not visible when cookie is set.

### ISSUE THREAD

**Issue by sybrew** [sybrew/the-seo-framework#532]
Thanks to [arfufu's report](https://wordpress.org/support/topic/sitemap-multilingual/), we found that Polylang sets a cookie based on the language the user is visiting. Unfortunately, this cookie also affects search engines.

For more information, see [our KB entry on Polylang](https://kb.theseoframework.com/kb/translation-plugin-compatibility/#polylang).

This cookie hampers the search engine's ability to view the sitemap of other languages. We'll need to see if we can output the sitemap regardless--but I don't have high hopes since (IIRC) the SITE_URL is affected.

**Comment by sybrew** [comment]
To work around this, you should disable the "Detect browser language" setting in Polylang. 
You can find this at <code>WP Admin &rarr; Languages &rarr; Settings &rarr; Module</code>. 

With that feature disabled, search engines and your users are free to browse your website. We can assure you that search engines will show links to your website in the potential visitor's preferred language.

**Comment by chesio** [comment]
A slightly better alternative might be to tell Polylang to not set any cookie:

```php
define('PLL_COOKIE', false);
```

See: https://polylang.pro/doc/php-constants/

This way browser language detection still works - at least with "The language is set from the directory name in pretty permalinks" option.

**Comment by sybrew** [comment]
I won't interfere with the functionality of other plugins or themes. That'll lead to issues down the line.

This issue was fixed permanently in 01ed86e45308cf24b246a86f63f96829de0527c8, and will ship with TSF v4.1.2.
