### ISSUE TITLE
Add an option to export plugin settings

### ISSUE THREAD

**Issue by askel45** [sybrew/the-seo-framework#552]
I am not sure if this has been requested before, but an option to export and import plugin settings would be very good when moving sites.

**Comment by sybrew** [comment]
If you're moving sites, then it'd be best to migrate the complete database.

For any other use case, this isn't easy. See (duplicate) #58.

**Comment by askel45** [comment]
@sybrew what I am referring to specifically is the settings a user has set in the plugin, not the SEO data.

**Comment by sybrew** [comment]
That's precisely what's proposed in #58. The issue is that we also store images and domain-specific details, which is why it's not easy.
