### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by askel45** [sybrew/the-seo-framework#553]
Any ideas in the making to revamp the design of the settings metaboxes? I think tabbed sections would look better TBH! An example https://prnt.sc/u6rvc6

**Comment by sybrew** [comment]
Hello 😄 

We're preparing for an overhaul of the settings page; you can track it via this project:
https://github.com/sybrew/the-seo-framework/projects/7

The main issue about the design is this one: https://github.com/sybrew/the-seo-framework/issues/505

Feel free to contribute your thoughts there!

(Sorry for closing issues on you, but duplicates are duplicates ☹️ )
