### ISSUE TITLE
Allow meta itemprop="dateModified" to be added to any page type

### ISSUE THREAD

**Issue by BWBama85** [sybrew/the-seo-framework#557]
Right now, meta itemprop="dateModified" content="2020-09-03 13:14:44 PDT"  is only being added to post types. As we update our pages areas frequently with new content or when data changes (think election data in real time or when we add new content about a candidate on their profile page) we want to be able to tell Google when the last time that page was updated.

**Comment by sybrew** [comment]
Hello!

Google can tell that pages are updated by:
- comparing the content of the page to a version they stored earlier;
- checking the `lastmod` timestamp outputted in the sitemap;
- checking dates outputted on the page, among the structured data from our [Articles extension](https://theseoframework.com/extensions/articles/).

TSF does not output Microdata meta tags (itemprop...content). You may want to consult with the theme author about this.
