### ISSUE TITLE
The Plugin is incompatible with Wordpress 4.7.0 and WPEngine

### ISSUE THREAD

**Issue by sumitii** [sybrew/the-seo-framework#56]
When I try and make deploys from staging to production in WPEngine I get the attached message:
<img width="822" alt="screen shot 2016-12-29 at 10 28 15 am" src="https://cloud.githubusercontent.com/assets/4623232/21547019/5ac1be54-cdb1-11e6-98c9-89b9ecbac3e5.png">

I deactivated and reactivated all my plugins one by one and also had a WPEngine technician look into this. We have determined that the issue is with the SEO Framework plugin. Please resolve! We love this plugin!

**Comment by sybrew** [comment]
Hi @sumitii! 

This issue has already been resolved https://github.com/sybrew/the-seo-framework/pull/47

A more elaborate explanation and temporarily solution has just been [posted on the WordPress.org forums(https://wordpress.org/support/topic/not-compatible-with-wordpress-4-7-0-or-wpengine/):
1. Disable TSF on staging;
2. Push from staging to live;
3. Enable TSF on live.

Alternatively, you can get a copy from the master branch, or wait for WordPress 4.7.1.

Cheers!

**Comment by sybrew** [comment]
Solved in TSF 2.7.3, which you can acquire from WordPress.org 😄
