### ISSUE TITLE
canonical query string stripped from paginated posts

### ISSUE THREAD

**Issue by hivecl** [sybrew/the-seo-framework#561]
**Describe the bug**
I'm using get_canonical_url filter to set the permalink without the pagination and with a query string. It works for non-paginated posts and the first page of a paginated post. However, on subsequent pages the query string is stripped.

**How to reproduce the bug**
Add this filter then visit page 2+ of a paginated post. There is no longer a query string.
```
function my_canonical( $url ) {
        if( is_singular( 'post' )  ) { 
            return get_permalink( $obj->ID ) . '?key=value';
        }
        return $url;
    }
add_filter('get_canonical_url', 'my_canonical');
```

**Expected behavior**
Query string is not removed when using get_canonical_url WordPress filter

**Possible solution**
From:
```
// generate-url.class.php line 764-770
if ( $continue ) {
	$url = substr( $url, 0, $pos );
	$url = \user_trailingslashit( $url );

	if ( $_query )
		$url = $this->append_php_query( $url, $_query );
}
```
To:
```
if ( $continue ) {
	$url = substr( $url, 0, $pos );
	$url = \user_trailingslashit( $url );
}
if ( $_query )
	$url = $this->append_php_query( $url, $_query );
```
Or simply:
```
// generate-url.class.php line 776
return apply_filters('get_canonical_url', $url);
```

**Comment by sybrew** [comment]
🤦 ... oops

I like your first solution best. Thanks for digging 😃 

In the meantime (as a workaround), we also have filters `the_seo_framework_rel_canonical_output` and `the_seo_framework_ogurl_output` available--simply return the same output from `my_canonical` to it, and it should work.

**Comment by sybrew** [comment]
N.B. When filtering `get_canonical_url`, you must provide the pagination yourself; otherwise, the canonical URL for paginated pages will lead to the first page. For details, see [wp_get_canonical_url()](https://developer.wordpress.org/reference/functions/wp_get_canonical_url/).
