### ISSUE TITLE
composer 2.0 - PSR 4 non compliance warning

### ISSUE THREAD

**Issue by danbas90** [sybrew/the-seo-framework#567]
When I run composer update im getting this warnings with composer 2.0:

<pre> Class The_SEO_Framework\Admin_Pages located in ./web/app/plugins/the-seo-framework/inc/classes/admin-pages.class.php does not comply with psr-4 autoloading standard. Skipping.
Class The_SEO_Framework\Site_Options located in ./web/app/plugins/the-seo-framework/inc/classes/site-options.class.php does not comply with psr-4 autoloading standard. Skipping.
Class The_SEO_Framework\Query located in ./web/app/plugins/the-seo-framework/inc/classes/query.class.php does not comply with psr-4 autoloading standard. Skipping.
Class The_SEO_Framework\Cache located in ./web/app/plugins/the-seo-framework/inc/classes/cache.class.php does not comply with psr-4 autoloading standard. Skipping.
Class The_SEO_Framework\Interpreters\SeoBar located in ./web/app/plugins/the-seo-framework/inc/classes/interpreters/seobar.class.php does not comply with psr-4 autoloading standard. Skipping.
Class The_SEO_Framework\Load located in ./web/app/plugins/the-seo-framework/inc/classes/load.class.php does not comply with psr-4 autoloading standard. Skipping.
Class The_SEO_Framework\Debug located in ./web/app/plugins/the-seo-framework/inc/classes/debug.class.php does not comply with psr-4 autoloading standard. Skipping.
Class The_SEO_Framework\Builders\Scripts located in ./web/app/plugins/the-seo-framework/inc/classes/builders/scripts.class.php does not comply with psr-4 autoloading standard. Skipping.
Class The_SEO_Framework\Builders\Sitemap located in ./web/app/plugins/the-seo-framework/inc/classes/builders/sitemap.class.php does not comply with psr-4 autoloading standard. Skipping.
Class The_SEO_Framework\Builders\Images located in ./web/app/plugins/the-seo-framework/inc/classes/builders/images.class.php does not comply with psr-4 autoloading standard. Skipping.
Class The_SEO_Framework\Builders\SeoBar located in ./web/app/plugins/the-seo-framework/inc/classes/builders/seobar.class.php does not comply with psr-4 autoloading standard. Skipping.
Class The_SEO_Framework\Builders\Sitemap_Base located in ./web/app/plugins/the-seo-framework/inc/classes/builders/sitemap-base.class.php does not comply with psr-4 autoloading standard. Skipping.
Class The_SEO_Framework\Builders\SeoBar_Page located in ./web/app/plugins/the-seo-framework/inc/classes/builders/seobar-page.class.php does not comply with psr-4 autoloading standard. Skipping.
Class The_SEO_Framework\Builders\SeoBar_Term located in ./web/app/plugins/the-seo-framework/inc/classes/builders/seobar-term.class.php does not comply with psr-4 autoloading standard. Skipping.
Class The_SEO_Framework\Generate_Image located in ./web/app/plugins/the-seo-framework/inc/classes/generate-image.class.php does not comply with psr-4 autoloading standard. Skipping.
Class The_SEO_Framework\Profile located in ./web/app/plugins/the-seo-framework/inc/classes/profile.class.php does not comply with psr-4 autoloading standard. Skipping.
Class The_SEO_Framework\Term_Data located in ./web/app/plugins/the-seo-framework/inc/classes/term-data.class.php does not comply with psr-4 autoloading standard. Skipping.
Class The_SEO_Framework\Bridges\Scripts located in ./web/app/plugins/the-seo-framework/inc/classes/bridges/scripts.class.php does not comply with psr-4 autoloading standard. Skipping.
Class The_SEO_Framework\Bridges\SeoSettings located in ./web/app/plugins/the-seo-framework/inc/classes/bridges/seosettings.class.php does not comply with psr-4 autoloading standard. Skipping.
Class The_SEO_Framework\Bridges\Ping located in ./web/app/plugins/the-seo-framework/inc/classes/bridges/ping.class.php does not comply with psr-4 autoloading standard. Skipping.
Class The_SEO_Framework\Bridges\Sitemap located in ./web/app/plugins/the-seo-framework/inc/classes/bridges/sitemap.class.php does not comply with psr-4 autoloading standard. Skipping.
Class The_SEO_Framework\Bridges\ListTable located in ./web/app/plugins/the-seo-framework/inc/classes/bridges/listtable.class.php does not comply with psr-4 autoloading standard. Skipping.
Class The_SEO_Framework\Bridges\TermSettings located in ./web/app/plugins/the-seo-framework/inc/classes/bridges/termsettings.class.php does not comply with psr-4 autoloading standard. Skipping.
Class The_SEO_Framework\Bridges\SeoBar located in ./web/app/plugins/the-seo-framework/inc/classes/bridges/seobar.class.php does not comply with psr-4 autoloading standard. Skipping.
Class The_SEO_Framework\Bridges\ListEdit located in ./web/app/plugins/the-seo-framework/inc/classes/bridges/listedit.class.php does not comply with psr-4 autoloading standard. Skipping.
Class The_SEO_Framework\Bridges\PostSettings located in ./web/app/plugins/the-seo-framework/inc/classes/bridges/postsettings.class.php does not comply with psr-4 autoloading standard. Skipping.
Class The_SEO_Framework\Bridges\Feed located in ./web/app/plugins/the-seo-framework/inc/classes/bridges/feed.class.php does not comply with psr-4 autoloading standard. Skipping.
Class The_SEO_Framework\Generate_Description located in ./web/app/plugins/the-seo-framework/inc/classes/generate-description.class.php does not comply with psr-4 autoloading standard. Skipping.
Class The_SEO_Framework\User_Data located in ./web/app/plugins/the-seo-framework/inc/classes/user-data.class.php does not comply with psr-4 autoloading standard. Skipping.
Class The_SEO_Framework\Detect located in ./web/app/plugins/the-seo-framework/inc/classes/detect.class.php does not comply with psr-4 autoloading standard. Skipping.
Class The_SEO_Framework\Render located in ./web/app/plugins/the-seo-framework/inc/classes/render.class.php does not comply with psr-4 autoloading standard. Skipping.
Class The_SEO_Framework\Admin_Init located in ./web/app/plugins/the-seo-framework/inc/classes/admin-init.class.php does not comply with psr-4 autoloading standard. Skipping.
Class The_SEO_Framework\Generate_Ldjson located in ./web/app/plugins/the-seo-framework/inc/classes/generate-ldjson.class.php does not comply with psr-4 autoloading standard. Skipping.
Class The_SEO_Framework\Sanitize located in ./web/app/plugins/the-seo-framework/inc/classes/sanitize.class.php does not comply with psr-4 autoloading standard. Skipping.
Class The_SEO_Framework\Init located in ./web/app/plugins/the-seo-framework/inc/classes/init.class.php does not comply with psr-4 autoloading standard. Skipping.
Class The_SEO_Framework\Deprecated located in ./web/app/plugins/the-seo-framework/inc/classes/deprecated.class.php does not comply with psr-4 autoloading standard. Skipping.
Class The_SEO_Framework\Post_Data located in ./web/app/plugins/the-seo-framework/inc/classes/post-data.class.php does not comply with psr-4 autoloading standard. Skipping.
Class The_SEO_Framework\Generate_Url located in ./web/app/plugins/the-seo-framework/inc/classes/generate-url.class.php does not comply with psr-4 autoloading standard. Skipping.
Class The_SEO_Framework\Generate_Title located in ./web/app/plugins/the-seo-framework/inc/classes/generate-title.class.php does not comply with psr-4 autoloading standard. Skipping.
Class The_SEO_Framework\Core located in ./web/app/plugins/the-seo-framework/inc/classes/core.class.php does not comply with psr-4 autoloading standard. Skipping.
Class The_SEO_Framework\Generate located in ./web/app/plugins/the-seo-framework/inc/classes/generate.class.php does not comply with psr-4 autoloading standard. Skipping.
Class The_SEO_Framework\Silencer located in ./web/app/plugins/the-seo-framework/inc/classes/silencer.class.php does not comply with psr-4 autoloading standard. Skipping.</pre>

**Comment by sybrew** [comment]
From my earlier comment https://github.com/sybrew/the-seo-framework/issues/533#issuecomment-654023728:
> I believe I should remove the PSR-4 autoloader from the schema. TSF has a custom one (via `spl_autoload()`) well integrated, which loads conditionally. All you need is to load its base plugin file (`autodescription.php`).

I didn't think it'd cause these issues, frankly. I'll get a move on this.
