### ISSUE TITLE
og:image tag should not default to featured image of most recent post

### ISSUE THREAD

**Issue by bvulaj** [sybrew/the-seo-framework#572]
**Describe the bug**
og:image tag of home page uses featured image from most recent post

**How to reproduce the bug**
1. Go to https://theperfectpack.com/
2. View source
4. See og:image tag is set to the featured image of the newest post, rather than the set image in my SEO settings

**Expected behavior**
I expect the first og:image tag to be the one I've explicitly set, or at least make an option that is more clear about this. The first image of the recent post doesn't make a lot of sense.

**Screenshots**
![image](https://user-images.githubusercontent.com/854769/100791478-4ef3e200-33e7-11eb-8ba5-c62047fe2ec8.png)

![image](https://user-images.githubusercontent.com/854769/100791755-ab570180-33e7-11eb-8bdb-fdbd099bda28.png)

**Comment by sybrew** [comment]
`is_blog_page()`/`is_blog_page_by_id()` should not be used when the homepage is a blog in `is_singular_archive()`, because the blog page won't be registered in the database as a page.

**Comment by sybrew** [comment]
Hi @bvulaj ,

The theme outputs separate Open Graph metadata, which supersedes TSF's output. 
In the HTML source, you can find the conflicting (and incorrect) data on line 5.

See if you can find a toggle in the theme to turn this off.

**Comment by bvulaj** [comment]
Hey, that was it! Thanks for the tip. Sorry about the bug report, but I appreciate the help.
