### ISSUE TITLE
Mobile first Indexing and separate Url for mobiles.

### ISSUE THREAD

**Issue by Solutiontales** [sybrew/the-seo-framework#574]
I feel the Seoframework should ready this feature to have mobile urls based on desktop ones, before the google update goes live.

source: https://www.seroundtable.com/google-mobile-first-indexing-for-separate-mobile-urls-30779.html

**Comment by sybrew** [comment]
WordPress relies on themes making responsive designs... and AMP for some superficial holacratic reason. I'm not aware of WordPress sending signals in Gutenberg when presenting mobile/tablet/desktop previews.

Mobile-first indexing is out of our hands. There is no change happening right now from Google. 

WordPress, The SEO Framework, and AMP for WordPress handle this correctly already via canonical URLs.

To learn more, please see https://developers.google.com/search/mobile-sites/mobile-first-indexing.
