### ISSUE TITLE
meta description tag is absent

### ISSUE THREAD

**Issue by Alexufo** [sybrew/the-seo-framework#578]
I install TSF and see only on main page meta tag.

Latest wp. No additional plugins installed.

![2021-03-10_18-52-11](https://user-images.githubusercontent.com/1562329/110657441-e2506680-81d1-11eb-8760-17a41b0a862f.png)

**Comment by sybrew** [comment]
Answered here: https://wordpress.org/support/topic/where-is-decsription-tag/
