### ISSUE TITLE
tsfem_i_[...] is a protected option after saving multisite settings

### ISSUE THREAD

**Issue by krzyko** [sybrew/the-seo-framework#580]
**Describe the bug**
Saving site settings in wordpress' multisite (subfolder mode) primary site leads to error message "tsfem_i_[...] is a protected option". Problem occurs only on primary site. Other sites in multisite does not have this problem.

**To Reproduce**
1. Install The Seo Framework and Extension Manager.
2. Activate both plugins in primary site /wp-admin/plugins.php in multisite environment
3. Get a free license for Extension Manager
4. Go to '/wp-admin/network/site-settings.php?id=1' (primary site on wordpress multisite)
5. Click on 'Save changes'
6. See error 'tsfem_i_[...] is a protected option'

**Expected behavior**
Options should be saved and site settings should be displayed again.

**Comment by sybrew** [comment]
Fixed in https://github.com/sybrew/The-SEO-Framework-Extension-Manager/commit/a1bde5ec07d53bdcfae23a7843a98a0a4de84319 (Extension Manager v2.5.1, TBA)
