### ISSUE TITLE
Add product specific data?

### ISSUE THREAD

**Issue by strarsis** [sybrew/the-seo-framework#584]
Does this plugin add product-specific data, as structured data (price, quantity and such), 
as the commercial [Yoast WooCommerce SEO plugin](https://yoast.com/wordpress/plugins/yoast-woocommerce-seo/) does?

There is some compat code for WooCommerce, but does it make use of all the shop-/product-specific data?

**Comment by sybrew** [comment]
WooCommerce supplies that structured data, so we don't have to. TSF is in that regard more compatible with WooCommerce than other SEO plugins. Other than providing a preview (which is only a guess), I believe Yoast's WooCommerce SEO is a rip-off in that regard.

For more information, see [this KB entry about structured data and TSF](https://kb.theseoframework.com/kb/structured-data-supported-by-the-seo-framework/#not-just-us)
