### ISSUE TITLE
Query for untranslated posts excludes almost all posts from sitemap.

### ISSUE THREAD

**Issue by ot-st** [sybrew/the-seo-framework#586]
https://github.com/sybrew/the-seo-framework/blob/32cd81102da57ad3bdd15d641bc3afe2408d46d5/inc/compat/plugin-polylang.php#L130

**Describe the bug**
At line 125 `pll_languages_list( [ 'fields' => 'term_id' ] )` returns an array of **term_ids** while the id for default language at 130 is taken from `$default_language->term_taxonomy_id`. 
This causes the tax query to look for posts that do not match the term_ids of a language while looking for posts with the default term_taxonomy_id making the first condition exclude the 2nd.

**Probable fix that worked on my setup**
Swap the current line 130 to `'terms'    => $default_lang->term_id,`.

**Comment by sybrew** [comment]
Similar reports:
1. https://wordpress.org/support/topic/sitemap-xml-polylang-issue-with-default-language-sitemap/
2. https://wordpress.org/support/topic/sitemap-issue-with-polylang-default-language/

User of 2. (lemoon) found the provided fix working.
