### ISSUE TITLE
Add priceRange to Local (Structured Data)

### ISSUE THREAD

**Issue by raouffuelist** [sybrew/the-seo-framework#590]
I'd like to request the [priceRange property](https://schema.org/priceRange) be added to the Local extension.

e.g. "$$$" "$10-$15"

priceRange is a recommended property to include in the structured data for a local business.

For some of our clients, the pricing is a competitive advantage. We have had to disable the Local extension and manually insert json-ld scripts just to include the priceRange property.

We'd love if we could just control everything from The SEO Framework since it's just a text field.

Google uses it in many examples of its structured data for local businesses: https://developers.google.com/search/docs/advanced/structured-data/local-business (CTRL+F "price")

Thank you in advance.

**Comment by sybrew** [comment]
Thank you for bringing up this issue -- many were before you.

And before, we couldn't implement a numerical range, so I left it out due to hyper-ambiguity. 
But, now, from Google's docs:

> The relative price range of a business, commonly specified by either a numerical range (for example, "$10-15") or a normalized number of currency signs (for example, "$$$").
> 
> This field must be shorter than 100 characters. If it's longer than 100 characters, Google won't show a price range for the business.

Since numerical ranges are now possible, I see no reason _not_ to implement the feature.

**Comment by sybrew** [comment]
This is how it will look:

![image](https://user-images.githubusercontent.com/7662236/217067936-266a5ad4-59fd-4b76-be3d-8b82b1ebf23b.png)

It is validated by a regular expression I published here: https://regex101.com/r/N3f5lF/6.

Google allows "only" 100 characters; however, with the restrictions from the regex imposed, I see no reason anyone would hit that, so I didn't bother testing how Google would respond.
