### ISSUE TITLE
Canonical to a different domain

### ISSUE THREAD

**Issue by zlobec** [sybrew/the-seo-framework#592]
Hi,

I have 3 webshops all with the same content synced from a single source. With regard to SEO recomendations, it would be logical to add the source domain as a canonical url. 

Is there a way to add this automatically, for example I enter the domain "https://myoriginaldomain.com" and it would translate to each product url the canonical address from "https://mySECONDshop.com/product/example-product" to "https://myoriginaldomain.com/product/example-product" ?

To do it by hand is a real hassle... I have more than 1500 products in my shops.

EDIT: forgot to add :) Currently I'm doing this with functions.php
```
add_filter( 'the_seo_framework_rel_canonical_output', function($url){
    return str_replace('https://mySECONDshop.com', 'https://myoriginaldomain.com', $url);
} );
```

Regard,
Darjan

**Comment by sybrew** [comment]
Hi Darjan,

If you just want to affect only TSF's URLs, then you must filter `home_url` between actions `the_seo_framework_do_before_output` and `the_seo_framework_do_after_output`. e.g.

```php
add_action( 'the_seo_framework_do_before_output', function() {
	add_filter( 'home_url', 'my_home_url_filter' );
}, PHP_INT_MIN );

add_action( 'the_seo_framework_do_after_output', function() {
	remove_filter( 'home_url', 'my_home_url_filter' );
}, PHP_INT_MAX );
```

I'm not sure why you'd want to use canonical URLs instead of using a redirect via .htaccess. But I'm probably missing half of the story here.

I hope this helps! Cheers :)

**Comment by zlobec** [comment]
Hello Sybre,

I've only recently started using the plugin, since all my clients were demanding Yoast (??!) and I'm a bit unversed in the hooks the plugin has, and need more a confirmation that I was doing it correctly.

Thanks for your response and additional info.

Regard,
Darjan
