### ISSUE TITLE
PHP Warning when using the filter the_seo_framework_sitemap_post_limit 

### ISSUE THREAD

**Issue by ictbeheer** [sybrew/the-seo-framework#594]
**Describe the bug**

When the filter `the_seo_framework_sitemap_post_limit` is used, you get the following PHP warning when going to the TSF settings screen.

```
PHP Warning:  '<span><strong>Warning:</strong> <code>tsf()-&gt;get_sitemap_post_limit()</code> is niet toegankelijk in <code>tsf()</code>.  In \wp-content\plugins\autodescription\inc\views\settings\metaboxes\sitemaps.php on line 163</span><br>
 in \wp-content\plugins\autodescription\inc\classes\internal\debug.class.php on line 258
```

**How to reproduce the bug**
1. Attach a function to the filter the_seo_framework_sitemap_post_limit 
2. Go to the TSF settings screen.

**Expected behavior**
No PHP warning :)

**Additional context**
WP 5.8.2 / TSF 4.2.0 / PHP 8.0.0

**Comment by sybrew** [comment]
Could you please share the filter code you're using? Thanks!

**Comment by ictbeheer** [comment]
This is the filter code I am using:
`add_filter( 'the_seo_framework_sitemap_post_limit', fn(): int => 5000);`

**Comment by sybrew** [comment]
Hi again!

That filter cannot invoke the error. Could you please check if there are other active filters/plugins which may cause the issue?

**Comment by ictbeheer** [comment]
Hi, I have managed to reproduce this on a clean WP install with only TSF installed and the filter code added to the functions.php of the default theme.

Could it be in the following part, as that is only executed if this `the_seo_framework_sitemap_post_limit` has a filter?

https://github.com/sybrew/the-seo-framework/blob/49edbbc3920fb87721b8c3d71479b0e5862307c0/inc/views/settings/metaboxes/sitemaps.php#L159-L166

**Comment by sybrew** [comment]
🤦‍♂️

**Comment by sybrew** [comment]
I've chosen to remove that conditional and display the standard input field, especially because the filter can be applied conditionally.

This is in line with all other fields that might get filtered.
