### ISSUE TITLE
Notification of incompatibility with XML Site Map and Google News

### ISSUE THREAD

**Issue by bolda500** [sybrew/the-seo-framework#598]
**Describe the bug**
After updating Wordpress, this notification screen appeared a few days ago.

Is it a bug or is the plugin incompatible, because Google has changed something.

**Screenshots**
![image](https://user-images.githubusercontent.com/6399560/143147489-315a1c4f-7c7f-4baa-a3c4-7f325610f14b.png)

**Comment by sybrew** [comment]
Hello!

That notification isn't outputted by The SEO Framework and is unrelated to changes in Google. The notification is not a bug; it's a result of a detection invoked by the XML Sitemaps & Google News plugin.

The notification's wording could be improved, however. It's not "not compatible. [period]"; it's "not compatible when... [explanation]". 

Please mind that only TSF's sitemap considers the plugin's indexing, exclusion, and redirecting options. This mitigates warnings you might come across in the webmaster tools (Search Console/Bing Webmasters). If you require a Google News sitemap, we do offer that via our [Articles extension](https://tsf.fyi/e/articles), but that's a premium-only feature.

Ultimately, it's up to you which sitemap you choose.
