### ISSUE TITLE
Add Yandex verification meta tag

### ISSUE THREAD

**Issue by alanorth** [sybrew/the-seo-framework#6]
Yandex is a major search engine in Russia. From their [Webmaster API docs](https://tech.yandex.com/webmaster/doc/dg/reference/hosts-type-docpage/):

```
<meta name='yandex-verification' content='4ea8e18ffda14271' />
```

**Comment by sybrew** [comment]
Good catch Alan! I'll see if I can slip it into the 2.6.0 release!

**Comment by sybrew** [comment]
It's in [beta](https://github.com/sybrew/the-seo-framework/commit/47607bcf3262e3346efb345fbac8aaad9df93d4e). Enjoy!
