### ISSUE TITLE
Dynamic meta content for post type archive

### ISSUE THREAD

**Issue by vralle** [sybrew/the-seo-framework#601]
**Describe the bug**
Unable to use dynamic metadata content.

**How to reproduce the bug**
As an example, I will give a filter of archive description:
```php
function archive_description( string $description, $object ): string {
	if ( $object instanceof \WP_Post_Type ) {
		$current_page = get_query_var( 'paged' ) ? (int) get_query_var( 'paged' ) : 1;
		$post_type      = $object->name;
		if ( 1 === $current_page ) {
			$meta_value = get_option( "archive_{$post_type}_description", '' );
			if ( $meta_value ) {
				return 'Find the latest cars for sale by owner or from a trusted dealer in London. Compare prices, features & photos. Contact sellers today.';
			}
		} elseif ( 2 <= $current_page ) {
			$total_posts   = $GLOBALS['wp_query']->found_posts;
			$per_page      = get_query_var( 'posts_per_page', 0 );
			$current_start = ( $current_page - 1 ) * $per_page + 1;
			$current_end   = $current_page * $per_page;
			$meta_value    = get_option( "archive_{$post_type}_description_paged", '' );
			if ( $meta_value ) {
				return "{$current_start}-{$current_end} (out of {$total_posts}) {cars for sale by owner or from a trusted dealer in London. Compare prices, features & photos. Contact sellers today.}";
			}
		}
	}

	return $description;
}
add_filter( 'the_seo_framework_pta_description_excerpt', 'archive_description', 11, 2 );
```
After the first generation of the description, the filter no longer fired. Description content cannot be changed.
Even if you remove the filter, the plugin continues to use outdated content.
Applying "Save Settings" on the plugin's settings page also has no effect.

**Expected behavior**
Metadata content can be changed dynamically.

**Additional context**
Since version 4.2, the content of the metadata has become static. I suppose you can control the content of the metadata using the memo function, but so far I have not come across a description of such a mechanism.

**Updated**
Since v4.2 meta content for post type archives controlled with new filters:
[the_seo_framework_post_type_archive_meta](https://github.com/sybrew/the-seo-framework/blob/858f70ce23f2193db1b6cbde9ed8fd41d5e6edd2/inc/classes/site-options.class.php#L821-L835)
[the_seo_framework_get_post_type_archive_meta_defaults](https://github.com/sybrew/the-seo-framework/blob/858f70ce23f2193db1b6cbde9ed8fd41d5e6edd2/inc/classes/site-options.class.php#L885-L896)

This works as expected. 
It's a shame that dynamic meta description didn't work properly on sites for a long time.

**Comment by sybrew** [comment]
Hi Vitaliy,

TSF's meta generation "in the loop" only expects one query to take place. I don't know which method you called to obtain metadata in an actual loop, but I probably optimized that one down the line -- keeping in mind that metadata is generated for only one query of an "in the loop" post/archive.

If you wish to grab data from TSF's methods outside of the main one for the query, you must populate `$args` wherever possible and read that value in the following filters.
