### ISSUE TITLE
Author/Editor SEO

### ISSUE THREAD

**Issue by sybrew** [sybrew/the-seo-framework#61]
Although Author SEO is incorporated in the plugin, it's quite basic and targeted to the main website's pages.
This works great for both small and large businesses, but not so much for News websites where multiple authors reside to share opinions and ideas.

Think Forbes: Where many different authors write very different articles. Either for self-promotion, to merely share an opinion, or even for their business.

Author SEO will allow authors to edit their WordPress user profiles in order to add mostly Social Sites optimizations; which allows &mdash; on sharing the links of those articles &mdash; to display their page in the results/excerpt.

Maybe even add back-to-profile links beneath the articles. This will also affect the Knowledge Graph through Rich Data if done correctly.

A lot more work has to be done on the specifics, but let's just start by opening an issue on it for now.

**Comment by pakpenyo** [comment]
+1 for this. Really need the Knowledge Graph to identity writer/author.

**Comment by sybrew** [comment]
Related: #21

**Comment by ladislavsulc** [comment]
+1

**Comment by sybrew** [comment]
This new feature will affect social sharing, only.

For Knowledge Graph-targeted data, see https://theseoframework.com/extensions/articles/
