### ISSUE TITLE
Identical settings in multiple tabs

### ISSUE THREAD

**Issue by paaljoachim** [sybrew/the-seo-framework#611]
**Describe the bug**

For the settings tabs:
Layout, Performance, Canonical, Timestamps and Exclusions I am seeing the same sections being repeated over and over again.
This issue is linked in with: 
https://wordpress.org/support/topic/identical-settings-in-multiple-tabs/#post-16002420

**How to reproduce the bug**
No idea....

**Expected behavior**
Not having repeated the same sections for each tab.

**Screenshots**

Unlisted Youtube video: https://youtu.be/mbmbMIdIOH4

**Additional context**
Local site made with Desktop Server. Running PHP version 7.3.
WordPress 6.0.2
A few different plugins.
I see no console error.
Brave browser

**Comment by paaljoachim** [comment]
I switched themes and deactivated various plugins but the result was the same.

I also tested this on a live dev site and noticed the same error.
Send me an email at paaljoachim@easywebdesigntutorials.com and I will send you login info to the dev site so you can see for yourself.

**Comment by sybrew** [comment]
Hi Paal,

Thank you for the video, it helped me understand the issue.

There's no bug here 😅, each of the meta boxes has its very own tab management system. The content displayed underneath each tab stops at the end of the meta box. So "General > Layout" has 5 checkboxes, "General > Canonical" has 1 dropdown and 3 checkboxes, and then when we move down a meta box, "Title > General" has 2 options.

You can also drag the meta boxes up and down just like you would on the Classic Editor (pre-Gutenberg). In the image below, I'm dragging the closed General meta box:
![image](https://user-images.githubusercontent.com/7662236/189769837-8c347c66-54d2-4ba7-a301-cedd70d3a071.png)

At the top right, you have "Screen Options," via which you can disable meta boxes.

![image](https://user-images.githubusercontent.com/7662236/189770177-bd76eda0-da88-4b3a-b68f-d63be217f7f9.png)

You're not the first to be confused or overwhelmed by our current interface, and I'm planning to overhaul it in a future major update. See https://github.com/sybrew/the-seo-framework/issues/505.

**Comment by paaljoachim** [comment]
Thanks @sybrew 
I will follow along.

Btw
Do you have a few folks that beta test? If so I would like to join the list.

Closing this issue....

**Comment by sybrew** [comment]
Hi Paal,

I appreciate your interest! When we have a public beta run, I will announce it -- probably via our Twitter account: https://twitter.com/TheSEOFramework. 
In the past, it led to no responses or bug reports, but 5.0 will be a significant change incurring feedback necessary.

**Comment by paaljoachim** [comment]
I just sent you a Slack message, as I am not much of a Twitter fan.
As it would be nice to when the time comes to help test the beta.
