### ISSUE TITLE
Regenerate Meta Description (if autogenerated description is in use) on Update

### ISSUE THREAD

**Issue by blizam** [sybrew/the-seo-framework#639]
It looks like meta descriptions are only automatically generated once... when the plugin is installed or when a post/page is created. If additional text is added to the body of a post/page that might improve the meta description it is not considered on subsequent saves. I get this if the field was manually overwritten with a human-typed meta description but if the automatically generated description is in use I think it should regenerate on every page update so that as additions to to the post/page are made they're incorporated into the meta description as appropriate.

Is there any way to force meta tags to regenerate besides uninstalling/reinstalling the plugin? Something here perhaps?: https://github.com/sybrew/the-seo-framework/issues/445

**Comment by sybrew** [comment]
Hello!

TSF generates new descriptions on every request and doesn't store its output anywhere.

If it appears to only happen once without updating, then a caching plugin keeps a stale copy of the page's output, perhaps even segmented (via transients or object cache).

**Comment by blizam** [comment]
hmmmm I'll have to do some more testing as we are running different types of content/object caching...

Specific to Product (WooCommerce) Posts where is TSF scanning content that it then generates a meta description for? The Short Description (Excerpt)? Main Description? Is it only scanning post content stored in the database or is it by chance scanning front end content which would allow it see other content set by themes or other plugins?

**Comment by sybrew** [comment]
Hi again!

TSF first tries the excerpt field and then the post content to generate a description. 
It takes the content as-is from the database, so shortcodes and some page builder content often won't be used for generation. 

Depending on the filters implemented on the site, the content may be pre-processed. But this is unlikely, so dynamic content from page builders often won't be interpretable by TSF.

The [description generator is quite complex](https://tsf.fyi/kb/a/65), but the gist is that it strips out HTML it thinks needless and then tries to fit that within 160 characters for English sites by trimming words.

**Comment by blizam** [comment]
Thank you for the detail.

I see at that link, The Getter:

```Step one, the getter

    first takes your content (or excerpt, when available);```

So if there's an excerpt/short description (Woo) then *only* the excerpt is considered for description generation? Additional content in the main description is ignored/not-used?

**Comment by sybrew** [comment]
Correct!
