### ISSUE TITLE
Schema section does not allow input of logo URL

### ISSUE THREAD

**Issue by Knocks** [sybrew/the-seo-framework#646]
The current version of the plugin (4.2.8) does not allow manual user input in the URL field for schema logo images (Presence tab).  The field is grayed out.  The only way to specify an image is to upload one via media gallery and then browse to your upload.

I am filing this under bugs because manual input is allowed for images in other sections (open graph etc), so the assumption is that the behavior should be the same for schema.

**Comment by sybrew** [comment]
This is intentional behavior. 

We need to have the image ID from the WordPress database to parse the image dimensions, which are required for this type of Schema.org output.

Calculating the dimensions for the image "just in time" would require us to access the image, while the data is only consumed by one single visitor: Googlebot.

**Comment by Knocks** [comment]
Thanks for clarifying the behavior.  The need for the image ID to parse dimensions is clearly valid.

My concern is that key assets, such as logos and branding images don't really belong in wp-content/uploads/2023/07 etc, especially when other similar images like open graph, pwa, favicons etc are neatly organized somewhere else.  Since we are only specifying this image once, is the performance overhead of fetching the dimensions via the server's default image processor really high?

**Comment by sybrew** [comment]
If the image URL is stored remotely, getting the image size would be as slow as loading an entire image via the browser before we can send the page. If the remote server is offline or overwhelmed, and we set a timeout of 3 seconds, your site will load 3 seconds slower. This is done for every page where the logo's dimensions are requested. Workarounds don't exist for this "time to first byte" problem.

If the image URL is stored locally, we'd still have to request the URL to get the size; this will double the request to your site whenever we want to fetch the image's dimensions.

I think WordPress's naming conventions of attachments are fine; it is not something your visitors would capture, nor would anyone capable of reading your website's source be concerned. WordPress automatically organizes attachments, and this is something I wish to avoid fiddling with.

**Comment by sybrew** [comment]
It appears the logo requirements have changed -- a plain URL without dimensions is also allowed.
I'll fix this in the next major update.

**Comment by sybrew** [comment]
I resolved it a few months ago in this commit: https://github.com/sybrew/the-seo-framework/commit/e44d72af7fc6a71c79de59600ed259a015c5e022#diff-aea1fe23089859c62316899cc6d9d61e56219abf7704fb887a76b26113068bc6L180.

The attached commit below will also remove the JavaScript requirement warning.
