### ISSUE TITLE
Add "Google-Extended" option to Robots options to block AI

### ISSUE THREAD

**Issue by social-ink** [sybrew/the-seo-framework#647]
Google just introduced Google-Extended https://blog.google/technology/ai/an-update-on-web-publisher-controls/ to opt out of all AI training.

Would love the ability to add this to Robots (and checked by default when adding plugin to site).

**Comment by sybrew** [comment]
Thank you for providing those details.

This can be part of #59; I added your suggestion to it. Let's continue there. Cheers!

**Comment by sybrew** [comment]
I am going to treat this as a separate issue.

**Comment by sybrew** [comment]
Implemented via 242d69fb34c6c9a71b53fe30b6606758a7f11a9a.
