### ISSUE TITLE
5.0 Beta Test. 

### ISSUE THREAD

**Issue by advwebin** [sybrew/the-seo-framework#653]
Installed the plugin from the link you shared on Twitter, Using wp.one .. Activation caused Critical Error on Wordpress.

Installed it on a staging site on my server hosted with Runcloud, PHP 8.1, WP 6.4.1
Same issue.

Going Back, the dashboard was working and I was able to get into the settings page.

Listing the NGINX Error Log:

#6 /home/var/webapps/example/wp-content/plugins/the-seo-framework-ma" while reading response header from upstream, client: 172.68.167.137, server: example.com, request: "GET /wp-admin/plugins.php?activate=true&plugin_status=all&paged=1&s= HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/example.sock:", host: "example.com", referrer: "https://example.com/wp-admin/update.php?action=upload-plugin"
#5 /home/var/webapps/example/wp-content/plugins/the-seo-framework-master/inc/classes/data/admin/plugin.class.php(65): add_option()
#4 /home/var/webapps/example/wp-includes/option.php(972): sanitize_option()
#3 /home/var/webapps/example/wp-includes/formatting.php(5126): apply_filters()
#2 /home/var/webapps/example/wp-includes/plugin.php(205): WP_Hook->apply_filters()
#1 /home/var/webapps/example/wp-includes/class-wp-hook.php(324): The_SEO_Framework\Data\Filter\Plugin::filter_settings_update()
#0 /home/var/webapps/example/wp-content/plugins/the-seo-framework-master/inc/classes/data/filter/plugin.class.php(76): array_merge()
Stack trace:
2023/11/11 15:22:32 [error] 514882#514882: *49363 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: array_merge(): Argument #2 must be of type array, bool given in /home/var/webapps/example/wp-content/plugins/the-seo-framework-master/inc/classes/data/filter/plugin.class.php:76

**How to reproduce the bug**
1. Go to wp.one
2. Upload the 5.0 Plugins
3. Activate

**Screenshots**

<img width="1059" alt="Screenshot 2023-11-11 at 20 57 50" src="https://github.com/sybrew/the-seo-framework/assets/90175055/47d21c09-10b0-45da-b43e-1ec403821e72">

**Comment by sybrew** [comment]
Thank you for testing! 

I hadn't touched a fresh site in a few weeks (it was on the [triage TODO list](https://github.com/sybrew/the-seo-framework/blob/master/readme.txt#L342)), so this issue slipped in.
I just fixed it in the last commit.
