### ISSUE TITLE
Toggle Sitemap stylesheet header link

### ISSUE THREAD

**Issue by alanjacobmathew** [sybrew/the-seo-framework#658]
When sitemap styling is enabled the admin has the ability to add or remove the logo. Similarly give the admin the ability to enable or disable the backlink to the homepage. Or allow the admin to choose what link to display.

Why?
When a static version of the site is created, the link from the logo & title still redirects to the dev site, and not to the static site. 

I tested with Staatic plugin and Simply Static plugin plugin to create, all other permalinks can be controlled with the absolute URL or relative URL setting in those plugins. But this link cannot be directly controlled.

**Comment by sybrew** [comment]
Hi Alan,

We use `get_home_url()` to output that URL, which is filterable via `home_url`. If that URL is incorrect, something may need to be addressed with the setup.

Disabling that URL won't make the cause of the problem disappear, and it may be echoed somewhere obscure.

We load the sitemap at `parse_request` priority `15`.
