### ISSUE TITLE
Sitemap priority setting

### ISSUE THREAD

**Issue by bazeboiee** [sybrew/the-seo-framework#661]
I'd like to be able to rank my pages in order of priority so that Google understands the relative importance of each page.

**Comment by sybrew** [comment]
Hello!

If you wish to use the `<priority>` tag, then it'd be futile. Google never used them: https://developers.google.com/search/blog/2023/06/sitemaps-lastmod-ping#changefreq-and-priority.

If you mean something else, please elaborate.
