### ISSUE TITLE
Schema.org and microdata

### ISSUE THREAD

**Issue by LeBaux** [sybrew/the-seo-framework#67]
I was using different schema generators over the years and I am curious what is your stance on this topic and if you plant to implement in TSF, presumably via plugin.

I was using [Schema Creator by Raven (github mirror)](https://github.com/SchemaCreator/schema-creator) ) for a year on 2 sites and it actually hurt my rankings quite a bit. It was pulled from[ wordpress plugin directory with only discussions left](https://wordpress.org/support/plugin/schema-creator/). Raven is doing his thing separately now as SAAS, but [other schema plugins emerged](https://wordpress.org/plugins/search.php?q=schema.org) and I am wondering how useful or impactful they are.

For example, some _SEO experts_ are abusing the [schema review](https://schema.org/Review), mainly to add stars to SERP - and it is hard to blame them since 5-star visual cue in SERP is boosting CTR. Anyway, what is your stance on schema.org microdata, are you planing to use mentioned star feature or/and do you have any insight or opinion on this topic? Thanks.

PS: I hope I am not bothering you too much with these topics, if it puts too much strain on your work/mood just lock it ;)

**Comment by sybrew** [comment]
Hi @LeBaux, 

All Rich Data created by The SEO Framework are implemented through Schema.org JSON-LD standard. This is a favored way of implementation, as it's theme independent, and doesn't require user interaction. It's also **only injected when required** and when the user has enabled such option.

When you ***abuse*** these kinds of data, you'll be eventually punished for cloaking or improper implementation (abuse) according to [Webmaster Guidelines](https://support.google.com/webmasters/answer/35769?hl=en).

Therefore, TSF will only implement these types of information scarcely and will always rely foremost on WordPress Core supplied data. **The user has no say in how this is used or implemented** when using TSF. I believe that **Rich Data is much too powerful for anyone to manually adjust**; which can lead to drastically incorrect results or even penalty. And that's the last thing I want users and their site's visitors to experience when using TSF.

Although there are filters in place, I strongly advice not to use them.

And this might be why you've seen your rankings drop with the other (currently removed from the repository) plugin. It could've easily been incorrectly implemented.

### My stance on Schema.org data:
I'll be implementing it more and more. It's currently even at the highest priority for development for The SEO Framework. With TSF 2.8.0 I've reworked the admin settings layout for this.

#### But, no review (stars) data.
The review feature is currently handled by WooCommerce when it makes visual use of this data. 
I have no plans on implementing review data as it's perfectly handled by WooCommerce. 
I strongly advice you to stay away from abusing this and use it only when properly implemented, like with WooCommerce.

I currently can't think of any other plugins or implementations in WordPress that can or should use this. Yelp and Google Places are much better sources for local business reviews, and they should be left there. They also present more authority.

I can't comment on how you should implement this yourself and when it's proper. However, [Google has documentation on this](https://developers.google.com/search/docs/data-types/reviews).

**Comment by LeBaux** [comment]
Thanks again for clarification, I have to say I like your stance on this. You are taking really methodical, recommended and safe (white hat) approach.

**Comment by sybrew** [comment]
This "documentation" issue is maintained in our Knowledge Base: https://tsf.fyi/kb/structureddata.
