### ISSUE TITLE
PHP Warning

### ISSUE THREAD

**Issue by xaja** [sybrew/the-seo-framework#676]
PHP Warning:  Array to string conversion in /wp-content/plugins/autodescription/inc/classes/internal/deprecated.class.php on line 1699

**Comment by sybrew** [comment]
Thank you for reporting this issue! This has recently been fixed at https://github.com/sybrew/the-seo-framework/commit/784471bab7211b94bee9974f68472faa437ca00d and is scheduled for TSF v5.0.7.

AMP for WordPress still calling our previous API, indirectly invoking this warning. We intend to resolve the deprecation calls -- see https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/5603.
