### ISSUE TITLE
After installing TSF, our company name on Google has apostrophe-s after it.  Why?

### ISSUE THREAD

**Issue by mwoffenden** [sybrew/the-seo-framework#679]
**Describe the bug**
Our company name on Google suddenly has as apostrophe-s after it.  We've triple checked the business settings in Google and those settings are correct.

**Screenshots**
<img width="697" alt="google" src="https://github.com/sybrew/the-seo-framework/assets/6774346/e44d4190-5153-4cdc-af48-d36099d16cdf">

**Additional context**
Started happening after installing and setting up TSF, we also installed the Cord extension.

**Comment by mwoffenden** [comment]
Never mind!  The cause was a rogue ALT title on our site that included the apostrophe-s.  Nothing to do with TSF.

**Comment by sybrew** [comment]
Google rewrites titles and descriptions often based on the search query in relationship to the content of your pages. 

Google's erratic behavior confuses many of our users, but ultimately, it serves to improve the search engine results page.
