### ISSUE TITLE
Post Type Exclusions - please add tds-*

### ISSUE THREAD

**Issue by marcusdoc** [sybrew/the-seo-framework#681]
General > Exclusions > Post Type Exclusions
already has some exclusions for the “tagDiv Opt-In Builder”

Reviews - tdc-review
Cloud Templates - tdb_templates

There are additional items that I ask to be included that are from the “tagDiv Opt-In Builder”
/tds-checkout
/tds-my-account
/tds-login-register

Please add the exclusion for **tds-***

Thank you!

**Comment by sybrew** [comment]
This is a follow-up from a [WordPress.org support thread](https://wordpress.org/support/topic/tds-entries-in-the-sitemap-xml/#post-17867615).

Thank you for opening this feature suggestion! 

However, TSF already automatically supports all post types. This entire class is dedicated to that effort: https://github.com/sybrew/the-seo-framework/blob/5.0.6/inc/classes/helper/post-type.class.php.

It assumes post types are registered according to the API. The `tdf_*` post types were registered correctly; hence, you do not see them listed in the settings. They cannot be seen by search engines, so "SEO" wouldn't be possible.
