### ISSUE TITLE
Schema.org breadcrumbs has dot instead of clean URL

### ISSUE THREAD

**Issue by Dade88** [sybrew/the-seo-framework#685]
**Describe the bug**
I use TSF on my site but have deactivated Schema because of an own implementation. I wanted to test some possibilities with TSF and I saw the breadcrumbs URLs in the generated schema with dots.

Dots in Base Category and Base Tag (Permalink options) is used to remove /category/ or /tag/ from the urls.

**How to reproduce the bug**
1. Set Base Category and/or Base Tag as ".", without quotes.
2. Turn on Schema on TSF options.

**Expected behavior**
Schema breadcrumbs should have the actual URLs without dots when it comes to categories.

**Comment by sybrew** [comment]
Hello!

Dots shouldn't be used in the permalink settings. It is a bug, not a feature, that makes it behave like this.

If you wish to remove the base, consider using a plugin like [No Category Base](https://wordpress.org/plugins/no-category-base-wpml/), which achieves this by omitting the `%category%` part of the rewrite rules. It also redirects URLs with the category base to one without, which is good for SEO.

Still, I'll look into this behavior and see if TSF calls something incorrectly or if WordPress feeds us the link with a dot. 
If it's the latter, I cannot resolve this.

**Comment by Dade88** [comment]
I was not aware the dot was a bug on WordPress, good to know.

Could it be considered as a new option for TSF? This way solves the lack of native solutions from WordPress core and TSF having his own options about it can be easier and more straightforward to check than any other plugin or custom implementations.

**Comment by sybrew** [comment]
We get requests for this feature often, but I never considered it helpful for SEO.

It makes the link hierarchy more logical, which is helpful for visitors when navigating... and, therefore, also for SEO. So, I guess my previous consideration was wrong.

**Comment by sybrew** [comment]
I was able to replicate the issue. It comes from the method `The_SEO_Framework\Meta\URI::get_bare_term_url()`.

That method uses [WordPress's `get_term_link()` function](https://developer.wordpress.org/reference/functions/get_term_link/):

https://github.com/sybrew/the-seo-framework/blob/2157a44ca56592e67ab7f65894a0bc16f551c298/inc/classes/meta/uri.class.php#L400-L416

Dumping the result of `$url = \get_term_link( $term_id, $taxonomy );`, we'll get the URL with the dot.

So, WordPress provides us with the URL containing the dot -- hence, I won't fix the issue.

You could strip it using this method, but I recommend using a plugin to remove the category base instead:
```php
add_filter( 'term_link', fn ( $termlink ) => str_replace( '/./', '/', $termlink ) );
```

I'm planning to add a category-base-removal feature in the next major update. Thank you for your suggestion earlier!

**Comment by Dade88** [comment]
Finally had the chance to test this, and I can confirm `add_filter( 'term_link', fn( $termlink ) => str_replace( '/./', '/', $termlink ) );` works on my side too.

I will consider the options about the taxonomies urls while waiting for the next major release.
