### ISSUE TITLE
TSF doesn't generate multiple language sitemaps with Polylang Pro

### ISSUE THREAD

**Issue by sviatoslavadamiv** [sybrew/the-seo-framework#687]
The SEO Framework (TSF) version 5.0.6 is not generating multiple language sitemaps when using Polylang Pro 3.6.1. Instead, it generates only one sitemap for the default language. The issue does not occur when using the free version of Polylang, where everything works as expected. And to this all TSF does not see the plugin for multilanguage at all and in the settings panel there is no warning text that the site has installed plugin for multilanguage.

**Comment by sybrew** [comment]
Howdy!

What's the folder name of Polylang Pro on your website? 
In that folder, is the main file called `polylang.php`?

You can find the folder inside `/wp-content/plugins/`. It and its filename should match this pattern for TSF to recognize Polylang Pro: https://github.com/sybrew/the-seo-framework/blob/5.0.6/bootstrap/init-compat.php#L43.

**Comment by sviatoslavadamiv** [comment]
Yes, you were right. My folder was named polylang-pro-master, I renamed the folder and everything works as it should!
Thanks for your help!
