### ISSUE TITLE
Deprecation notice in a site running WP 6.7 beta1

### ISSUE THREAD

**Issue by mrleemon** [sybrew/the-seo-framework#689]
**Describe the bug**
The following warning appears when trying your plugin in WP 6.7 beta1:
`Notice: Function load_plugin_textdomain was called incorrectly. Attempted to load translations for the autodescription domain too early. Translations should be loaded after the after_setup_theme action has fired, to ensure that the current user is already set up. Please see [Debugging in WordPress](https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/) for more information. (This message was added in version 6.7.0.) in xxxxxxxxxx\wp-includes\functions.php on line 6099
`

**How to reproduce the bug**
1. Install WordPress Beta Tester plugin in a site running WP 6.7 beta1
2. Add `define( 'WP_DEBUG', true );` to the `wp-config.php` file
3. Bug occurs.

**Expected behavior**
No warning

**Comment by sybrew** [comment]
Thanks for opening this bug report!

Here's the reference: https://core.trac.wordpress.org/ticket/44937

From [this commit](https://github.com/WordPress/wordpress-develop/commit/c9a6a39f772775f5e95a85913029a91dfc0dd6ab):
> Some plugins and themes load translations too early, before the current user is known.
> This happens either explicitly or through just-in-time translation loading.
>
> If the current user (and thus their locale) is not known, WordPress might attempt to load translations in the wrong locale.
