### ISSUE TITLE
Multilingual Sitemap

### ISSUE THREAD

**Issue by sybrew** [sybrew/the-seo-framework#69]
Previous: #55 

Currently, the sitemap is outputted as so (trimmed example):
***This is no longer the case since v3.0**, where only the main language is used*.
```
<url>
	<loc>http://www.example.com/english/</loc>
</url>
<url>
	<loc>http://www.example.com/deutsch/</loc>
</url>
<url>
	<loc>http://www.example.com/schweiz-deutsch/</loc>
</url>
```

With translation plugins, like WPML, we might wish to add `href` links in the sitemap as well, like so (trimmed example):
```
<url>
	<loc>http://www.example.com/english/</loc>
	<xhtml:link rel="alternate" hreflang="de" href="http://www.example.com/deutsch/" />
	<xhtml:link rel="alternate" hreflang="de-ch" href="http://www.example.com/schweiz-deutsch/" />
	<xhtml:link rel="alternate" hreflang="en" href="http://www.example.com/english/" />
</url>
```

See https://support.google.com/webmasters/answer/189077 and https://support.google.com/webmasters/answer/2620865 for more info.

Note that WPML and most other translation plugins already correctly take care of this outside of the sitemap's scope, either through meta tags or HTTP headers.

**Comment by david-treblig** [comment]
Right now, Polylang's permalinks for the sitemap are screwed as well. TSF currently only generates the sitemap with the language that the admin had active at that moment (since it's possible to have activated the global language switch at the top of the page anytime).

Even when "all" languages are selected, the sitemap seems to only output links for the main language.

**Comment by sybrew** [comment]
The global language selection will pragmatically fall back to the default language. That's why the main language is showing; i.e. the admin language when left unconfigured per user-basis.

AFAICR, Polylang also relies on cookies. While doing so, the sitemap for the selected language will be shown based on the cookie. When in incognito the sitemap for the followed front-end language should be shown.

In any case, accessing the language externally for something that's based on *in-the-loop* queries is inherently broken. You can always expect something weird going on, as it's the biggest flaw regarding working with translation plugins and it's something that will always require external support and maintenance.

That said, the sitemap doesn't yield a SERP ranking factor. So this issue will maintain a low priority.

**Comment by david-treblig** [comment]
You're right about everything, but the problem is exactly that. It's that even in icognito mode, no cookie, etc. accessing the sitemap without a language prefix (which should assume "all languages"), the sitemap doesn't generate correctly and outputs only the main language meaning not all pages are accessible by the sitemap.

**Comment by sybrew** [comment]
@david-treblig We can't assume all languages because Polylang alters the query. TSF just wants to `::get_posts()` without bias: https://developer.wordpress.org/reference/classes/wp_query/get_posts/

This issue could mean that Polylang has a bias towards the main language, or is completely unbiased in that specific query and lets WordPress decide the language (which is the main language).

It will cost a vast amount of time to figure out what and why exactly. 
> That said, the sitemap doesn't yield a SERP ranking factor. So this issue will maintain a low priority. 

Nevertheless, check out what's below for a possible solution.

## Two symptoms

### 1. Transient cache
Because `var_dump( get_locale() );` will probably drop the main locale when viewing "all languages", the cache of the main locale will be used in the sitemap.

The sitemap bases its transient cache on two variables:
1. Revision.
2. Locale.
3. Blog ID.

#### The solution: 
Disable the Sitemap transient cache in the General SEO Settings (under Performance) to see if it affects the output.

### 2. Filters are inaccessible
You could check Polylang's bias by enabling filters. If the following snippet works (PHP5.4+), then Polylang does work with filters that are otherwise inaccessible:

#### The solution:
```
add_action( 'template_redirect', function() {
	$filters = [
		'the_seo_framework_sitemap_pages_query_args',
		'the_seo_framework_sitemap_posts_query_args',
		'the_seo_framework_sitemap_cpt_query_args',
	];

	foreach ( $filters as $filter ) add_filter( $filter, function( $args ) {
		return [ 'suppress_filters' => false ];
	} );
}, 0 );
```

**Comment by ladislavsulc** [comment]
Hi, I am using Polylang and SEO Framework with 2 languages, although the sitemap is only generated for the default language. Any solution for this? Thank you.

**Comment by sybrew** [comment]
Hi @ladislavsulc 

If your issue is related to #244, please hold tight for version 3.1
If not, I must ask you to open a new issue.

**Comment by ladislavsulc** [comment]
Hi @sybrew, thank you. Will enable your sitemap when it is resolved until then I have to go with a different solution for sitemap generation. Looking forward to another great update!

**Comment by ladislavsulc** [comment]
Btw, it is not related. I have a standard domain.com and domain.com/de (example) language setup but I only see sitemap in the default language.

**Comment by ladislavsulc** [comment]
If you want to do some tests, this one, for example, works properly. https://wordpress.org/plugins/xml-sitemap-feed/

**Comment by ladislavsulc** [comment]
@sybrew sorry, I misunderstood that topic. 👍

**Comment by bramvandenbulcke** [comment]
@ladislavsulc. I'm using WPML with each language in a separate directory ("different languages in directories" and "use directory for default language" checked): /nl/ for Dutch and /fr/ for French and was really struggling finding a solution for a multilingual sitemap in combination with the SEO Framework. The XML Sitemap Feed seems to do the job! Thanks!

**Comment by ladislavsulc** [comment]
@bramvandenbulcke happy to help!

**Comment by sybrew** [comment]
From the original comment, which still remains accurate after all these years:

> Note that WPML and most other translation plugins already correctly take care of this outside of the sitemap's scope, either through meta tags or HTTP headers.

I have no intention of integrating this feature because it'll require too many queries on a single page, which can cause memory exhaustion. Such errors increase my support burden -- that is roughly 35% about the most useless SEO feature already: Sitemaps.

Closing. 

We may want to revisit this feature when WordPress integrates multilingual support natively, hopefully adding alternative language URLs as transformative metadata to each post requested, making this feature possible.
