### ISSUE TITLE
wp-admin paths in robots.txt incorrect when WP installed in subdirectory

### ISSUE THREAD

**Issue by retlehs** [sybrew/the-seo-framework#7]
when WP is [installed in a subdirectory](https://codex.wordpress.org/Giving_WordPress_Its_Own_Directory) such as on a [bedrock](https://github.com/roots/bedrock) install, robots.txt shows:

```
User-agent: *
Disallow: /wp-admin/
Allow: /wp-admin/admin-ajax.php
```

expected output is:

```
User-agent: *
Disallow: /wp/wp-admin/
Allow: /wp/wp-admin/admin-ajax.php
```

example from a bedrock install that's not running this plugin: https://roots-example-project.com/robots.txt

wordpress core uses the site URL instead of home URL for the admin paths: https://github.com/WordPress/WordPress/blob/a800cf654b7ed54fbb329fdce865672f300b1e79/wp-includes/functions.php#L1319-L1322

**Comment by sybrew** [comment]
Hi retehs,

I believe this has been solved already in the 2.6.0 Beta branch (which is now a RC). Feel free to try it out! :smile: 
I do see I've removed the starting slash, I'll remove that stray functionality a moment.

https://github.com/sybrew/the-seo-framework/blob/beta/inc/classes/sitemaps.class.php#L832-L840

**Comment by sybrew** [comment]
Fixed: https://github.com/sybrew/the-seo-framework/commit/5b4379824142bbdf7f0798290172f21b91618916

**Comment by retlehs** [comment]
thanks!
