### ISSUE TITLE
Configure content in description field for each post

### ISSUE THREAD

**Issue by jserrao** [sybrew/the-seo-framework#85]
I'm wondering how SEO Framework gets this data and is there a way to change it? It always says the descriptions are bad but wondering if there is a way to change the defaults without forking the project.

**Comment by sybrew** [comment]
Hi @jserrao,

TSF gets the fallback description data for singulars and terms from method `the_seo_framework()->fetch_excerpt()`, called by `the_seo_framework()->get_excerpt_by_id()`.
... which is called by `the_seo_framework()->generate_excerpt()`.

I'm not sure why it always says bad, but I guess you're using a page builder? Which prevents the `$post->post_content` from returning anything; because it ought to be full of shortcodes.

Either way, there currently is no overwrite filter for descriptions or its extraction; I never thought one needed to generate their own descriptions.
You can also manually fill in the custom description meta field, if needed.

If you require a filter, please inform me on when and where :) I'd be more than happy to expand the API.

Cheers!

**Comment by jserrao** [comment]
Ah, makes sense why this is pulling 'bad' descriptions on my site. I'm extensively using Advanced Custom Fields (ACF) and don't have a typical excerpt to pull, it's just getting a title and putting it into the description field now.

What I've done to fix this is kinda hacky - basically, I just generate my own description field in a WP template partial for the head, injecting after TSF to fix the problem:

```
    // Output missing descriptions from SEO framework plugin
    if (is_singular('departments') || is_singular('features') || is_singular('post')) {
      echo '<meta name="description" content="' . get_field('subtitle') .'">';
      echo '<meta name="twitter:description" content="' . get_field('subtitle') . '">';
      echo '<meta property="og:description" content="' . get_field('subtitle') . '">';
    }
```

Ideally, I'd like to be able to redirect the default description field in TSF to a custom ACF field I've made (`subtitle` in my case) with a filter.

**Comment by sybrew** [comment]
Hi @jserrao,

Just be careful it doesn't output duplicated tags, as Search Engines and Social Sites alike tend to take the first entry and might see this as an erroneous output.

I'll see what I can do with a filter in order to short-circuit the output. That would be in 2.9.0-dev1.
Tomorrow I'll commit. Cheers!

**Comment by sybrew** [comment]
Hi @jserrao,

I forgot there already was a short-circuit filter, but that will only adjust the *actual output* of the page, not all things that relate to it.

For this, the following filter should be used:
```
add_filter( 'the_seo_framework_ogdescription_output', function( $description = '', $post_or_term_id = 0 ) {

	// code here
	
	return $description;
}, 10, 2 );
```

The short-circuit filters that affects all (SEO Bar, placeholder fields, counters, etc.) are still on their way.

Cheers!

**Comment by jserrao** [comment]
Thanks, great plugin btw.

**Comment by sybrew** [comment]
Thanks! 

Also, my excuses for not implementing the new filter already &mdash; I've been feeling under the weather as of last week. Nevertheless, I'll ping this issue when it's implemented. 😄

**Comment by sybrew** [comment]
The filters:
1. `the_seo_framework_custom_field_description`
2. `the_seo_framework_generated_description`
3. `the_seo_framework_fetched_description_excerpt`

Commit: https://github.com/sybrew/the-seo-framework/commit/593bb9cf12753ca18cb2b651a0a7fd905d7a83ff

Enjoy!

**Comment by dvrcthewrld** [comment]
When this is released, we'll be able to use one of these filters to set a default og:description that will be used when no other description exists?

**Comment by sybrew** [comment]
Hi @dvrcthewrld,

Yes, that's possible. Be aware that you should never use duplicated descriptions.
Each page must have an unique description.

`the_seo_framework_custom_field_description` and `the_seo_framework_custom_field_description` work like so:
```
add_filter( 'the_seo_framework_custom_field_description', function( $description, $args ) {
    if ( ! $description ) {
        // Code here....
        $description = 'My custom description';
    }

    return $description;
}, 10, 2 );
```

**Comment by jserrao** [comment]
@sybrew - just wanted to add that these filters work very well. I've been able to customize descriptions on a couple of sites now with durable results. Thanks so much for this addition.

**Comment by PUncle** [comment]
Hi, I have a similar problem, as I extensively use ACF and don't use `the_content()` field on my custom post types at all, which leads to the SEO Framework description reporting as bad.

How would I go about using the above filters to replace my descriptions? I also thought about using an ACF save hook to duplicate content into the main content area, but would prefer not to keep 2x the description field in the database if i can avoid it.

Many thanks!

**Comment by sybrew** [comment]
Hi @PUncle 

The new filters were described earlier in this issue, and you should use: `the_seo_framework_fetched_description_excerpt`.

e.g.:
```php
add_filter( 'the_seo_framework_fetched_description_excerpt', function( $excerpt, $page_id ) {
	$field = function_exists( 'get_field' ) ? get_field( 'my-field', $page_id ) : '';
	return $field ?: $excerpt;
}, 10, 2 );
```

Regardless, I recommend using custom descriptions that fit Google's guidelines.

As the enhancement has been made a year ago--I'm locking this issue. 
If you require further support, please open a new issue.
