### ISSUE TITLE
Control SEO Box CPT support

### ISSUE THREAD

**Issue by sybrew** [sybrew/the-seo-framework#86]
Sometimes, supporting both the title and editor isn't feasible in CPT.
In any case, users wish to control the SEO Box support for their CPT.

To achieve this, a simple (yet advanced) metabox should be added in which users can select the supported post types, from a multi-select list of the current post types.

**Comment by hadamlenz** [comment]
is there a filter for this?

**Comment by sybrew** [comment]
@hadamlenz There is, it also affects the sitemap if filtered on the front-end:
https://github.com/sybrew/the-seo-framework/blob/2a05d8f846025987a5f9326a1d66e98133dd38ff/inc/classes/detect.class.php#L960-L967

**Comment by hadamlenz** [comment]
excellent, cheers

**Comment by sybrew** [comment]
Will be put in general settings, rather than an extension.

**Comment by sybrew** [comment]
This enhancement was asked for because there was "no" support automatically.
Now there "is" support automatically.

This makes this issue moot. 

Now, this enhancement should only affect removing the meta box support. This is useless, as WordPress provides enough control for this in the user screen options.
For developers wanting fine-grained support, there are plenty filters available. And the WordPress API supports this by default regardless.
