### ISSUE TITLE
Custom title/description prefix/additions

### ISSUE THREAD

**Issue by ArboLife** [sybrew/the-seo-framework#88]
Hi Sybre,

I'd like to add a setting in Javascript to make the content left of a separator (I use | ) be a floating prefix in the description field. 

However, this has to wait until the backend pulls the right content (when modified through filters and translated from WPML).

Initial conversation: https://wordpress.org/support/topic/title-description-structure-per-custom-post-types

Thanks,
Marc

**Comment by sybrew** [comment]
Related: https://github.com/sybrew/the-seo-framework/issues/71

Might require new JS data injections at PHP level and a filterable "title prefix" function, which propagates.

**Comment by sybrew** [comment]
This issue is both a feature and a bugfix.

The bug is only happening in the admin area, which is why I marked it with "Admin".

1. The "prefix/addition" code needs to be implemented.
2. The "addition" code needs to be filterable and standardized.

**Comment by sybrew** [comment]
I also found that term title collisions are still happening, but ONLY in the JS code. The [proposed code](https://github.com/sybrew/the-seo-framework/issues/88#issuecomment-439679127) should fix it. Ref: #202
