### ISSUE TITLE
Blocked content (SEO framework css and js) when using a site only accessible over https

### ISSUE THREAD

**Issue by itmustbe** [sybrew/the-seo-framework#89]
On localhost I'm able to use the SEO framework happily enough, and it's great! However, on my server vital parts of the SEO framework are not functioning properly because of the following console errors (I take it that my browser is blocking mixed content without allowing me to override that; I also had some content security policy errors along the same lines, but even when I opened that up fully for testing purposes and cleared those errors, Safari still blocks your css and js with the following warnings):

edit.php:27:117
[blocked] The page at https://[redacted]/wp-admin/edit.php?post_type=page was not allowed to run insecure content from http://[redacted]/wp-content/plugins/autodescription/lib/css/tsf.min.css?ver=2.8.2.
[blocked] The page at https://[redacted]/wp-admin/edit.php?post_type=page was not allowed to run insecure content from http://[redacted]/wp-content/plugins/autodescription/lib/js/tsf.min.js?ver=2.8.2.

Is there a way to let the SEO framework know that I'm running only over https and that it should too? Thanks so much for your fantastic plugin, I love the features :)

**Comment by itmustbe** [comment]
I made some further changes to my content security policies and that appears to have fixed this issue. I'm not actually sure quite which change I made that fixed it though, otherwise I'd report it here :/

**Comment by sybrew** [comment]
Hi @itmustbe 

1. You have/had HSTS enabled on your website, which is/was awesome!
2. On the admin side, for a weird reason, WordPress didn't enqueue the script files for `https`. This is an issue.

Be sure to update your WP version. If that doesn't work, please seek consultancy at your hosting provider regarding this issue.

The URL is generated by this function 1, which goes down this tree path to get http/https:
1. https://developer.wordpress.org/reference/functions/plugin_dir_url/
2. https://developer.wordpress.org/reference/functions/plugins_url/
3. https://developer.wordpress.org/reference/functions/set_url_scheme/
4. https://developer.wordpress.org/reference/functions/is_ssl/

At 4, that's where it can go wrong.

Best of luck!

**Comment by itmustbe** [comment]
Thank you for getting back to me! WP was up-to-date (and I'm my own host so no one to complain to besides me! :)  But whatever it was that I fiddled with that day CSP-wise, everything is working perfectly now, with The SEO Framework's js and css requests going over https:// properly (and HSTS still enabled :)  Thank you again for your help and your fantastic plugin, it is very useful indeed!!
