### ISSUE TITLE
"Fast Secure Contact Form" plugin compatibility

### ISSUE THREAD

**Issue by sybrew** [sybrew/the-seo-framework#90]
An anonymous report has been made regarding plugin compatibility between [Fast Secure Contact Form](https://wordpress.org/plugins/si-contact-form/) and The SEO Framework.

This compatibility issue gives a 500 error in the WordPress admin area if both plugins are active.

Environmental variables:
1. WordPress 4.7.x
2. PHP 5.3.x
3. Unknown webserver
4. Unknown theme
5. FSCF (unknown version)
6. The SEO Framework 2.8.x+

**I was unable to reproduce this issue.**
If anyone finds this issue, please notify. Cheers!

**Comment by ramon-villain** [comment]
I just tried to replicate the issue, and nothing happened.

WordPress 4.7.2
PHP 5.3.3
Apache/Httpd
2015/2016/2017
FSCF 4.0.49
The SEO Framework 2.8.2

**Comment by sybrew** [comment]
No significant information has been found so far. Might have been a fluke with a special combination of versions or any debugging header conflicts. Both plugins have been updated since also.

Feel free to contribute your scenario if you (the reader) still find this conflict.
