### ISSUE TITLE
Support for ACF custom fields

### ISSUE THREAD

**Issue by ooksanen** [sybrew/the-seo-framework#91]
Like this one for Yoast:
https://fi.wordpress.org/plugins/acf-content-analysis-for-yoast-seo/

**Comment by sybrew** [comment]
Hi @ooksanen,

That plugin injects data to their analyzer in real-time. The SEO Framework doesn't do that in any way.

What are you suggesting to be enhanced? Do you have an example that's related to TSF and ACF? Thanks!

**Comment by ooksanen** [comment]
Sorry @sybrew, I understood the "traffic light" in admin incorrectly. I thought it was for content analysis (if the content length is sufficent, certain keyword is found in content etc) like with Yoast "SEO score".

**Comment by sybrew** [comment]
TSF's "SEO Bar" only tracks metadata output. The content is for you to decide upon :)

If ACF can alter those meta tags directly, then a compatibility layer should be put in place.
